"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Check, MessageSquarePlus, Pencil } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AppShell } from "../../../components/AppShell";
import { ProtectedFamilyRoute, useFamilyAccess } from "../../../components/ProtectedFamilyRoute";
import { availablePlanActions, planProgressLabel, recurrenceLabel } from "../../../features/health-plan/model";
import { healthPlanTimeline, osloDate, osloTime } from "../../../features/health-plan/log";
import { mutationThenRefresh } from "../../../features/health-plan/mutation-refresh";
import { canEditHealthPlan, FamilyRequestGuard } from "../../../features/health-plan/request-context";
import { addHealthPlanNote, getHealthPlan, getHealthPlanLog, healthPlanCommand, updateHealthPlan, updateHealthPlanNotificationRecipients, getFamily, type FamilyMember, type HealthPlan, type HealthPlanAction, type HealthPlanLog } from "../../../lib/api";

const STATUS = { DRAFT: "Utkast", ACTIVE: "Aktiv", PAUSED: "Pauset", COMPLETED: "Avsluttet", ARCHIVED: "Arkivert" } as const;
type Command = Parameters<typeof healthPlanCommand>[2];

function PlanDetail() {
  const { id } = useParams<{ id: string }>();
  const access = useFamilyAccess(); const familyId = access.status === "approved" ? access.familyContext.activeFamilyId : null;
  const [plan, setPlan] = useState<HealthPlan | null>(null); const [members, setMembers] = useState<FamilyMember[]>([]); const [recipientsOpen, setRecipientsOpen] = useState(false); const [planContext, setPlanContext] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [log, setLog] = useState<HealthPlanLog | null>(null); const [warning, setWarning] = useState(""); const [tab, setTab] = useState<"plan" | "log">("plan"); const [noteOpen, setNoteOpen] = useState(false);
  const [confirm, setConfirm] = useState<{ command: Command; title: string; body: string } | null>(null); const [edit, setEdit] = useState<"metadata" | HealthPlanAction | null>(null);
  const loadGuard = useRef(new FamilyRequestGuard()); const actionGuard = useRef(new FamilyRequestGuard()); const loadController = useRef<AbortController | null>(null); const actionController = useRef<AbortController | null>(null); const contextKey = familyId && id ? `${familyId}:${id}` : null; const contextRef = useRef(contextKey); contextRef.current = contextKey;
  const load = useCallback(async () => { if (!familyId || !id) return; loadController.current?.abort(); const controller = new AbortController(); loadController.current = controller; const token = loadGuard.current.begin(); const requestContext = `${familyId}:${id}`; setLoading(true); setError(""); setWarning(""); try { const [nextPlan, nextLog, family] = await Promise.all([getHealthPlan(familyId, id, controller.signal), getHealthPlanLog(familyId, id, controller.signal), getFamily(familyId, controller.signal)]); if (!controller.signal.aborted && loadGuard.current.isCurrent(token) && contextRef.current === requestContext) { setPlan(nextPlan); setLog(nextLog); setMembers(family.members); setPlanContext(requestContext); } } catch (caught) { if (!controller.signal.aborted && loadGuard.current.isCurrent(token)) { setPlan(null); setLog(null); setPlanContext(requestContext); setError(caught instanceof Error ? caught.message : "Kunne ikke hente helseplanen."); } } finally { if (loadGuard.current.isCurrent(token)) setLoading(false); if (loadController.current === controller) loadController.current = null; } }, [familyId, id]);
  useEffect(() => { loadController.current?.abort(); actionController.current?.abort(); loadGuard.current.changeContext(contextKey); actionGuard.current.changeContext(contextKey); setPlan(null); setMembers([]); setLog(null); setPlanContext(null); setTab("plan"); setLoading(true); setError(""); setWarning(""); setBusy(false); setConfirm(null); setEdit(null); setNoteOpen(false); if (contextKey) void load(); return () => { loadController.current?.abort(); actionController.current?.abort(); loadGuard.current.invalidate(); actionGuard.current.invalidate(); }; }, [contextKey, load]);
  async function run(command: Command) { if (!familyId) return; const requestContext = contextKey; actionController.current?.abort(); const controller = new AbortController(); actionController.current = controller; const token = actionGuard.current.begin(); const isCurrent = () => !controller.signal.aborted && actionGuard.current.isCurrent(token) && contextRef.current === requestContext; setBusy(true); setError(""); setWarning(""); try { const outcome = await mutationThenRefresh({ mutation: () => healthPlanCommand(familyId, id, command, controller.signal), isCurrent, commitMutation: nextPlan => { setPlan(nextPlan); setConfirm(null); }, refresh: () => getHealthPlanLog(familyId, id, controller.signal), commitRefresh: setLog }); if (outcome === "refresh-failed" && isCurrent()) setWarning("Planen ble oppdatert, men loggen kunne ikke oppdateres. Prøv å laste siden på nytt."); } catch (caught) { if (isCurrent()) { setError(caught instanceof Error ? caught.message : "Planen ble endret et annet sted. Last inn på nytt og prøv igjen."); await load(); } } finally { if (actionController.current === controller) actionController.current = null; if (actionGuard.current.isCurrent(token)) setBusy(false); } }
  const currentPlan = planContext === contextKey ? plan : null; const actions = useMemo(() => currentPlan ? availablePlanActions(currentPlan) : null, [currentPlan]);
  const currentLevel = currentPlan?.levels?.find(level => level.id === currentPlan.activeLevelId); const up = currentPlan?.levels?.find(level => level.levelIndex === (currentLevel?.levelIndex ?? -1) + 1); const down = currentPlan?.levels?.find(level => level.levelIndex === (currentLevel?.levelIndex ?? 0) - 1);
  const switchingContext = planContext !== contextKey;
  const timeline = useMemo(() => healthPlanTimeline(log ?? { history: [], notes: [] }, new Map(currentPlan?.levels?.flatMap(level => level.steps?.map(step => [step.id, step.stepOrder] as const) ?? []) ?? [])), [log, currentPlan]);

  return <AppShell title="Helseplan"><main className="health-detail"><Link className="health-back" href="/health-plans"><ArrowLeft size={18}/> Helseplan · Planer</Link>
    {(loading || switchingContext) && <div className="health-empty" aria-live="polite">Laster helseplan …</div>}
    {!loading && !switchingContext && error && !currentPlan && <section className="health-empty"><h2>Planen ble ikke funnet</h2><p>{error}</p><button onClick={() => void load()}>Prøv igjen</button></section>}
    {currentPlan && actions && (() => { const plan = currentPlan; return <>
      <header className="health-detail-header"><div><span className={`health-status-pill health-status-pill--${plan.status.toLowerCase()}`}>{STATUS[plan.status]}</span><h1>{plan.name}</h1><p>{plan.familyMember.displayName}</p>{plan.description && <p className="health-description">{plan.description}</p>}<strong>{plan.status === "COMPLETED" ? "Planen er avsluttet" : plan.status === "ARCHIVED" ? "Planen er arkivert" : plan.status === "DRAFT" ? "Ikke startet" : planProgressLabel(plan)}</strong></div>{tab === "plan" && canEditHealthPlan(plan.status) && <button className="health-secondary" onClick={() => setEdit("metadata")}><Pencil size={16}/> Rediger</button>}</header>
      {error && <p className="health-error" role="alert">{error}</p>}
      {warning && <p className="health-warning" role="status">{warning}</p>}
      <div className="health-tabs" role="tablist" aria-label="Helseplanvisning"><button role="tab" aria-selected={tab === "plan"} onClick={() => setTab("plan")}>Plan</button><button role="tab" aria-selected={tab === "log"} onClick={() => setTab("log")}>Logg</button></div>
      {tab === "plan" && <>
      <section className="health-lifecycle" aria-label="Planhandlinger">
        {actions.start && <button className="health-primary" disabled={busy} onClick={() => void run("start")}>Start</button>}
        {actions.pause && <button className="health-primary" onClick={() => setConfirm({ command: "pause", title: "Pause denne helseplanen?", body: "Planen settes på pause. Varigheten fortsetter når planen startes igjen." })}>Pause</button>}
        {actions.resume && <button className="health-primary" disabled={busy} onClick={() => void run("resume")}>Fortsett</button>}
        {actions.levelUp && up && <button onClick={() => setConfirm({ command: "level-up", title: `Trapp opp til Trinn ${up.levelIndex}?`, body: `Planen starter på Del 1 i Trinn ${up.levelIndex}.` })}>Trapp opp</button>}
        {actions.levelDown && down && <button onClick={() => setConfirm({ command: "level-down", title: `Trapp ned til ${down.levelIndex === 0 ? "Basisplan" : `Trinn ${down.levelIndex}`}?`, body: `Planen starter på Del 1 i ${down.levelIndex === 0 ? "Basisplanen" : `Trinn ${down.levelIndex}`}.` })}>Trapp ned</button>}
        {actions.archive && <button disabled={busy} onClick={() => setConfirm({ command: "archive", title: "Arkiver denne helseplanen?", body: "Planen blir liggende i arkivet og kan fortsatt leses." })}>Arkiver</button>}
        {actions.complete && <button className="health-danger" onClick={() => setConfirm({ command: "complete", title: "Avslutt denne helseplanen?", body: "Planen blir avsluttet og nye hendelser vil ikke bli opprettet. Dette kan ikke angres i denne versjonen." })}>Avslutt plan</button>}
      </section>
      <section className="health-notifications" aria-labelledby="notification-heading"><h2 id="notification-heading">Varslinger</h2>{plan.notificationRecipients?.length ? <p>{plan.notificationRecipients.map(recipient => recipient.familyMember.displayName).join(" og ")} får varsel når en hendelse forfaller.</p> : <p>Ingen varslinger er satt opp.</p>}{canEditHealthPlan(plan.status) && <button className="health-secondary" onClick={() => setRecipientsOpen(true)}><Pencil size={16}/> Endre</button>}</section>
            <section aria-labelledby="structure-heading"><h2 id="structure-heading">Planstruktur</h2><div className="health-levels">{plan.levels?.map(level => { const levelCurrent = ["ACTIVE", "PAUSED"].includes(plan.status) && level.id === plan.activeLevelId; return <article className={`health-level ${levelCurrent ? "health-level--active" : ""}`} key={level.id}><header><h3>{level.levelIndex === 0 ? "Basisplan" : `Trinn ${level.levelIndex}`}</h3>{levelCurrent && <span><Check size={15}/> Aktivt trinn</span>}</header>{level.name && <p>{level.name}</p>}<div className="health-detail-steps">{level.steps?.map(step => { const current = levelCurrent && step.id === plan.activeStepId; return <section className={`health-detail-step ${current ? "health-detail-step--active" : ""}`} key={step.id}><header><h4>Del {step.stepOrder + 1}{step.name ? ` · ${step.name}` : ""}</h4>{current && <span>Nå · Aktiv del</span>}</header><p><strong>Varighet:</strong> {step.durationDays ? `${step.durationDays} ${step.durationDays === 1 ? "dag" : "dager"}` : "Ingen fast varighet"}</p>{step.schedules?.map(schedule => <div className="health-detail-schedule" key={schedule.id}><div><strong>Tidspunkt:</strong> {displayTime(schedule.localTime)}</div><div><strong>Gjentakelse:</strong> {recurrenceLabel(schedule)}</div><div className="health-detail-actions"><strong>Hendelser</strong>{schedule.actions.map(action => <div key={action.id}><div><b>{action.title}</b>{action.instruction && <small>{action.instruction}</small>}</div>{canEditHealthPlan(plan.status) && <button aria-label={`Rediger hendelse ${action.title}`} onClick={() => setEdit(action)}><Pencil size={15}/> Rediger hendelse</button>}</div>)}</div></div>)}</section>; })}</div></article>; })}</div></section>
      </>}
      {tab === "log" && <LogView entries={timeline} canAdd={canEditHealthPlan(plan.status)} onAdd={() => setNoteOpen(true)}/>}
    </>; })()}
    {recipientsOpen && currentPlan && familyId && <RecipientDialog members={members} selected={currentPlan.notificationRecipients?.map(recipient => recipient.familyMemberId) ?? []} busy={busy} onCancel={() => setRecipientsOpen(false)} onSave={async familyMemberIds => { const requestContext = contextKey; actionController.current?.abort(); const controller = new AbortController(); actionController.current = controller; const token = actionGuard.current.begin(); setBusy(true); setError(""); try { const next = await updateHealthPlanNotificationRecipients(familyId, currentPlan.id, familyMemberIds, controller.signal); if (!controller.signal.aborted && actionGuard.current.isCurrent(token) && contextRef.current === requestContext) { setPlan(next); setRecipientsOpen(false); } } catch (caught) { if (!controller.signal.aborted && actionGuard.current.isCurrent(token)) setError(caught instanceof Error ? caught.message : "Varslingene kunne ikke lagres."); } finally { if (actionGuard.current.isCurrent(token)) setBusy(false); } }}/>}
        {confirm && <ConfirmDialog {...confirm} busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void run(confirm.command)}/>}
    {edit && currentPlan && familyId && <EditDialog plan={currentPlan} action={edit === "metadata" ? null : edit} busy={busy} onCancel={() => setEdit(null)} onSave={async input => { const requestContext = contextKey; actionController.current?.abort(); const controller = new AbortController(); actionController.current = controller; const token = actionGuard.current.begin(); const isCurrent = () => !controller.signal.aborted && actionGuard.current.isCurrent(token) && contextRef.current === requestContext; setBusy(true); setError(""); setWarning(""); try { const outcome = await mutationThenRefresh({ mutation: () => updateHealthPlan(familyId, currentPlan.id, input, controller.signal), isCurrent, commitMutation: nextPlan => { setPlan(nextPlan); setEdit(null); }, refresh: () => getHealthPlanLog(familyId, currentPlan.id, controller.signal), commitRefresh: setLog }); if (outcome === "refresh-failed" && isCurrent()) setWarning("Endringen ble lagret, men loggen kunne ikke oppdateres. Prøv å laste siden på nytt."); } catch (caught) { if (isCurrent()) setError(caught instanceof Error ? caught.message : "Endringen kunne ikke lagres."); } finally { if (actionController.current === controller) actionController.current = null; if (actionGuard.current.isCurrent(token)) setBusy(false); } }}/>}
    {noteOpen && currentPlan && familyId && <NoteDialog busy={busy} error={error} onCancel={() => setNoteOpen(false)} onSave={async text => { const requestContext = contextKey; actionController.current?.abort(); const controller = new AbortController(); actionController.current = controller; const token = actionGuard.current.begin(); const isCurrent = () => !controller.signal.aborted && actionGuard.current.isCurrent(token) && contextRef.current === requestContext; setBusy(true); setError(""); setWarning(""); try { const outcome = await mutationThenRefresh({ mutation: () => addHealthPlanNote(familyId, currentPlan.id, { text }, controller.signal), isCurrent, commitMutation: () => setNoteOpen(false), refresh: () => getHealthPlanLog(familyId, currentPlan.id, controller.signal), commitRefresh: setLog }); if (outcome === "refresh-failed" && isCurrent()) setWarning("Notatet ble lagret, men loggen kunne ikke oppdateres. Prøv å laste siden på nytt."); } catch (caught) { if (isCurrent()) setError(caught instanceof Error ? caught.message : "Notatet kunne ikke lagres."); } finally { if (actionController.current === controller) actionController.current = null; if (actionGuard.current.isCurrent(token)) setBusy(false); } }}/>}
  </main></AppShell>;
}

function RecipientDialog({ members, selected, busy, onCancel, onSave }: { members: FamilyMember[]; selected: string[]; busy: boolean; onCancel: () => void; onSave: (ids: string[]) => Promise<void> }) { const [ids, setIds] = useState(selected); return <div className="health-modal-backdrop"><form className="health-confirm" role="dialog" aria-modal="true" onSubmit={event => { event.preventDefault(); void onSave(ids); }}><h2>Endre varslinger</h2>{members.map(member => <label key={member.id}><input type="checkbox" disabled={!member.userId} checked={ids.includes(member.id)} onChange={() => setIds(current => current.includes(member.id) ? current.filter(id => id !== member.id) : [...current, member.id])}/>{member.displayName}{!member.userId && <small> Kan ikke motta varsler – ingen egen innlogging</small>}</label>)}<footer><button type="button" onClick={onCancel}>Avbryt</button><button className="health-primary" disabled={busy} type="submit">Lagre</button></footer></form></div>; }

function displayTime(value: string) { const match = value.match(/T(\d{2}:\d{2})/); return match?.[1] ?? value.slice(0, 5); }
function targetLine(context: NonNullable<import("../../../lib/api").HealthPlanNote["targetContext"]>) { const time = context.kind === "OCCURRENCE" ? osloTime(context.scheduledAt) : displayTime(context.localTime); return `${time} · ${context.levelIndex === 0 ? "Basisplan" : `Trinn ${context.levelIndex}`} · Del ${context.stepOrder + 1}`; }
function LogView({ entries, canAdd, onAdd }: { entries: ReturnType<typeof healthPlanTimeline>; canAdd: boolean; onAdd: () => void }) { const groups = entries.reduce<Array<[string, typeof entries]>>((all, entry) => { const date = osloDate(entry.at, true); const current = all.at(-1); if (current?.[0] === date) current[1].push(entry); else all.push([date, [entry]]); return all; }, []); return <section className="health-log" aria-labelledby="log-heading"><header><h2 id="log-heading">Logg</h2>{canAdd && <button className="health-secondary" onClick={onAdd}><MessageSquarePlus size={17}/> Legg til notat</button>}</header>{entries.length === 0 ? <div className="health-empty">Ingen aktivitet ennå.</div> : groups.map(([date, items]) => <section className="health-log-day" key={date}><h3>{date}</h3><div>{items.map(entry => <article className={`health-log-entry health-log-entry--${entry.kind}`} key={entry.id}><span aria-hidden="true"/><div><strong>{entry.title}</strong>{entry.kind === "note" && entry.context && <small>{targetLine(entry.context)}</small>}{entry.kind === "note" && <p>«{entry.text}»</p>}<small>{[entry.actorDisplayName, osloTime(entry.at)].filter(Boolean).join(" · ")}</small></div></article>)}</div></section>)}</section>; }
function NoteDialog({ busy, error, onCancel, onSave }: { busy: boolean; error: string; onCancel: () => void; onSave: (text: string) => Promise<void> }) { const [text, setText] = useState(""); return <div className="health-modal-backdrop"><form className="health-confirm" role="dialog" aria-modal="true" aria-labelledby="note-title" onSubmit={event => { event.preventDefault(); void onSave(text.trim()); }}><h2 id="note-title">Notat</h2><label>Tekst<textarea autoFocus required maxLength={4000} value={text} onChange={event => setText(event.target.value)}/></label>{error && <p className="health-error" role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={onCancel}>Avbryt</button><button className="health-primary" disabled={busy || !text.trim()} type="submit">Lagre</button></footer></form></div>; }
function ConfirmDialog({ title, body, busy, onCancel, onConfirm }: { command: Command; title: string; body: string; busy: boolean; onCancel: () => void; onConfirm: () => void }) { return <div className="health-modal-backdrop"><div className="health-confirm" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" aria-describedby="confirm-body"><h2 id="confirm-title">{title}</h2><p id="confirm-body">{body}</p><footer><button autoFocus onClick={onCancel}>Avbryt</button><button className="health-primary" disabled={busy} onClick={onConfirm}>Bekreft</button></footer></div></div>; }
function EditDialog({ plan, action, busy, onCancel, onSave }: { plan: HealthPlan; action: HealthPlanAction | null; busy: boolean; onCancel: () => void; onSave: (input: { name?: string; description?: string | null; action?: { id: string; title: string; instruction: string | null } }) => Promise<void> }) { const [name, setName] = useState(action?.title ?? plan.name); const [description, setDescription] = useState(action?.instruction ?? plan.description ?? ""); return <div className="health-modal-backdrop"><form className="health-confirm" role="dialog" aria-modal="true" aria-labelledby="edit-title" onSubmit={e => { e.preventDefault(); void onSave(action ? { action: { id: action.id, title: name, instruction: description.trim() || null } } : { name, description: description.trim() || null }); }}><h2 id="edit-title">{action ? "Rediger hendelse" : "Rediger helseplan"}</h2><label>{action ? "Tittel" : "Plannavn"}<input autoFocus required value={name} onChange={e => setName(e.target.value)}/></label><label>{action ? "Instruksjon" : "Beskrivelse"}<textarea value={description} onChange={e => setDescription(e.target.value)}/></label><footer><button type="button" onClick={onCancel}>Avbryt</button><button className="health-primary" disabled={busy || !name.trim()} type="submit">Lagre</button></footer></form></div>; }

export default function HealthPlanDetailPage() { return <ProtectedFamilyRoute><PlanDetail/></ProtectedFamilyRoute>; }
