import { PASSWORD_POLICY, getPasswordValidationMessage } from "@familieappen/shared/auth/password-policy";
import { useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { Keyboard } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { AuthScreenShell, FormCard, FormField, InlineMessage, PasswordField, PrimaryButton, TextButton, AppText } from "../../src/components";
import { resetPassword } from "../../src/features/auth/api";
import { mapResetPasswordError } from "../../src/features/auth/errors";
import { getResetTokenFromParam } from "../../src/features/auth/routes";
import { theme } from "../../src/theme/tokens";
type FormValues = { password: string; confirmPassword: string };
export default function ResetPasswordScreen() { const { token: tokenParam } = useLocalSearchParams<{ token?: string | string[] }>(); const token = getResetTokenFromParam(tokenParam); const [serverError, setServerError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [showPassword, setShowPassword] = useState(false); const { control, handleSubmit, formState: { errors, isSubmitting, isValid }, watch } = useForm<FormValues>({ mode: "onChange", defaultValues: { password: "", confirmPassword: "" } }); const password = watch("password");
async function onSubmit(values: FormValues) { if (!token) return; Keyboard.dismiss(); setServerError(null); try { const response = await resetPassword({ token, password: values.password }); setMessage(response.message || "Passordet er oppdatert. Du kan logge inn med det nye passordet."); } catch (error) { setServerError(mapResetPasswordError(error)); } }
return <AuthScreenShell title="Lag nytt passord" lead="Velg et nytt passord for FamilieAppen-kontoen din."><FormCard accessibilityLabel="Skjema for nytt passord">{!token ? <InlineMessage type="error">Lenken mangler token. Be om en ny lenke.</InlineMessage> : null}{message ? <><InlineMessage type="success">{message}</InlineMessage><PrimaryButton title="Til login" onPress={() => router.replace("/(auth)/login")} /></> : <><Controller control={control} name="password" rules={{ required: "Nytt passord er påkrevd.", validate: (value) => getPasswordValidationMessage(value) || true }} render={({ field: { onChange, onBlur, value } }) => <PasswordField label="Nytt passord" visible={showPassword} onToggleVisible={() => setShowPassword((v) => !v)} error={errors.password?.message} inputProps={{ accessibilityLabel: "Nytt passord", autoCapitalize: "none", autoComplete: "new-password", onBlur, onChangeText: (text) => { setServerError(null); onChange(text); }, placeholder: PASSWORD_POLICY.helperText, returnKeyType: "next", textContentType: "newPassword", value }} />} /><AppText variant="small" style={{ color: theme.colors.textMuted }}>{PASSWORD_POLICY.helperText}</AppText><Controller control={control} name="confirmPassword" rules={{ required: "Gjenta passordet.", validate: (value) => value === password || "Passordene er ikke like." }} render={({ field: { onChange, onBlur, value } }) => <FormField label="Bekreft passord" error={errors.confirmPassword?.message} inputProps={{ accessibilityLabel: "Gjenta nytt passord", autoCapitalize: "none", autoComplete: "new-password", onBlur, onChangeText: (text) => { setServerError(null); onChange(text); }, onSubmitEditing: () => { if (isValid && !isSubmitting) void handleSubmit(onSubmit)(); }, placeholder: "Gjenta nytt passord", returnKeyType: "done", secureTextEntry: !showPassword, textContentType: "newPassword", value }} />} />{serverError ? <InlineMessage type="error">{serverError}</InlineMessage> : null}<PrimaryButton accessibilityLabel="Oppdater passord" disabled={!token || isSubmitting || !isValid} onPress={handleSubmit(onSubmit)} title={isSubmitting ? "Oppdaterer…" : "Oppdater passord"} /><TextButton title="Tilbake til login" onPress={() => router.replace("/(auth)/login")} /></>}</FormCard></AuthScreenShell> }
