"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { ChevronLeft,Copy,RefreshCw,ShieldAlert,Trash2 } from "lucide-react";
import { Badge,Button,Card,SectionHeader } from "../../../../components/ui";
import { ApiError,createCalendarExportFeed,deleteCalendarExportFeed,getCalendarExportFeed,regenerateCalendarExportFeedToken,updateCalendarExportFeed,type CalendarExportFeedSettings } from "../../../../lib/api";
import { useFamilyMembers } from "../../../../features/family/hooks/useFamilyMembers";

type Draft=Pick<CalendarExportFeedSettings,"name"|"enabled"|"includeEvents"|"includeMeals"|"includeReminders"|"includeSchoolWeekReminders"|"scope"|"selectedMemberIds">;
const fresh:Draft={name:"",enabled:true,includeEvents:true,includeMeals:true,includeReminders:true,includeSchoolWeekReminders:true,scope:"family",selectedMemberIds:[]};
export function CalendarFeedDetailClient({feedId}:{feedId?:string}){
 const {family,familyMembers}=useFamilyMembers(); const [feed,setFeed]=useState<CalendarExportFeedSettings|null>(null); const [draft,setDraft]=useState<Draft>(fresh); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
 useEffect(()=>{if(!family?.id||!feedId)return; void getCalendarExportFeed(family.id,feedId).then(value=>{setFeed(value);setDraft(value)}).catch(showError)},[family?.id,feedId]);
 function showError(e:unknown){setMessage(e instanceof ApiError?e.message:"Noe gikk galt")}
 function toggleMember(id:string){setDraft(d=>({...d,selectedMemberIds:d.selectedMemberIds.includes(id)?d.selectedMemberIds.filter(x=>x!==id):[...d.selectedMemberIds,id]}))}
 async function save(){if(!family?.id)return;setBusy(true);setMessage(null);try{const value=feedId?await updateCalendarExportFeed(family.id,feedId,draft):await createCalendarExportFeed(family.id,draft); if(!feedId){window.location.assign(`/settings/calendar/export/${value.id}`);return}setFeed(value);setDraft(value);setMessage("Endringene er lagret.")}catch(e){showError(e)}finally{setBusy(false)}}
 async function regenerate(){if(!family?.id||!feedId||!window.confirm("Den gamle lenken vil slutte å virke. Regenerere lenken?"))return;try{const value=await regenerateCalendarExportFeedToken(family.id,feedId);setFeed(value);setDraft(value);setMessage("Ny lenke er laget. Den gamle virker ikke lenger.")}catch(e){showError(e)}}
 async function remove(){if(!family?.id||!feedId||!window.confirm("Slette feeden permanent? Abonnementer med denne lenken vil slutte å oppdatere."))return;try{await deleteCalendarExportFeed(family.id,feedId);window.location.assign("/settings/calendar/export")}catch(e){showError(e)}}
 const noContent=!draft.includeEvents&&!draft.includeMeals&&!draft.includeReminders&&!draft.includeSchoolWeekReminders; const invalid=!draft.name.trim()||noContent||(draft.scope==="selectedParticipant"&&!draft.selectedMemberIds.length);
 return <main className="settings-shell settings-shell--detail calendar-export-settings"><Link className="settings-back-link" href="/settings/calendar/export"><ChevronLeft/></Link><header className="settings-hero settings-hero--detail"><h1>{feedId?draft.name||"Kalenderfeed":"Ny kalenderfeed"}</h1><p>Innhold og mottakere filtreres på serveren for akkurat denne private feeden.</p></header>
 {message?<Card tone="warm"><p>{message}</p></Card>:null}<section className="calendar-settings-section"><SectionHeader eyebrow="ICS" title="Innstillinger"/><Card className="calendar-export-card">
 <div className="calendar-export-card__intro"><div><h3>{draft.name||"Ny kalenderfeed"}</h3></div><Badge tone={draft.enabled?"success":"neutral"}>{draft.enabled?"Aktiv":"Inaktiv"}</Badge></div>
 <label className="form-field"><span className="form-field__label">Navn</span><input className="form-field__input" maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label>
 <label className="settings-toggle-row"><span><span className="settings-label">Aktiv</span><span className="settings-help">Lenken kan leses uten innlogging.</span></span><input className="settings-toggle" type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/></label>
 {feed?<div className="calendar-export-url"><span className="settings-label">Privat kalenderlenke</span><code>{feed.privateUrl}</code><div className="calendar-export-url__actions"><Button variant="secondary" onClick={()=>void navigator.clipboard.writeText(feed.privateUrl)}><Copy size={18}/> Kopier</Button><Button variant="secondary" onClick={regenerate}><RefreshCw size={18}/> Regenerer</Button></div><div className="calendar-export-warning"><ShieldAlert size={20}/><p>Alle som har lenken kan lese valgt kalenderinnhold.</p></div></div>:null}
 <div className="settings-fieldset"><div className="settings-fieldset__header"><span className="settings-label">Innhold</span><span className="settings-help">Velg minst én kategori. Middager fungerer som en selvstendig feed.</span></div>{[["includeEvents","Kalenderhendelser"],["includeMeals","Middager"],["includeReminders","Husk-påminnelser"],["includeSchoolWeekReminders","Skoleuka-påminnelser"]].map(([key,label])=><label className="settings-toggle-row" key={key}><span className="settings-label">{label}</span><input className="settings-toggle" type="checkbox" checked={Boolean(draft[key as keyof Draft])} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/></label>)}{noContent?<p className="calendar-validation">Velg minst én innholdskategori.</p>:null}</div>
 <div className="settings-fieldset"><div className="settings-fieldset__header"><span className="settings-label">Hvem kalenderhendelser gjelder</span><span className="settings-help">Personfilteret gjelder kalenderhendelser. Familieinnhold som middager påvirkes ikke.</span></div><div className="segmented-control segmented-control--export">{[["family","Hele familien"],["mine","Kun mine hendelser"],["selectedParticipant","Valgte familiemedlemmer"]].map(([value,label])=><label className="segmented-control__option" key={value}><input type="radio" checked={draft.scope===value} onChange={()=>setDraft({...draft,scope:value as Draft["scope"]})}/><span>{label}</span></label>)}</div>{draft.scope==="selectedParticipant"?<div className="calendar-member-checklist">{familyMembers.map(m=><label key={m.id}><input type="checkbox" checked={draft.selectedMemberIds.includes(m.id)} onChange={()=>toggleMember(m.id)}/><span>{m.name}</span></label>)}{!draft.selectedMemberIds.length?<p className="calendar-validation">Velg minst ett familiemedlem.</p>:null}</div>:null}</div>
 {draft.scope==="mine"&&feed?<p className="settings-help">Denne feeden gjelder {familyMembers.find(member=>member.id===feed.mineFamilyMemberId)?.name??"et familiemedlem som ikke lenger kan identifiseres"}.</p>:null}
 <div className="calendar-export-card__actions"><Button onClick={save} disabled={busy||invalid}>{feedId?"Lagre endringer":"Opprett feed"}</Button>{feedId?<Button variant="secondary" onClick={remove}><Trash2 size={18}/> Slett feed</Button>:null}</div>
 </Card></section></main>
}
