import assert from "node:assert/strict";
import test from "node:test";
import { availablePlanActions, blankLevel, blankSchedule, blankStep, buildCreateHealthPlanInput, compatiblePlanId, filterOccurrences, isOccurrenceActionable, ISO_WEEKDAYS, localDateInTimeZone, occurrenceMenuActions, planProgressLabel, plansForMember, recurrenceLabel, sortOccurrences, withStepDuration } from "./model";

const occurrence = (id: string, at: string, member = "alma", plan = "p1", status = "PENDING", planStatus = "ACTIVE") => ({ id, healthPlanId: plan, scheduledAt: at, status, healthPlan: { status: planStatus, familyMember: { id: member } } }) as never;
const plan = (id: string, member: string) => ({ id, familyMemberId: member }) as never;

test("ISO weekdays use Monday 1 through Sunday 7", () => { assert.equal(ISO_WEEKDAYS[0].value, 1); assert.equal(ISO_WEEKDAYS[6].value, 7); assert.ok(!ISO_WEEKDAYS.some(day => Number(day.value) === 0)); });
test("selected weekdays serialize unchanged and never as zero", () => { const level = blankLevel(); level.steps[0].schedules[0] = { ...blankSchedule(), recurrenceType: "WEEKDAYS", weekdays: [7, 1] }; level.steps[0].schedules[0].actions[0].title = "Smør krem"; const input = buildCreateHealthPlanInput("Plan", "", "alma", [level]); assert.deepEqual(input.levels[0].steps[0].schedules[0].weekdays, [1, 7]); assert.ok(!input.levels[0].steps[0].schedules[0].weekdays?.includes(0)); });
test("multiple steps, schedules and actions receive contiguous orders and final autoAdvance false", () => { const level = blankLevel(); level.steps = [blankStep(), blankStep(), blankStep()]; level.steps.forEach((step, index) => { step.durationDays = "2"; step.autoAdvance = true; step.schedules[0].actions[0].title = `A${index}`; }); level.steps[0].schedules.push({ ...blankSchedule(), actions: [{ title: "B", instruction: "" }, { title: "C", instruction: "" }] }); const input = buildCreateHealthPlanInput("Plan", "", "alma", [level]); assert.deepEqual(input.levels[0].steps.map(step => step.stepOrder), [0, 1, 2]); assert.equal(input.levels[0].steps[0].schedules.length, 2); assert.deepEqual(input.levels[0].steps[0].schedules[1].actions.map(action => action.sortOrder), [0, 1]); assert.equal(input.levels[0].steps[0].autoAdvance, true); assert.equal(input.levels[0].steps[2].autoAdvance, false); });
test("interval anchors use the Europe/Oslo calendar date", () => { assert.equal(localDateInTimeZone(new Date("2026-01-15T12:00:00Z"), "Europe/Oslo"), "2026-01-15"); assert.equal(localDateInTimeZone(new Date("2026-09-11T22:30:00Z"), "Europe/Oslo"), "2026-09-12"); assert.equal(localDateInTimeZone(new Date("2026-01-11T23:30:00Z"), "Europe/Oslo"), "2026-01-12"); const level = blankLevel(); level.steps[0].schedules[0] = { ...blankSchedule(), recurrenceType: "INTERVAL_DAYS" }; level.steps[0].schedules[0].actions[0].title = "A"; assert.equal(buildCreateHealthPlanInput("Plan", "", "alma", [level], new Date("2026-09-11T22:30:00Z")).levels[0].steps[0].schedules[0].anchorDate, "2026-09-12"); });
test("autoAdvance requires duration and clearing duration resets it", () => { const level = blankLevel(); level.steps = [blankStep(), blankStep()]; level.steps.forEach(step => { step.schedules[0].actions[0].title = "A"; }); level.steps[0].autoAdvance = true; assert.throws(() => buildCreateHealthPlanInput("Plan", "", "alma", [level]), /krever varighet/); level.steps[0].durationDays = "1"; assert.equal(buildCreateHealthPlanInput("Plan", "", "alma", [level]).levels[0].steps[0].autoAdvance, true); assert.deepEqual(withStepDuration(level.steps[0], ""), { ...level.steps[0], durationDays: "", autoAdvance: false }); });
test("create validation rejects weekday and interval errors", () => { const weekday = blankLevel(); weekday.steps[0].schedules[0] = { ...blankSchedule(), recurrenceType: "WEEKDAYS", weekdays: [] }; weekday.steps[0].schedules[0].actions[0].title = "A"; assert.throws(() => buildCreateHealthPlanInput("Plan", "", "alma", [weekday]), /ukedag/); weekday.steps[0].schedules[0].weekdays = [0]; assert.throws(() => buildCreateHealthPlanInput("Plan", "", "alma", [weekday]), /ukedag/); const interval = blankLevel(); interval.steps[0].schedules[0] = { ...blankSchedule(), recurrenceType: "INTERVAL_DAYS", intervalDays: 0 }; interval.steps[0].schedules[0].actions[0].title = "A"; assert.throws(() => buildCreateHealthPlanInput("Plan", "", "alma", [interval]), /Intervall/); });
test("member and plan filters compose and all-members works", () => { const items = [occurrence("a", "2026-09-11", "alma", "p1"), occurrence("b", "2026-09-11", "even", "p2")]; assert.deepEqual(filterOccurrences(items, "alma", "p1").map(x => x.id), ["a"]); assert.deepEqual(filterOccurrences(items, "", "").map(x => x.id), ["a", "b"]); });
test("changing member resets an incompatible plan", () => { const plans = [plan("p1", "alma"), plan("p2", "even")]; assert.deepEqual(plansForMember(plans, "even").map(item => item.id), ["p2"]); assert.equal(compatiblePlanId(plans, "even", "p1"), ""); assert.equal(compatiblePlanId(plans, "", "p1"), "p1"); });
test("only active unresolved occurrences are actionable", () => { for (const status of ["PENDING", "SNOOZED"]) assert.equal(isOccurrenceActionable(occurrence("a", "2026-09-11", "a", "p", status, "ACTIVE")), true); for (const planStatus of ["PAUSED", "ARCHIVED", "COMPLETED"]) assert.equal(isOccurrenceActionable(occurrence("a", "2026-09-11", "a", "p", "PENDING", planStatus)), false); for (const status of ["COMPLETED", "SKIPPED"]) assert.equal(isOccurrenceActionable(occurrence("a", "2026-09-11", "a", "p", status, "ACTIVE")), false); });
test("resolved occurrence menus contain only notes", () => { assert.deepEqual(occurrenceMenuActions(occurrence("a", "2026-09-11", "a", "p", "PENDING")), ["COMPLETED", "SKIPPED", "SNOOZED", "NOTE"]); assert.deepEqual(occurrenceMenuActions(occurrence("a", "2026-09-11", "a", "p", "SNOOZED")), ["COMPLETED", "SKIPPED", "SNOOZED", "NOTE"]); for (const status of ["COMPLETED", "SKIPPED"]) assert.deepEqual(occurrenceMenuActions(occurrence("a", "2026-09-11", "a", "p", status)), ["NOTE"]); });
test("plan progress labels use lightweight active context", () => { assert.equal(planProgressLabel({ status: "DRAFT", activeLevel: null, activeStep: null }), null); assert.equal(planProgressLabel({ status: "ACTIVE", activeLevel: { id: "l0", levelIndex: 0, name: null }, activeStep: { id: "s0", stepOrder: 0, name: null } }), "Basisplan · Del 1"); assert.equal(planProgressLabel({ status: "ACTIVE", activeLevel: { id: "l2", levelIndex: 2, name: null }, activeStep: { id: "s2", stepOrder: 2, name: null } }), "Trinn 2 · Del 3"); });
test("occurrences are chronological and stable", () => assert.deepEqual(sortOccurrences([occurrence("b", "2026-09-11T16:00:00Z"), occurrence("a", "2026-09-11T14:30:00Z")]).map(x => x.id), ["a", "b"]));
test("recurrences have human labels", () => { assert.equal(recurrenceLabel({ recurrenceType: "DAILY", weekdays: [], intervalDays: null }), "Hver dag"); assert.equal(recurrenceLabel({ recurrenceType: "WEEKDAYS", weekdays: [1, 3, 5], intervalDays: null }), "mandag, onsdag og fredag"); assert.equal(recurrenceLabel({ recurrenceType: "INTERVAL_DAYS", weekdays: [], intervalDays: 2 }), "Hver 2. dag"); });
test("detail lifecycle actions follow status and adjacent-level policy", () => { const levels = [{ id: "l0", levelIndex: 0 }, { id: "l1", levelIndex: 1 }, { id: "l2", levelIndex: 2 }] as never; const at = (status: string, activeLevelId: string | null) => availablePlanActions({ status, activeLevelId, levels } as never); assert.deepEqual(at("DRAFT", null), { start: true, pause: false, resume: false, complete: false, archive: true, levelUp: false, levelDown: false }); assert.deepEqual(at("ACTIVE", "l1"), { start: false, pause: true, resume: false, complete: true, archive: false, levelUp: true, levelDown: true }); assert.equal(at("ACTIVE", "l2").levelUp, false); assert.equal(at("ACTIVE", "l0").levelDown, false); assert.equal(at("PAUSED", "l1").resume, true); assert.equal(at("PAUSED", "l1").levelUp, false); assert.equal(at("COMPLETED", "l1").archive, true); assert.equal(at("COMPLETED", "l1").complete, false); assert.ok(Object.values(at("ARCHIVED", "l1")).every(value => !value)); });
test("terminal plans expose no occurrence comment action", () => { for (const planStatus of ["COMPLETED", "ARCHIVED"] as const) assert.deepEqual(occurrenceMenuActions(occurrence("a", "2026-09-11", "a", "p", "COMPLETED", planStatus)), []); });
