import type { CalendarEvent } from "@familieappen/shared";
import { calendarEventToDuplicateCreateForm, calendarRecurrenceOptions, createCalendarEventPayload, decodeCalendarEventInitialValues, encodeCalendarEventInitialValues, getCalendarRecurrenceLabel, isValidDateString, toLocalDateTimeString, validateCreateCalendarEventForm, type CreateCalendarEventForm } from "./createEventForm";
function assertEqual<T>(actual: T, expected: T, description: string): void { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`${description}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`); }
function form(overrides: Partial<CreateCalendarEventForm> = {}): CreateCalendarEventForm { return { title: " Trening ", date: "2026-03-29", allDay: false, startTime: "09:00", endTime: "10:00", location: " Hallen ", description: " Ta med sko ", recurrenceFrequency: "never", recurrenceUntil: "", icon: "family", reminderMinutesBefore: null, participantFamilyMemberIds: [], ...overrides }; }
assertEqual(calendarRecurrenceOptions.map(getCalendarRecurrenceLabel), ["Aldri", "Daglig", "Ukentlig", "Månedlig", "Årlig"], "all supported frequencies have Norwegian labels");
assertEqual(validateCreateCalendarEventForm(form()), {}, "valid timed event passes validation");
assertEqual(validateCreateCalendarEventForm(form({ title: "   " })).title, "Tittel må fylles ut.", "whitespace title is rejected");
assertEqual(validateCreateCalendarEventForm(form({ date: "2026-02-30" })).date, "Velg en gyldig dato.", "invalid dates are rejected");
assertEqual(validateCreateCalendarEventForm(form({ endTime: "08:59" })).endTime, "Sluttid må være etter starttid.", "end before start is rejected");
assertEqual(validateCreateCalendarEventForm(form({ allDay: true, startTime: "99:99", endTime: "00:00" })), {}, "all-day events do not require valid visible times");
assertEqual(validateCreateCalendarEventForm(form({ recurrenceFrequency: "daily", recurrenceUntil: "" })).recurrenceUntil, "Velg sluttdato for gjentakelsen.", "recurring events require an until date");
assertEqual(validateCreateCalendarEventForm(form({ recurrenceFrequency: "weekly", recurrenceUntil: "2026-03-28" })).recurrenceUntil, "Sluttdato kan ikke være før startdato.", "recurrence until before start is rejected");
assertEqual(validateCreateCalendarEventForm(form({ recurrenceFrequency: "monthly", recurrenceUntil: "2026-03-29" })), {}, "same-day recurrence until follows backend on-or-after contract");
assertEqual(validateCreateCalendarEventForm(form({ recurrenceFrequency: "yearly", recurrenceUntil: "2026-10-25" })), {}, "Norwegian DST date stays valid");
assertEqual(isValidDateString("2026-10-25"), true, "DST date validates without UTC parsing");
assertEqual(toLocalDateTimeString("2026-10-25", "09:30", false), "2026-10-25T09:30:00.000Z", "local date/time string is built without toISOString UTC shift");
assertEqual(createCalendarEventPayload(form()), { title: "Trening", description: "Ta med sko", location: "Hallen", icon: "family", reminderMinutesBefore: null, startsAt: "2026-03-29T09:00:00.000Z", endsAt: "2026-03-29T10:00:00.000Z", allDay: false, recurrenceFrequency: "never", recurrenceUntil: null, participantFamilyMemberIds: [] }, "payload matches backend create contract");
assertEqual(createCalendarEventPayload(form({ recurrenceFrequency: "weekly", recurrenceUntil: "2026-04-30" })).recurrenceUntil, "2026-04-30T23:59:59.999Z", "recurrence until is sent as backend end-of-day string without toISOString");

function event(overrides: Partial<CalendarEvent> = {}): CalendarEvent { return { id: "event-a", familyId: "family-1", title: "Bursdag", date: "2026-07-15", endDate: null, startTime: "17:00:00", endTime: "19:00:00", allDay: false, location: "Hjemme", description: "Kake", icon: "birthday", participantIds: ["member-1", "member-2"], participants: [], source: "manual", isImported: false, reminder: { label: "30 minutter før", minutesBefore: 30 }, reminderMinutesBefore: 30, recurrence: { frequency: "weekly", until: "2026-08-15T23:59:59.999Z" }, recurrenceFrequency: "weekly", recurrenceUntil: "2026-08-15T23:59:59.999Z", startsAt: "2026-07-15T17:00:00.000Z", endsAt: "2026-07-15T19:00:00.000Z", icsSourceId: null, externalUid: null, createdByUserId: "user-1", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-02T00:00:00.000Z", ...overrides } as CalendarEvent; }
const duplicate = calendarEventToDuplicateCreateForm(event());
assertEqual(duplicate, { title: "Bursdag", date: "2026-07-15", allDay: false, startTime: "17:00", endTime: "19:00", location: "Hjemme", description: "Kake", recurrenceFrequency: "weekly", recurrenceUntil: "2026-08-15", icon: "birthday", reminderMinutesBefore: 30, participantFamilyMemberIds: ["member-1", "member-2"] }, "duplicate mapping pre-fills relevant create form fields and excludes metadata ids");
assertEqual(createCalendarEventPayload(duplicate), { title: "Bursdag", description: "Kake", location: "Hjemme", icon: "birthday", reminderMinutesBefore: 30, startsAt: "2026-07-15T17:00:00.000Z", endsAt: "2026-07-15T19:00:00.000Z", allDay: false, recurrenceFrequency: "weekly", recurrenceUntil: "2026-08-15T23:59:59.999Z", participantFamilyMemberIds: ["member-1", "member-2"] }, "duplicate create payload creates a manual event without id/import/occurrence metadata");
assertEqual(calendarEventToDuplicateCreateForm(event({ source: "ics", icsSourceId: "ics-1", externalUid: "external-1" })).participantFamilyMemberIds, ["member-1", "member-2"], "imported events can be mapped to a new manual create form");
assertEqual(calendarEventToDuplicateCreateForm(event({ id: "occ-1", isRecurringOccurrence: true, recurringEventId: "series-1", occurrenceDate: "2026-07-22", date: "2026-07-22" })).recurrenceFrequency, "weekly", "occurrence duplicate follows hydrated occurrence recurrence data");
const encoded = encodeCalendarEventInitialValues(duplicate);
assertEqual(decodeCalendarEventInitialValues(encoded, form()).icon, "birthday", "encoded initial values round-trip through create route params");
