import type { CalendarEvent } from "@familieappen/shared";
import { mergeUpdatedCalendarEvent, moveCalendarEventBetweenDays, replaceCalendarEventInDay, replaceCalendarEventOccurrenceInDay, removeCalendarEventByIdFromDay, removeCalendarEventOccurrenceFromDay, removeCalendarEventSeriesFromDay } from "./cache";
function assertEqual<T>(actual: T, expected: T, description: string): void { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`${description}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`); }
function event(id: string, date = "2026-07-15", title = id): CalendarEvent { return { id, familyId: "family-1", title, date, endDate: null, startTime: "09:00", endTime: "10:00", allDay: false, location: null, description: null, icon: "family", participantIds: [], participants: [], source: "manual", isImported: false, reminder: null, reminderMinutesBefore: null, recurrence: null, recurrenceFrequency: "never", recurrenceUntil: null, startsAt: `${date}T09:00:00.000Z`, endsAt: `${date}T10:00:00.000Z`, icsSourceId: null, externalUid: null, createdByUserId: null, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" } as CalendarEvent; }
function occurrence(seriesId: string, occurrenceDate: string, title = occurrenceDate): CalendarEvent { return { ...event(`${seriesId}-${occurrenceDate}`, occurrenceDate, title), recurringEventId: seriesId, occurrenceDate, isRecurringOccurrence: true, recurrenceFrequency: "weekly", recurrence: { frequency: "weekly", until: "2026-12-31T23:59:59.999Z" } } as CalendarEvent; }
assertEqual(replaceCalendarEventInDay([event("a"), event("b")], event("a", "2026-07-15", "Ny"))?.map((item) => item.title), ["b", "Ny"], "replace updates same-day cache without duplicates");
assertEqual(moveCalendarEventBetweenDays([event("a"), event("b")], event("a", "2026-07-16"), "2026-07-15")?.map((item) => item.id), ["b"], "move removes event from old day");
assertEqual(moveCalendarEventBetweenDays([event("b")], event("a", "2026-07-16"), "2026-07-16")?.map((item) => item.id), ["a", "b"], "move inserts event into new day with sorting");
assertEqual(mergeUpdatedCalendarEvent(event("a", "2026-07-15", "Gammel"), event("a", "2026-07-15", "Ny"))?.title, "Ny", "detail cache can merge updated event");
assertEqual(replaceCalendarEventOccurrenceInDay([occurrence("series-a", "2026-07-15", "A"), occurrence("series-a", "2026-07-22", "B")], occurrence("series-a", "2026-07-15", "Ny"), { eventId: "series-a", occurrenceDate: "2026-07-15", date: "2026-07-15" })?.map((item) => item.title), ["B", "Ny"], "occurrence replace affects only selected occurrence");
assertEqual(replaceCalendarEventOccurrenceInDay([occurrence("series-a", "2026-07-15", "A")], occurrence("series-a", "2026-07-16", "Flyttet"), { eventId: "series-a", occurrenceDate: "2026-07-15", date: "2026-07-15" })?.map((item) => item.title), [], "moved occurrence is removed from old day");
assertEqual(removeCalendarEventByIdFromDay([event("a"), event("b")], "a")?.map((item) => item.id), ["b"], "single delete removes only matching event id");
assertEqual(removeCalendarEventByIdFromDay([event("a"), event("ab")], "a")?.map((item) => item.id), ["ab"], "single delete does not remove similar ids");
assertEqual(removeCalendarEventOccurrenceFromDay([occurrence("series-a", "2026-07-15"), occurrence("series-a", "2026-07-22"), occurrence("series-b", "2026-07-15")], { eventId: "series-a", occurrenceDate: "2026-07-15" })?.map((item) => item.occurrenceDate), ["2026-07-22", "2026-07-15"], "occurrence delete removes only selected series date");
assertEqual(removeCalendarEventSeriesFromDay([occurrence("series-a", "2026-07-15"), occurrence("series-a", "2026-07-22"), event("single")], "series-a")?.map((item) => item.id), ["single"], "series delete removes known cached occurrences for series");
assertEqual(removeCalendarEventOccurrenceFromDay(undefined, { eventId: "series-a", occurrenceDate: "2026-07-15" }), undefined, "occurrence delete preserves undefined cache safely");
