import type { CalendarEvent } from "@familieappen/shared";
import { calendarEventToForm, occurrenceUpdateCalendarEventPayload, updateCalendarEventPayload, validateCalendarEventForm } from "./eventForm";
function assertEqual<T>(actual: T, expected: T, description: string): void { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`${description}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`); }
function event(overrides: Partial<CalendarEvent> = {}): CalendarEvent { return { id: "event-a", familyId: "family-1", title: " Trening ", date: "2026-03-29", endDate: null, startTime: "09:00:00", endTime: "10:00:00", allDay: false, location: null, description: null, icon: "family", participantIds: [], participants: [], source: "manual", isImported: false, reminder: null, reminderMinutesBefore: null, recurrence: null, recurrenceFrequency: "never", recurrenceUntil: null, startsAt: "2026-03-29T09:00:00.000Z", endsAt: "2026-03-29T10:00:00.000Z", icsSourceId: null, externalUid: null, createdByUserId: null, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", ...overrides } as CalendarEvent; }
const hydrated = calendarEventToForm(event({ location: "", description: null }));
assertEqual(hydrated, { title: " Trening ", date: "2026-03-29", allDay: false, startTime: "09:00", endTime: "10:00", location: "", description: "", recurrenceFrequency: "never", recurrenceUntil: "" }, "maps existing event to form values without UTC date parsing");
assertEqual(calendarEventToForm(event({ recurrenceFrequency: "weekly", recurrence: { frequency: "weekly", until: "2026-10-25T23:59:59.999Z" }, recurrenceUntil: "2026-10-25T23:59:59.999Z" })).recurrenceUntil, "2026-10-25", "hydrates recurrence until without UTC shift");
assertEqual(validateCalendarEventForm({ ...hydrated, title: "   " }).title, "Tittel må fylles ut.", "edit validation rejects whitespace title");
assertEqual(updateCalendarEventPayload({ ...hydrated, title: " Ny ", location: " ", description: " Tekst " }), { title: "Ny", description: "Tekst", location: null, startsAt: "2026-03-29T09:00:00.000Z", endsAt: "2026-03-29T10:00:00.000Z", allDay: false }, "maps occurrence-safe edit form to PATCH payload by default");
assertEqual(updateCalendarEventPayload({ ...hydrated, recurrenceFrequency: "daily", recurrenceUntil: "2026-04-01" }, { includeRecurrence: true }), { title: "Trening", description: null, location: null, startsAt: "2026-03-29T09:00:00.000Z", endsAt: "2026-03-29T10:00:00.000Z", allDay: false, recurrenceFrequency: "daily", recurrenceUntil: "2026-04-01T23:59:59.999Z" }, "series edit includes recurrence fields");
assertEqual((updateCalendarEventPayload({ ...hydrated, recurrenceFrequency: "never", recurrenceUntil: "2026-04-01" }, { includeRecurrence: true }) as { recurrenceUntil?: string | null }).recurrenceUntil, null, "series edit can remove recurrence");
const occurrencePayload = occurrenceUpdateCalendarEventPayload({ ...hydrated, recurrenceFrequency: "weekly", recurrenceUntil: "2026-04-30" });
assertEqual("recurrenceFrequency" in occurrencePayload || "recurrenceUntil" in occurrencePayload || "recurrence" in occurrencePayload, false, "occurrence edit payload never sends recurrence fields");
