"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, Clock3, MoreHorizontal, Plus, X } from "lucide-react";
import { AppShell } from "../../components/AppShell";
import { ProtectedFamilyRoute, useFamilyAccess } from "../../components/ProtectedFamilyRoute";
import { addHealthPlanNote, createHealthPlan, getFamily, getHealthPlanOccurrences, getHealthPlans, healthPlanCommand, updateHealthPlanOccurrence, type CreateHealthPlanInput, type FamilyMember, type HealthPlan, type HealthPlanOccurrence } from "../../lib/api";
import { blankLevel, blankSchedule, blankStep, buildCreateHealthPlanInput, compatiblePlanId, filterOccurrences, isOccurrenceActionable, isOverdue, ISO_WEEKDAYS, localDayBounds, planProgressLabel, plansForMember, withStepDuration, type LevelDraft, type ScheduleDraft } from "../../features/health-plan/model";

const statusLabels = { DRAFT: "Utkast", ACTIVE: "Aktive", PAUSED: "Pausede", COMPLETED: "Fullførte", ARCHIVED: "Arkiverte" } as const;
const planStatusLabels = { DRAFT: "Utkast", ACTIVE: "Aktiv", PAUSED: "Pauset", COMPLETED: "Fullført", ARCHIVED: "Arkivert" } as const;

function HealthPlansContent() {
  const access = useFamilyAccess(); const familyId = access.status === "approved" ? access.familyContext.activeFamilyId : null;
  const [tab, setTab] = useState<"today" | "plans">("today"); const [members, setMembers] = useState<FamilyMember[]>([]); const [plans, setPlans] = useState<HealthPlan[]>([]); const [items, setItems] = useState<HealthPlanOccurrence[]>([]);
  const [memberId, setMemberId] = useState(""); const [planId, setPlanId] = useState(""); const [upcomingCount, setUpcomingCount] = useState(5); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [createOpen, setCreateOpen] = useState(false);
  const refresh = useCallback(async () => { if (!familyId) return; const { start, horizon } = localDayBounds(); try { setError(""); const [family, nextPlans, nextItems] = await Promise.all([getFamily(familyId), getHealthPlans(familyId), getHealthPlanOccurrences(familyId, { from: start.toISOString(), to: horizon.toISOString(), limit: 500 })]); setMembers(family.members); setPlans(nextPlans); setItems(nextItems); } catch (e) { setError(e instanceof Error ? e.message : "Kunne ikke hente helseplaner."); } }, [familyId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const filtered = useMemo(() => filterOccurrences(items, memberId, planId), [items, memberId, planId]); const { tomorrow } = localDayBounds(); const today = filtered.filter(x => new Date(x.scheduledAt) < tomorrow && (isOccurrenceActionable(x) || ["COMPLETED", "SKIPPED"].includes(x.status))); const upcoming = filtered.filter(x => new Date(x.scheduledAt) >= tomorrow && isOccurrenceActionable(x));
  function selectMember(nextMemberId: string) { setMemberId(nextMemberId); setPlanId(current => compatiblePlanId(plans, nextMemberId, current)); }
  async function occurrenceAction(item: HealthPlanOccurrence, action: "COMPLETED" | "SKIPPED" | "SNOOZED" | "NOTE", minutes = 0) { if (!familyId) return; let note: string | null = null; if (action === "NOTE") { note = window.prompt("Kommentar"); if (!note?.trim()) return; } setBusy(item.id); try { if (action === "NOTE") await addHealthPlanNote(familyId, item.healthPlanId, { occurrenceId: item.id, text: note!.trim() }); else await updateHealthPlanOccurrence(familyId, item, { status: action, ...(action === "SNOOZED" ? { scheduledAt: new Date(Date.now() + minutes * 60000).toISOString() } : {}) }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Handlingen kunne ikke lagres."); } finally { setBusy(""); } }
  async function command(plan: HealthPlan, action: Parameters<typeof healthPlanCommand>[2]) { if (!familyId) return; setBusy(plan.id); try { await healthPlanCommand(familyId, plan.id, action); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Planen kunne ikke oppdateres."); } finally { setBusy(""); } }
  return <AppShell title="Helseplan"><div className="health-page">
    <div className="health-tabs" role="tablist"><button aria-selected={tab === "today"} onClick={() => setTab("today")}>I dag</button><button aria-selected={tab === "plans"} onClick={() => setTab("plans")}>Planer</button></div>
    {error && <p className="health-error" role="alert">{error}</p>}
    {tab === "today" ? <>
      <div className="health-filters"><div><span>Familiemedlem</span><div className="health-chips"><button className={!memberId ? "active" : ""} onClick={() => selectMember("")}>Alle</button>{members.map(m => <button className={memberId === m.id ? "active" : ""} key={m.id} onClick={() => selectMember(m.id)}>{m.displayName}</button>)}</div></div><label>Plan<select value={planId} onChange={e => setPlanId(e.target.value)}><option value="">Alle planer</option>{plansForMember(plans, memberId).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
      <OccurrenceSection title="I dag" items={today} busy={busy} onAction={occurrenceAction} empty={items.length ? "Alt er gjort for i dag" : "Ingen helseplanhendelser i dag"} />
      <OccurrenceSection title="Kommende hendelser" items={upcoming.slice(0, upcomingCount)} busy={busy} onAction={occurrenceAction} empty="Ingen kommende hendelser" />
      {upcoming.length > upcomingCount && <button className="health-more" onClick={() => setUpcomingCount(n => n + 5)}>Vis flere</button>}
    </> : <><div className="health-plan-heading"><p>Administrer familiens helseplaner.</p><button className="health-primary" onClick={() => setCreateOpen(true)}><Plus size={18}/> Ny helseplan</button></div>{(Object.keys(statusLabels) as Array<keyof typeof statusLabels>).map(status => { const group = plans.filter(p => p.status === status); return group.length ? <section key={status}><h2>{statusLabels[status]}</h2><div className="health-plan-grid">{group.map(p => <PlanCard key={p.id} plan={p} busy={busy} command={command}/>)}</div></section> : null; })}{!plans.length && <div className="health-empty">Ingen helseplaner ennå.</div>}</>}
    {createOpen && familyId && <CreatePlan familyId={familyId} members={members} onClose={() => setCreateOpen(false)} onCreated={async () => { setCreateOpen(false); await refresh(); }}/>} 
  </div></AppShell>;
}

function OccurrenceSection({ title, items, busy, onAction, empty }: { title: string; items: HealthPlanOccurrence[]; busy: string; empty: string; onAction: (item: HealthPlanOccurrence, action: "COMPLETED" | "SKIPPED" | "SNOOZED" | "NOTE", minutes?: number) => void }) { return <section><h2>{title}</h2>{items.length ? <div className="health-events">{items.map(item => { const actionable = isOccurrenceActionable(item); return <article className={`health-event health-event--${item.status.toLowerCase()}`} key={item.id}><time>{new Intl.DateTimeFormat("nb-NO", { hour: "2-digit", minute: "2-digit" }).format(new Date(item.scheduledAt))}</time><div><h3>{item.actionTitle}</h3><p>{item.healthPlan.familyMember.displayName} · {item.healthPlan.name}</p>{item.occurrenceLevel && item.occurrenceStep && <small>{item.occurrenceLevel.levelIndex === 0 ? "Basisplan" : `Trinn ${item.occurrenceLevel.levelIndex}`} · Del {item.occurrenceStep.stepOrder + 1}</small>}{item.actionInstruction && <small>{item.actionInstruction}</small>}<Status item={item}/></div><details className="health-menu"><summary aria-label={`Handlinger for ${item.actionTitle}`}><MoreHorizontal/></summary><div role="menu">{actionable && <><button disabled={busy === item.id} onClick={() => onAction(item, "COMPLETED")}><Check size={16}/> Marker som utført</button><button onClick={() => onAction(item, "SKIPPED")}>Hopp over</button><button onClick={() => onAction(item, "SNOOZED", 30)}><Clock3 size={16}/> Utsett 30 min</button><button onClick={() => onAction(item, "SNOOZED", 60)}>Utsett 1 time</button></>}<button onClick={() => onAction(item, "NOTE")}>Legg til kommentar</button></div></details></article>; })}</div> : <div className="health-empty">{empty}</div>}</section>; }
function Status({ item }: { item: HealthPlanOccurrence }) { if (item.status === "COMPLETED") return <span className="health-status"><Check size={14}/> Utført{item.completedAt ? ` ${new Intl.DateTimeFormat("nb-NO", { hour: "2-digit", minute: "2-digit" }).format(new Date(item.completedAt))}` : ""}</span>; if (item.status === "SKIPPED") return <span className="health-status">Hoppet over</span>; if (item.status === "SNOOZED") return <span className="health-status">Utsatt</span>; return isOverdue(item) ? <span className="health-status">Forsinket</span> : null; }
function PlanCard({ plan, busy, command }: { plan: HealthPlan; busy: string; command: (plan: HealthPlan, action: Parameters<typeof healthPlanCommand>[2]) => void }) { const progress = planProgressLabel(plan); return <article className="health-plan-card"><h3>{plan.name}</h3><p>{plan.familyMember.displayName}</p><small>{planStatusLabels[plan.status]}{progress ? ` · ${progress}` : ""}</small><div>{plan.status === "DRAFT" && <button onClick={() => command(plan, "start")}>Start</button>}{plan.status === "ACTIVE" && <><button onClick={() => command(plan, "pause")}>Pause</button><button onClick={() => command(plan, "level-up")}>Trapp opp</button><button onClick={() => command(plan, "level-down")}>Trapp ned</button></>}{plan.status === "PAUSED" && <button onClick={() => command(plan, "resume")}>Fortsett</button>}{["DRAFT", "ACTIVE", "PAUSED", "COMPLETED"].includes(plan.status) && <button disabled={busy === plan.id} onClick={() => command(plan, "archive")}>Arkiver</button>}</div></article>; }

function CreatePlan({ familyId, members, onClose, onCreated }: { familyId: string; members: FamilyMember[]; onClose: () => void; onCreated: () => void }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [memberId, setMemberId] = useState(members[0]?.id ?? ""); const [levels, setLevels] = useState<LevelDraft[]>([blankLevel()]); const [error, setError] = useState("");
  const changeStep = (li: number, sti: number, change: (step: LevelDraft["steps"][number]) => LevelDraft["steps"][number]) => setLevels(current => current.map((level, index) => index === li ? { ...level, steps: level.steps.map((step, stepIndex) => stepIndex === sti ? change(step) : step) } : level));
  const changeSchedule = (li: number, sti: number, si: number, change: (schedule: ScheduleDraft) => ScheduleDraft) => changeStep(li, sti, step => ({ ...step, schedules: step.schedules.map((schedule, scheduleIndex) => scheduleIndex === si ? change(schedule) : schedule) }));
  async function submit(e: React.FormEvent) { e.preventDefault(); try { setError(""); const input: CreateHealthPlanInput = buildCreateHealthPlanInput(name, description, memberId, levels); await createHealthPlan(familyId, input); onCreated(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Kontroller feltene."); } }
  return <div className="health-modal-backdrop"><form className="health-modal" onSubmit={submit} noValidate><header><div><small>Ny helseplan</small><h2>Grunninfo og plan</h2></div><button type="button" aria-label="Lukk" onClick={onClose}><X/></button></header>{error && <p role="alert" className="health-error">{error}</p>}
    <section className="health-create-section"><h3>Grunninfo</h3><label>Navn<input required value={name} onChange={e => setName(e.target.value)}/></label><label>Familiemedlem<select required value={memberId} onChange={e => setMemberId(e.target.value)}><option value="">Velg familiemedlem</option>{members.map(member => <option value={member.id} key={member.id}>{member.displayName}</option>)}</select></label><label>Beskrivelse (valgfritt)<textarea value={description} onChange={e => setDescription(e.target.value)}/></label></section>
    {levels.map((level, li) => <fieldset key={li}><legend>{li === 0 ? "Basisplan" : `Trinn ${li}`}</legend>
      {level.steps.map((step, sti) => <section className="health-step" key={sti}><div className="health-step-heading"><h3>Del {sti + 1}</h3>{level.steps.length > 1 && <button type="button" onClick={() => setLevels(current => current.map((item, index) => index === li ? { ...item, steps: item.steps.filter((_, stepIndex) => stepIndex !== sti).map((remaining, remainingIndex, all) => remainingIndex === all.length - 1 ? { ...remaining, autoAdvance: false } : remaining) } : item))}>Fjern del</button>}</div>
        <label>Varighet i dager (valgfritt)<input min="1" step="1" type="number" value={step.durationDays} onChange={e => changeStep(li, sti, current => withStepDuration(current, e.target.value))}/></label>
        {step.schedules.map((schedule, si) => <div className="health-schedule" key={si}><div className="health-step-heading"><strong>Tidspunkt {si + 1}</strong>{step.schedules.length > 1 && <button type="button" onClick={() => changeStep(li, sti, current => ({ ...current, schedules: current.schedules.filter((_, index) => index !== si) }))}>Fjern tidspunkt</button>}</div><label>Tidspunkt<input required type="time" value={schedule.localTime} onChange={e => changeSchedule(li, sti, si, current => ({ ...current, localTime: e.target.value }))}/></label><label>Gjentakelse<select value={schedule.recurrenceType} onChange={e => changeSchedule(li, sti, si, current => ({ ...current, recurrenceType: e.target.value as ScheduleDraft["recurrenceType"] }))}><option value="DAILY">Hver dag</option><option value="WEEKDAYS">Utvalgte ukedager</option><option value="INTERVAL_DAYS">Hver X. dag</option></select></label>
          {schedule.recurrenceType === "WEEKDAYS" && <div className="health-weekdays">{ISO_WEEKDAYS.map(day => <label key={day.value}><input type="checkbox" checked={schedule.weekdays.includes(day.value)} onChange={() => changeSchedule(li, sti, si, current => ({ ...current, weekdays: current.weekdays.includes(day.value) ? current.weekdays.filter(value => value !== day.value) : [...current.weekdays, day.value] }))}/>{day.label}</label>)}</div>}
          {schedule.recurrenceType === "INTERVAL_DAYS" && <label>Antall dager<input min="1" step="1" type="number" value={schedule.intervalDays} onChange={e => changeSchedule(li, sti, si, current => ({ ...current, intervalDays: e.target.value }))}/></label>}<strong>Hendelser</strong>{schedule.actions.map((action, ai) => <div className="health-action-input" key={ai}><input aria-label={`Hendelse ${ai + 1}`} required placeholder="Hva skal gjøres?" value={action.title} onChange={e => changeSchedule(li, sti, si, current => ({ ...current, actions: current.actions.map((item, index) => index === ai ? { ...item, title: e.target.value } : item) }))}/>{schedule.actions.length > 1 && <button type="button" aria-label={`Fjern hendelse ${ai + 1}`} onClick={() => changeSchedule(li, sti, si, current => ({ ...current, actions: current.actions.filter((_, index) => index !== ai) }))}><X size={16}/></button>}</div>)}<button type="button" onClick={() => changeSchedule(li, sti, si, current => ({ ...current, actions: [...current.actions, { title: "", instruction: "" }] }))}>+ Legg til hendelse</button></div>)}
        <button type="button" onClick={() => changeStep(li, sti, current => ({ ...current, schedules: [...current.schedules, blankSchedule()] }))}>+ Legg til tidspunkt</button>
        {sti < level.steps.length - 1 && <label><input type="checkbox" disabled={step.durationDays === ""} checked={step.autoAdvance} onChange={e => changeStep(li, sti, current => ({ ...current, autoAdvance: e.target.checked }))}/> Gå automatisk til neste delsteg etter varigheten</label>}
      </section>)}<button type="button" onClick={() => setLevels(current => current.map((item, index) => index === li ? { ...item, steps: [...item.steps, blankStep()] } : item))}>+ Legg til delsteg</button></fieldset>)}
    <button type="button" onClick={() => setLevels(current => [...current, blankLevel()])}>+ Legg til trinn</button><footer><button type="button" onClick={onClose}>Avbryt</button><button className="health-primary" type="submit">Opprett plan</button></footer></form></div>;
}
export default function HealthPlansPage() { return <ProtectedFamilyRoute><HealthPlansContent/></ProtectedFamilyRoute>; }
