import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { createHash, randomBytes } from "node:crypto";
import { EmailService, getAppBaseUrl } from "../email";
import { FamilyAuthorizationService } from "../families";
import { PrismaService } from "../prisma";
import { AddShoppingItemRequestDto, CreateShoppingListRequestDto, ShoppingCatalogCategoryDto, ShoppingCatalogItemDto, ShoppingListDto, ShoppingListInvitationDto, ShoppingListInviteRequestDto, ShoppingListInviteResponseDto, ShoppingListInvitePreviewDto, ShoppingListItemDto, ShoppingListSummaryDto, UpdateShoppingItemRequestDto, UpdateFamilyCustomShoppingItemRequestDto, AddShoppingItemResponseDto } from "./dto/shopping.dto";

const DEFAULT_SHOPPING_LIST_NAME = "Family Shopping";
const ACTIVE_INVITE_STATUSES = ["pending", "accepted"];

type AnyClient = typeof PrismaService.prototype.client & { shoppingListInvitation: any; shoppingListAccess: any; familyCustomShoppingItem: any };
type Rec = any;
function normalizeShoppingSearchValue(value: string): string { return value.trim().toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/æ/g, "ae").replace(/ø/g, "o").replace(/å/g, "a").replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim(); }

@Injectable()
export class ShoppingService {
  constructor(private readonly prisma: PrismaService, private readonly familyAuthorization: FamilyAuthorizationService, private readonly emailService: EmailService) {}
  private get db(): AnyClient { return this.prisma.client as AnyClient; }

  async getCatalogCategories(familyId?: string): Promise<ShoppingCatalogCategoryDto[]> { const categories = await this.prisma.client.shoppingCatalogCategory.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }], include: { _count: { select: { items: true } } } }); const mapped = (categories as Rec[]).map((c) => ({ id: c.id, name: c.name, slug: c.slug, sortOrder: c.sortOrder, totalItemCount: c._count?.items ?? 0 })); const customItems = familyId ? await this.db.familyCustomShoppingItem.findMany({ where: { familyId, deletedAt: null }, select: { categorySlug: true } }) : []; const counts = new Map<string, number>(); for (const item of customItems as Rec[]) counts.set(item.categorySlug, (counts.get(item.categorySlug) ?? 0) + 1); return this.withCustomCategory(mapped.map((category) => ({ ...category, totalItemCount: category.totalItemCount + (counts.get(category.slug) ?? 0) })), counts.get("egne-varer") ?? 0); }
  async getCatalogItems(userId?: string, familyId?: string): Promise<ShoppingCatalogItemDto[]> { if (familyId && userId) await this.familyAuthorization.requireFamilyMember(userId, familyId); const items = await this.prisma.client.shoppingCatalogItem.findMany({ orderBy: [{ category: { sortOrder: "asc" } }, { sortOrder: "asc" }, { name: "asc" }], include: { category: { select: { slug: true, name: true } } } }); const custom = familyId ? await this.db.familyCustomShoppingItem.findMany({ where: { familyId, deletedAt: null }, orderBy: [{ categorySlug: "asc" }, { name: "asc" }] }) : []; return [...(items as Rec[]).map((item) => this.toShoppingCatalogItemDto(item)), ...(custom as Rec[]).map((item) => this.toFamilyCustomItemDto(item))]; }
  async searchCatalog(query: string, userId?: string, familyId?: string): Promise<ShoppingCatalogItemDto[]> { const q = normalizeShoppingSearchValue(query); if (q.length < 2) return []; if (familyId && userId) await this.familyAuthorization.requireFamilyMember(userId, familyId); const items = await this.prisma.client.shoppingCatalogItem.findMany({ orderBy: [{ category: { sortOrder: "asc" } }, { sortOrder: "asc" }, { name: "asc" }], include: { category: { select: { slug: true, name: true } } } }); const global = (items as Rec[]).filter((item) => (item.searchValues ?? [item.name, ...item.aliases].map(normalizeShoppingSearchValue)).some((v: string) => v.includes(q))).map((item) => this.toShoppingCatalogItemDto(item)); const custom = familyId ? await this.db.familyCustomShoppingItem.findMany({ where: { familyId, deletedAt: null }, orderBy: [{ name: "asc" }] }) : []; return [...global, ...(custom as Rec[]).filter((item) => item.normalizedName.includes(q)).map((item) => this.toFamilyCustomItemDto(item))]; }

  async listShoppingLists(userId: string, familyId: string): Promise<ShoppingListSummaryDto[]> { await this.familyAuthorization.requireFamilyMember(userId, familyId); await this.getOrCreateFamilyShoppingList(familyId); const lists = await this.db.shoppingList.findMany({ where: { OR: [{ familyId, isDefault: true }, { ownerUserId: userId }, { accesses: { some: { userId } } }] }, include: { invitations: { orderBy: { createdAt: "desc" } }, accesses: { include: { user: { select: { id: true, name: true, email: true } } }, orderBy: { createdAt: "asc" } } }, orderBy: [{ isDefault: "desc" }, { createdAt: "asc" }] }); return lists.map((l: Rec) => this.toShoppingListSummaryDto(l)); }
  async createShoppingList(userId: string, familyId: string, input: CreateShoppingListRequestDto = {}): Promise<ShoppingListDto> {
    await this.familyAuthorization.requireFamilyMember(userId, familyId);
    const name = this.validateName(input.name);
    const list = await this.db.shoppingList.create({
      data: {
        name,
        isDefault: false,
        family: { connect: { id: familyId } },
        ownerUser: { connect: { id: userId } },
        accesses: { create: { user: { connect: { id: userId } } } }
      },
      include: this.listInclude()
    });
    return this.toShoppingListDto(list);
  }
  async getShoppingList(userId: string, familyId: string, listId?: string): Promise<ShoppingListDto> { await this.familyAuthorization.requireFamilyMember(userId, familyId); const list = listId ? await this.getAccessibleListOrThrow(userId, familyId, listId) : await this.getOrCreateFamilyShoppingList(familyId); return this.toShoppingListDto(list); }

  async addItem(userId: string, familyId: string, input: AddShoppingItemRequestDto = {}, listId?: string): Promise<AddShoppingItemResponseDto> { const label = this.validateLabel(input.label); const unit = this.validateOptionalText(input.unit, "Shopping item unit", 40) ?? "stk"; const category = this.validateOptionalText(input.category, "Shopping item category", 60) ?? "egne-varer"; const customItemId = this.validateOptionalText(input.customItemId, "Custom item id", 80); const shouldCreateCustom = input.createCustom === true; const catalogItem = customItemId ? await this.getFamilyCustomItemOrThrow(familyId, customItemId) : shouldCreateCustom ? await this.createCustomItemOrThrow(userId, familyId, label, unit, input.quantity, category, input.note) : await this.findFamilyCustomItem(familyId, label); const list = await this.getAccessibleListOrThrow(userId, familyId, listId ?? (await this.getOrCreateFamilyShoppingList(familyId)).id); const item = await this.prisma.client.shoppingListItem.create({ data: { shoppingListId: list.id, familyCustomShoppingItemId: catalogItem?.id ?? null, label, quantity: this.validateOptionalText(input.quantity, "Shopping item quantity", 60), unit, note: this.validateOptionalText(input.note, "Shopping item note", 240), category, createdByUserId: userId } }); return { item: this.toShoppingListItemDto(item), catalogItem: catalogItem ? this.toFamilyCustomItemDto(catalogItem) : null }; }
  async updateItem(userId: string, familyId: string, itemId: string, input: UpdateShoppingItemRequestDto = {}, listId?: string): Promise<ShoppingListItemDto> { const item = await this.getAccessibleShoppingItemOrThrow(userId, familyId, itemId, listId); const updated = await this.prisma.client.shoppingListItem.update({ where: { id: item.id }, data: { label: this.validateLabel(input.label), quantity: this.validateOptionalText(input.quantity, "Shopping item quantity", 60), unit: this.validateOptionalText(input.unit, "Shopping item unit", 40), note: this.validateOptionalText(input.note, "Shopping item note", 240), category: this.validateOptionalText(input.category, "Shopping item category", 60) } }); return this.toShoppingListItemDto(updated); }
  async toggleItem(userId: string, familyId: string, itemId: string, listId?: string): Promise<ShoppingListItemDto> { const item = await this.getAccessibleShoppingItemOrThrow(userId, familyId, itemId, listId); const checked = !item.checked; const updated = await this.prisma.client.shoppingListItem.update({ where: { id: item.id }, data: { checked, checkedByUserId: checked ? userId : null, checkedAt: checked ? new Date() : null } }); return this.toShoppingListItemDto(updated); }
  async deleteItem(userId: string, familyId: string, itemId: string, listId?: string): Promise<ShoppingListItemDto> { const item = await this.getAccessibleShoppingItemOrThrow(userId, familyId, itemId, listId); const deleted = await this.prisma.client.shoppingListItem.delete({ where: { id: item.id } }); return this.toShoppingListItemDto(deleted); }
  async updateCustomItem(userId: string, familyId: string, itemId: string, input: UpdateFamilyCustomShoppingItemRequestDto = {}): Promise<ShoppingCatalogItemDto> { await this.familyAuthorization.requireFamilyMember(userId, familyId); const existing = await this.db.familyCustomShoppingItem.findFirst({ where: { id: itemId, familyId, deletedAt: null } }); if (!existing) throw new NotFoundException("Egen vare finnes ikke"); const name = input.name == null ? existing.name : this.validateLabel(input.name); const normalizedName = normalizeShoppingSearchValue(name); const global = await this.prisma.client.shoppingCatalogItem.findUnique({ where: { normalizedName } }); if (global) throw new ConflictException("Denne varen finnes allerede i varekatalogen."); const duplicate = await this.db.familyCustomShoppingItem.findFirst({ where: { familyId, normalizedName, deletedAt: null, id: { not: existing.id } } }); if (duplicate) throw new ConflictException("Denne varen finnes allerede i Egne varer."); const updated = await this.db.familyCustomShoppingItem.update({ where: { id: existing.id }, data: { name, normalizedName, defaultUnit: this.validateOptionalText(input.defaultUnit, "Default unit", 40) ?? existing.defaultUnit, suggestedQuantity: this.validateQuantity(input.suggestedQuantity, existing.suggestedQuantity), categorySlug: this.validateOptionalText(input.categorySlug, "Category", 60) ?? existing.categorySlug, iconKey: this.validateOptionalText(input.iconKey, "Icon", 80) } }); await this.prisma.client.shoppingListItem.updateMany({ where: { familyCustomShoppingItemId: updated.id, shoppingList: { familyId } }, data: { label: updated.name, unit: updated.defaultUnit, quantity: String(updated.suggestedQuantity), category: updated.categorySlug } }); return this.toFamilyCustomItemDto(updated); }
  async deleteCustomItem(userId: string, familyId: string, itemId: string): Promise<{ ok: true }> { await this.familyAuthorization.requireFamilyMember(userId, familyId); const existing = await this.db.familyCustomShoppingItem.findFirst({ where: { id: itemId, familyId, deletedAt: null } }); if (!existing) throw new NotFoundException("Egen vare finnes ikke"); await this.db.familyCustomShoppingItem.update({ where: { id: existing.id }, data: { deletedAt: new Date() } }); return { ok: true }; }

  async getShoppingSummary(userId: string, familyId: string) { await this.familyAuthorization.requireFamilyMember(userId, familyId); const list = await this.getOrCreateFamilyShoppingList(familyId); const [uncheckedCount, totalItems] = await Promise.all([this.prisma.client.shoppingListItem.count({ where: { shoppingListId: list.id, checked: false } }), this.prisma.client.shoppingListItem.count({ where: { shoppingListId: list.id } })]); return { uncheckedCount, totalItems }; }

  async inviteByEmail(userId: string, familyId: string, listId: string, input: ShoppingListInviteRequestDto = {}): Promise<ShoppingListInviteResponseDto> { const list = await this.getAccessibleListOrThrow(userId, familyId, listId); if (list.isDefault) throw new BadRequestException("Standardlisten kan ikke deles ennå"); if (list.ownerUserId !== userId) throw new ForbiddenException("Bare eieren kan dele handlelisten"); const invitedEmail = this.validateEmail((input.email ?? input.invitedEmail ?? input.invited_email) as unknown); const inviter = await this.prisma.client.user.findUnique({ where: { id: userId } }) as Rec; if (inviter.email.toLowerCase() === invitedEmail) throw new BadRequestException("Du kan ikke invitere deg selv"); const invitedUser = await this.prisma.client.user.findUnique({ where: { email: invitedEmail } }) as Rec | null; if (invitedUser && await this.hasExplicitListAccess(invitedUser.id, list.id)) throw new ConflictException("Denne e-postadressen har allerede tilgang"); const existing = await this.db.shoppingListInvitation.findFirst({ where: { shoppingListId: list.id, invitedEmail: { equals: invitedEmail, mode: "insensitive" }, status: { in: ACTIVE_INVITE_STATUSES } } }); if (existing?.status === "pending") throw new ConflictException("Det finnes allerede en ventende invitasjon til denne e-postadressen"); if (existing?.status === "accepted") throw new ConflictException("Denne e-postadressen har allerede tilgang"); const token = randomBytes(32).toString("base64url"); const data = { invitedUserId: invitedUser?.id ?? null, tokenHash: this.hashToken(token), status: "pending", revokedAt: null, declinedAt: null, acceptedAt: null }; const invitation = await this.db.shoppingListInvitation.create({ data: { ...data, shoppingListId: list.id, familyId, invitedEmail, createdByUserId: userId } }); const inviteUrl = `${getAppBaseUrl()}/shopping/invite/${encodeURIComponent(token)}`; const email = await this.emailService.sendEmail({ to: invitedEmail, template: "shopping-list-invite", data: { inviteUrl, inviterName: inviter.name, listName: this.formatListName(list) } }); return { invitation: this.toInvitationDto(invitation), email: { ok: email.ok, mode: email.mode } }; }
  async acceptInvite(userId: string, token: string): Promise<ShoppingListInvitationDto> { const inv = await this.getInvitationByTokenOrThrow(token); if (inv.status !== "pending") throw new BadRequestException("Invitasjonen kan ikke aksepteres"); await this.assertRecipient(userId, inv); const updated = await this.db.$transaction(async (transaction) => { const tx = transaction as unknown as AnyClient; await tx.shoppingListAccess.upsert({ where: { shoppingListId_userId: { shoppingListId: inv.shoppingListId, userId } }, update: {}, create: { shoppingListId: inv.shoppingListId, userId } }); return tx.shoppingListInvitation.update({ where: { id: inv.id }, data: { status: "accepted", invitedUserId: userId, acceptedAt: new Date() } }); }); return this.toInvitationDto(updated); }
  async getInvitePreview(token: string): Promise<ShoppingListInvitePreviewDto> { const inv = await this.getInvitationByTokenOrThrow(token); return { id: inv.id, shoppingListId: inv.shoppingListId, listName: this.formatListName(inv.shoppingList), invitedEmail: inv.invitedEmail, inviterName: inv.createdByUser?.name ?? "FamilieAppen", status: inv.status, requiresAuth: true }; }
  async revokeInvite(userId: string, familyId: string, listId: string, invitationId: string): Promise<ShoppingListInvitationDto> { const list = await this.getAccessibleListOrThrow(userId, familyId, listId); if (list.ownerUserId !== userId) throw new ForbiddenException("Bare eieren kan trekke tilbake invitasjoner"); const invitation = await this.db.shoppingListInvitation.findFirst({ where: { id: invitationId, shoppingListId: list.id } }); if (!invitation) throw new NotFoundException("Invitasjonen finnes ikke"); if (invitation.status !== "pending") throw new BadRequestException("Bare ventende invitasjoner kan trekkes tilbake"); const updated = await this.db.shoppingListInvitation.update({ where: { id: invitation.id }, data: { status: "revoked", revokedAt: new Date() } }); return this.toInvitationDto(updated); }
  async removeCollaborator(userId: string, familyId: string, listId: string, collaboratorUserId: string): Promise<void> { const list = await this.getAccessibleListOrThrow(userId, familyId, listId); if (list.isDefault) throw new BadRequestException("Standardlisten kan ikke endres her"); if (list.ownerUserId === collaboratorUserId) throw new BadRequestException("Eieren kan ikke fjernes fra egen liste"); const isSelfRemoval = userId === collaboratorUserId; if (list.ownerUserId !== userId && !isSelfRemoval) throw new ForbiddenException("Bare eieren kan fjerne andre fra handlelisten"); if (!isSelfRemoval && list.ownerUserId !== userId) throw new ForbiddenException("Bare eieren kan fjerne tilgang"); const access = await this.db.shoppingListAccess.findFirst({ where: { shoppingListId: list.id, userId: collaboratorUserId } }); if (!access) throw new NotFoundException("Tilgangen finnes ikke"); await this.db.shoppingListAccess.delete({ where: { id: access.id } }); }

  private async getOrCreateFamilyShoppingList(familyId: string): Promise<Rec> { let list = await this.db.shoppingList.findFirst({ where: { familyId, isDefault: true }, include: this.listInclude() }); if (list) return list; list = await this.db.shoppingList.findFirst({ where: { familyId }, include: this.listInclude() }); if (list) return this.db.shoppingList.update({ where: { id: list.id }, data: { isDefault: true }, include: this.listInclude() }); return this.db.shoppingList.create({ data: { familyId, name: DEFAULT_SHOPPING_LIST_NAME, isDefault: true }, include: this.listInclude() }); }
  private async getAccessibleListOrThrow(userId: string, familyId: string, listId: string): Promise<Rec> { const list = await this.db.shoppingList.findFirst({ where: { id: listId, OR: [{ familyId, isDefault: true }, { ownerUserId: userId }, { accesses: { some: { userId } } }] }, include: this.listInclude() }); if (!list) throw new NotFoundException("Shopping list was not found"); if (list.isDefault) await this.familyAuthorization.requireFamilyMember(userId, list.familyId); return list; }
  private async getAccessibleShoppingItemOrThrow(userId: string, familyId: string, itemId: string, listId?: string): Promise<Rec> { const item = await this.prisma.client.shoppingListItem.findFirst({ where: { id: itemId, ...(listId ? { shoppingListId: listId } : {}), shoppingList: { OR: [{ familyId, isDefault: true }, { ownerUserId: userId }, { accesses: { some: { userId } } }] } } }); if (!item) throw new NotFoundException("Shopping item was not found"); if ((item as Rec).shoppingList?.isDefault) await this.familyAuthorization.requireFamilyMember(userId, (item as Rec).shoppingList.familyId); return item; }
  private async getInvitationByTokenOrThrow(token: string): Promise<Rec> { const inv = await this.db.shoppingListInvitation.findFirst({ where: { tokenHash: this.hashToken(token) }, include: { shoppingList: true, createdByUser: true } }); if (!inv) throw new NotFoundException("Invitasjonen finnes ikke"); return inv; }
  private async assertRecipient(userId: string, inv: Rec) { const user = await this.prisma.client.user.findUnique({ where: { id: userId } }) as Rec | null; if (!user || user.email.toLowerCase() !== inv.invitedEmail.toLowerCase()) throw new ForbiddenException("Invitasjonen tilhører en annen e-postadresse"); }
  private async hasExplicitListAccess(userId: string, listId: string): Promise<boolean> { return Boolean(await this.db.shoppingListAccess.findFirst({ where: { userId, shoppingListId: listId } })); }
  private async createCustomItemOrThrow(userId: string, familyId: string, name: string, defaultUnit: string, quantity: unknown, categorySlug: string, iconKey: unknown): Promise<Rec> { const normalizedName = normalizeShoppingSearchValue(name); const global = await this.prisma.client.shoppingCatalogItem.findUnique({ where: { normalizedName } }); if (global) throw new ConflictException("Denne varen finnes allerede i varekatalogen."); const duplicate = await this.db.familyCustomShoppingItem.findFirst({ where: { familyId, normalizedName, deletedAt: null } }); if (duplicate) throw new ConflictException("Denne varen finnes allerede i Egne varer."); const data = { name, normalizedName, defaultUnit, suggestedQuantity: this.validateQuantity(quantity, 1), categorySlug, iconKey: this.validateOptionalText(iconKey, "Icon", 80), createdByUserId: userId }; return this.db.familyCustomShoppingItem.create({ data: { ...data, familyId } }); }
  private async findFamilyCustomItem(familyId: string, name: string): Promise<Rec | null> { return this.db.familyCustomShoppingItem.findFirst({ where: { familyId, normalizedName: normalizeShoppingSearchValue(name), deletedAt: null } }); }
  private async getFamilyCustomItemOrThrow(familyId: string, itemId: string): Promise<Rec> { const item = await this.db.familyCustomShoppingItem.findFirst({ where: { id: itemId, familyId, deletedAt: null } }); if (!item) throw new NotFoundException("Egen vare finnes ikke"); return item; }
  private validateQuantity(v: unknown, fallback: number) { if (v == null || v === "") return fallback; const n = typeof v === "number" ? v : Number(String(v).trim().replace(",", ".")); if (!Number.isFinite(n) || n < 0) return fallback; return Math.max(1, Math.round(n)); }
  private withCustomCategory(categories: ShoppingCatalogCategoryDto[], customCount: number) { const base = categories.filter((c) => c.slug !== "egne-varer"); return [...base, { id: "family-custom-egne-varer", name: "Egne varer", slug: "egne-varer", sortOrder: 999, totalItemCount: customCount }]; }
  private listInclude() { return { items: { orderBy: [{ checked: "asc" }, { createdAt: "asc" }] }, invitations: { orderBy: { createdAt: "desc" } }, accesses: { include: { user: { select: { id: true, name: true, email: true } } }, orderBy: { createdAt: "asc" } } }; }
  private hashToken(token: string) { return createHash("sha256").update(token).digest("hex"); }
  private validateName(v: unknown) { if (typeof v !== "string") throw new BadRequestException("Shopping list name is required"); const name = v.trim(); if (name.length < 1 || name.length > 80) throw new BadRequestException("Shopping list name must be between 1 and 80 characters"); return name; }
  private validateEmail(v: unknown) { if (typeof v !== "string") throw new BadRequestException("E-post er påkrevd"); const email = v.trim().toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new BadRequestException("Ugyldig e-postadresse"); return email; }
  private validateLabel(v: unknown) { if (typeof v !== "string") throw new BadRequestException("Shopping item label is required"); const label = v.trim(); if (label.length < 1 || label.length > 120) throw new BadRequestException("Shopping item label must be between 1 and 120 characters"); return label; }
  private validateOptionalText(v: unknown, name: string, max: number): string | null { if (v == null) return null; if (typeof v !== "string") throw new BadRequestException(`${name} must be text`); const text = v.trim(); if (text.length > max) throw new BadRequestException(`${name} must be ${max} characters or fewer`); return text || null; }
  private formatListName(l: Rec) { return !l.name || l.name === DEFAULT_SHOPPING_LIST_NAME ? "Familiehandleliste" : l.name; }
  private toShoppingCatalogItemDto(item: Rec): ShoppingCatalogItemDto { return { id: item.id, name: item.name, categorySlug: item.category.slug, categoryLabel: item.category.name, aliases: item.aliases, defaultUnit: item.defaultUnit, suggestedQuantity: item.suggestedQuantity }; }
  private toFamilyCustomItemDto(item: Rec): ShoppingCatalogItemDto { return { id: item.id, name: item.name, categorySlug: item.categorySlug, categoryLabel: this.getCategoryLabel(item.categorySlug), aliases: [], defaultUnit: item.defaultUnit, suggestedQuantity: item.suggestedQuantity, isCustom: true }; }
  private toShoppingListSummaryDto(l: Rec): ShoppingListSummaryDto { return { id: l.id, familyId: l.familyId, name: this.formatListName(l), isDefault: Boolean(l.isDefault), ownerUserId: l.ownerUserId ?? null, createdAt: l.createdAt.toISOString(), updatedAt: l.updatedAt.toISOString(), invitations: l.invitations?.map((i: Rec) => this.toInvitationDto(i)), collaborators: l.accesses?.filter((a: Rec) => a.userId !== l.ownerUserId).map((a: Rec) => ({ id: a.id, userId: a.userId, name: a.user?.name ?? null, email: a.user?.email ?? "", createdAt: a.createdAt.toISOString() })) }; }
  private toShoppingListDto(l: Rec): ShoppingListDto { return { ...this.toShoppingListSummaryDto(l), items: (l.items ?? []).map((i: Rec) => this.toShoppingListItemDto(i)) }; }
  private toInvitationDto(i: Rec): ShoppingListInvitationDto { return { id: i.id, shoppingListId: i.shoppingListId, invitedEmail: i.invitedEmail, invitedUserId: i.invitedUserId ?? null, status: i.status, acceptedAt: i.acceptedAt?.toISOString() ?? null, createdAt: i.createdAt.toISOString(), updatedAt: i.updatedAt.toISOString() }; }
  private getCategoryLabel(slug: string) { return slug === "egne-varer" ? "Egne varer" : slug; }
  private toShoppingListItemDto(i: Rec): ShoppingListItemDto { return { id: i.id, shoppingListId: i.shoppingListId, familyCustomShoppingItemId: i.familyCustomShoppingItemId ?? null, label: i.label, quantity: i.quantity, unit: i.unit, note: i.note, category: i.category, checked: i.checked, createdByUserId: i.createdByUserId, checkedByUserId: i.checkedByUserId, checkedAt: i.checkedAt?.toISOString() ?? null, createdAt: i.createdAt.toISOString(), updatedAt: i.updatedAt.toISOString() }; }
}
