"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { fetchAdminStatistics } from "../../lib/admin-client-api";
import { AdminApiError, type AdminStatistics } from "../../lib/admin-shared";

export function AdminStatisticsClient({ initialStatistics, initialError }: { initialStatistics: AdminStatistics | null; initialError?: "forbidden" | "error" }) {
  const router = useRouter(); const [stats,setStats]=useState(initialStatistics); const [error,setError]=useState(initialError); const [loading,setLoading]=useState(false);
  async function retry(){ setLoading(true); setError(undefined); try{ setStats(await fetchAdminStatistics()); } catch(err){ if(err instanceof AdminApiError && err.status===401){ router.replace("/admin/login"); return; } setError(err instanceof AdminApiError && err.status===403 ? "forbidden" : "error"); } finally { setLoading(false); } }
  const max = Math.max(1, ...(stats?.registrationsPerDay.map((d)=>d.count) ?? [0]));
  return <section className="admin-data-page" aria-labelledby="statistics-title"><div className="admin-page-header"><p>Statistics</p><h1 id="statistics-title">Admin statistics</h1><span>Read-only aggregate usage metrics from the admin API.</span></div>{loading ? <div className="admin-state admin-state--inline" role="status">Loading statistics…</div> : null}{error === "forbidden" ? <div className="admin-state admin-state--inline" role="alert"><h2>Access denied</h2><p>You do not have permission to view statistics.</p></div> : error ? <div className="admin-alert" role="alert"><p>Statistics could not be loaded. Please try again.</p><button className="admin-button" onClick={() => void retry()}>Retry</button></div> : null}{stats && !error ? <><div className="admin-metrics"><Metric label="Total users" value={stats.totalUsers} text="Registered users"/><Metric label="Total families" value={stats.totalFamilies} text="Family workspaces"/><Metric label="Active calendar imports" value={stats.activeCalendarImports} text="Enabled ICS imports"/></div><section className="admin-panel"><h2>Registrations over the last 30 days</h2><div className="admin-bars" aria-label="Daily registration counts">{stats.registrationsPerDay.map((d)=><div className="admin-bar-row" key={d.date}><span>{formatDay(d.date)}</span><div aria-hidden="true"><i style={{width:`${Math.max(4,(d.count/max)*100)}%`}} /></div><strong>{d.count}</strong></div>)}</div></section><section className="admin-panel"><h2>Feature activity, last 30 days</h2><div className="admin-metrics admin-metrics--compact"><Metric label="Calendar events" value={stats.calendarEventsCreatedLast30Days} text="Created events"/><Metric label="Tasks" value={stats.tasksCreatedLast30Days} text="Created tasks"/><Metric label="Reminders" value={stats.remindersCreatedLast30Days} text="Created reminders"/></div></section><section className="admin-panel"><h2>Advertisement status summary</h2>{stats.advertisementsByStatus.length ? <table className="admin-table"><thead><tr><th>Status</th><th>Count</th></tr></thead><tbody>{stats.advertisementsByStatus.map((a)=><tr key={a.status}><td>{labelStatus(a.status)}</td><td>{a.count}</td></tr>)}</tbody></table> : <p className="admin-muted">No advertisement records currently.</p>}</section></> : null}</section>;
}
function Metric({label,value,text}:{label:string;value:number;text:string}){ return <article className="admin-metric-card"><p>{label}</p><strong>{new Intl.NumberFormat("en").format(value)}</strong><span>{value === 0 ? "No records currently" : text}</span></article>; }
function formatDay(v:string){ return new Intl.DateTimeFormat("en", { month:"short", day:"numeric" }).format(new Date(`${v}T00:00:00Z`)); }
function labelStatus(v:string){ return v.charAt(0)+v.slice(1).toLowerCase(); }
