import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
const form = readFileSync("components/admin/AdminAdvertisementFormClient.tsx", "utf8");
const clientApi = readFileSync("lib/admin-client-api.ts", "utf8");
const shared = readFileSync("lib/admin-shared.ts", "utf8");
assert(form.includes('status:"DRAFT"'));
assert(form.includes('router.replace(`/admin/advertisements/${saved.id}?created=1`)'));
assert(form.includes('Image upload is available after this draft is saved'));
assert(form.includes('MOBILE') && form.includes('TABLET') && form.includes('DESKTOP'));
assert(form.includes('accept={accept}') && form.includes('image/jpeg,image/png,image/webp'));
assert(form.includes('URL.createObjectURL') && form.includes('URL.revokeObjectURL'));
assert(form.includes('Uploading this file will replace the current'));
assert(form.includes('Remove tablet creative?') || form.includes('Remove ${v.toLowerCase()} creative?'));
assert(form.includes('Publishing is blocked until'));
assert(form.includes('This advertisement uses the legacy format'));
assert(form.includes('alt={form.altText||'));
assert(clientApi.includes('FormData') && clientApi.includes('body.set("image", file)'));
assert(clientApi.includes('/images/${variant}'));
assert(shared.includes('adminAdvertisementErrorMessage'));
console.log("admin advertisement creative source tests passed");
