import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
const form = readFileSync("components/admin/AdminAdvertisementFormClient.tsx", "utf8");
const css = readFileSync("app/globals.css", "utf8");
const stats = readFileSync("components/admin/AdminStatisticsClient.tsx", "utf8");
const clientApi = readFileSync("lib/admin-client-api.ts", "utf8");
const shared = readFileSync("lib/admin-shared.ts", "utf8");
assert(form.includes('status:"DRAFT"'));
assert(form.includes('router.replace(`/admin/advertisements/${saved.id}?created=1`)'));
assert(form.includes('Image upload is available after this draft is saved'));
assert(form.includes('MOBILE') && form.includes('TABLET') && form.includes('DESKTOP'));
assert(form.includes('accept={accept}') && form.includes('image/jpeg,image/png,image/webp'));
assert(form.includes('URL.createObjectURL') && form.includes('URL.revokeObjectURL'));
assert(form.includes('Uploading this file will replace the current'));
assert(form.includes('Remove tablet creative?') || form.includes('Remove ${v.toLowerCase()} creative?'));
assert(form.includes('Publishing is blocked until'));
assert(form.includes('This advertisement uses the legacy format'));
assert(form.includes('alt={form.altText||'));
assert(form.includes('admin-placement-list') && form.includes('admin-placement-row'));
assert(form.includes('form.placements.includes(p)') && form.includes('[...form.placements,p]'));
assert(form.includes('Advertisement statistics') && form.includes('last7Days') && form.includes('last30Days') && form.includes('perPlacement'));
assert(css.includes('.admin-creative-preview') && css.includes('max-width: 100%') && css.includes('object-fit: contain') && css.includes('max-height: 12rem'));
assert(css.includes('.admin-creative-grid { grid-template-columns: 1fr; }'));
assert(css.includes('.admin-placement-row') && css.includes('.admin-placement-box') && css.includes('input:checked'));
assert(stats.includes('Advertisement statistics') && stats.includes('Overall CTR') && stats.includes('activeAdvertisementCount'));
assert(clientApi.includes('FormData') && clientApi.includes('body.set("image", file)'));
assert(clientApi.includes('/images/${variant}'));
assert(shared.includes('adminAdvertisementErrorMessage') && shared.includes('AdvertisementStats'));
console.log("admin advertisement creative source tests passed");
