import { useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { Keyboard, Pressable } from "react-native";
import { Link } from "expo-router";
import { AppText, AuthScreenShell, FormCard, FormField, InlineMessage, PrimaryButton } from "../../src/components";
import { forgotPassword } from "../../src/features/auth/api";
import { GENERIC_FORGOT_PASSWORD_MESSAGE } from "../../src/features/auth/errors";
import { ApiError } from "../../src/lib/api/client";
import { theme } from "../../src/theme/tokens";
type FormValues = { email: string };
export default function ForgotPasswordScreen() { const [message, setMessage] = useState<string | null>(null); const [serverError, setServerError] = useState<string | null>(null); const { control, handleSubmit, formState: { errors, isSubmitting, isValid } } = useForm<FormValues>({ mode: "onChange", defaultValues: { email: "" } });
async function onSubmit(values: FormValues) { Keyboard.dismiss(); setServerError(null); setMessage(null); try { await forgotPassword({ email: values.email.trim() }); setMessage(GENERIC_FORGOT_PASSWORD_MESSAGE); } catch (error) { if (error instanceof ApiError && error.code === "network.unavailable") setServerError(error.message); else if (error instanceof ApiError && (error.status === 400 || error.status === 404)) setMessage(GENERIC_FORGOT_PASSWORD_MESSAGE); else setServerError("Kunne ikke sende forespørselen akkurat nå. Prøv igjen."); } }
return <AuthScreenShell title="Glemt passord?" lead="Skriv inn e-postadressen din. Av sikkerhetshensyn viser vi samme melding uansett om adressen finnes."><FormCard accessibilityLabel="Glemt passord-skjema"><Controller control={control} name="email" rules={{ required: "E-post er påkrevd.", pattern: { value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/, message: "Skriv inn en gyldig e-postadresse." } }} render={({ field: { onChange, onBlur, value } }) => <FormField label="E-post" error={errors.email?.message} inputProps={{ accessibilityLabel: "E-postadresse", autoCapitalize: "none", autoComplete: "email", autoCorrect: false, editable: !isSubmitting, inputMode: "email", keyboardType: "email-address", onBlur, onChangeText: (text) => { setServerError(null); onChange(text); }, onSubmitEditing: () => { if (isValid && !isSubmitting) void handleSubmit(onSubmit)(); }, placeholder: "navn@eksempel.no", returnKeyType: "send", textContentType: "username", value }} />} />{message ? <InlineMessage type="success">{message}</InlineMessage> : null}{serverError ? <InlineMessage type="error">{serverError}</InlineMessage> : null}<PrimaryButton accessibilityLabel="Send passordlenke" disabled={isSubmitting || !isValid} onPress={handleSubmit(onSubmit)} title={isSubmitting ? "Sender…" : "Send informasjon"} /><Link href="/(auth)/login" asChild><Pressable accessibilityRole="link" style={{ minHeight: 44, justifyContent: "center" }}><AppText style={{ color: theme.colors.primaryStrong, fontWeight: "800", textAlign: "center" }}>Tilbake til login</AppText></Pressable></Link></FormCard></AuthScreenShell> }
