import { useState } from "react";
import { Pressable, RefreshControl, StyleSheet, View } from "react-native";
import { Screen } from "../../../components/Screen";
import { AppText } from "../../../components/AppText";
import { EmptyState, ErrorState } from "../../../components/States";
import { theme } from "../../../theme/tokens";
import { useHusk } from "../hooks/useHusk";
import { useReminderCompletion } from "../hooks/useReminderMutations";
import { emptyReminderState, type ReminderFilter } from "../reminderHistory";
import { HuskSection } from "./HuskSection";
import { ReminderList } from "./ReminderList";
import { ReminderSkeleton } from "./ReminderSkeleton";
export function HuskShell() { const [filter, setFilter] = useState<ReminderFilter>("active"); const husk = useHusk(filter); const completion = useReminderCompletion(); const empty = emptyReminderState(filter); const action = filter === "active" ? "complete" : "undo"; const changeFilter = (next: ReminderFilter) => setFilter(next); return <Screen bottomInset="tab" refreshControl={<RefreshControl refreshing={husk.refreshing} onRefresh={() => void husk.refresh()} tintColor={theme.colors.primary} />}><View style={styles.header}><AppText variant="title">Husk</AppText><AppText style={styles.description}>Påminnelser og lister for familien.</AppText></View><View style={styles.filter} accessibilityRole="tablist" accessibilityLabel="Filter påminnelser"><FilterButton selected={filter === "active"} title="Aktive" onPress={() => changeFilter("active")} /><FilterButton selected={filter === "history"} title="Historikk" onPress={() => changeFilter("history")} /></View>{husk.loading ? <ReminderSkeleton /> : husk.error ? <ErrorState description="Kunne ikke hente Husk akkurat nå." onRetry={() => void husk.refresh()} /> : <HuskSection title={filter === "active" ? "Aktive" : "Historikk"}>{husk.reminders.length ? <ReminderList reminders={husk.reminders} action={action} actionBusy={completion.saving ? "pending" : null} onAction={(id) => void (action === "complete" ? completion.complete(id) : completion.undo(id))} /> : <EmptyState {...empty} />}{completion.error ? <AppText style={styles.error}>{completion.error}</AppText> : null}</HuskSection>}</Screen>; }
function FilterButton({ title, selected, onPress }: { title: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} accessibilityRole="tab" accessibilityState={{ selected }} accessibilityLabel={`Vis ${title.toLowerCase()} påminnelser`} accessibilityHint="Bytter hvilken type påminnelser som vises." style={[styles.filterButton, selected && styles.filterButtonSelected]}><AppText style={[styles.filterText, selected && styles.filterTextSelected]}>{title}</AppText></Pressable>; }
const styles = StyleSheet.create({ header: { gap: theme.spacing.xs }, description: { color: theme.colors.textMuted }, filter: { flexDirection: "row", gap: theme.spacing.sm }, filterButton: { minHeight: 44, justifyContent: "center", paddingHorizontal: theme.spacing.md, borderRadius: theme.radius.pill, backgroundColor: theme.colors.primarySoft }, filterButtonSelected: { backgroundColor: theme.colors.primaryStrong }, filterText: { color: theme.colors.primaryStrong, fontWeight: "800" }, filterTextSelected: { color: theme.colors.surface }, error: { color: theme.colors.error } });
