import { useEffect, useState } from "react";
import { router } from "expo-router";
import { Modal, Pressable, RefreshControl, StyleSheet, Switch, TextInput, View } from "react-native";
import { Screen } from "../../../components/Screen";
import { AppText } from "../../../components/AppText";
import { EmptyState, ErrorState } from "../../../components/States";
import { theme } from "../../../theme/tokens";
import { useHusk, type HuskView } from "../hooks/useHusk";
import { useReminderCompletion } from "../hooks/useReminderMutations";
import { emptyReminderState, type ReminderFilter } from "../reminderHistory";
import { HuskSection } from "./HuskSection";
import { ReminderList } from "./ReminderList";
import { ReminderSkeleton } from "./ReminderSkeleton";
import { HuskListCard } from "./HuskListCard";
import { HuskViewSwitcher } from "./HuskViewSwitcher";
import { selectHuskView } from "../viewState";
import { useSchoolWeekMutations } from "../hooks/useSchoolWeekMutations";
import type { SchoolWeekReminderViewModel } from "../models";

export function HuskShell() {
  const [filter, setFilter] = useState<ReminderFilter>("active");
  const [view, setView] = useState<HuskView>("reminders");
  const husk = useHusk(filter, view);
  const completion = useReminderCompletion();
  const schoolMutations = useSchoolWeekMutations(husk.weekStart);
  const [schoolFormOpen, setSchoolFormOpen] = useState(false);
  const [editingSchoolItem, setEditingSchoolItem] = useState<SchoolWeekReminderViewModel | null>(null);
  const empty = emptyReminderState(filter);
  const action = filter === "active" ? "complete" : "undo";
  return <Screen bottomInset="tab" refreshControl={<RefreshControl refreshing={husk.refreshing} onRefresh={() => void husk.refresh()} tintColor={theme.colors.primary} />}>
    <View style={styles.header}><AppText variant="title">Husk</AppText><AppText style={styles.description}>Påminnelser og lister for familien.</AppText></View>
    <HuskViewSwitcher view={view} onChange={(nextView) => setView(selectHuskView({ view, reminderFilter: filter }, nextView).view)} />
    {view === "school-week" ? <Pressable accessibilityRole="button" accessibilityLabel="Legg til skolehusk" onPress={() => { setEditingSchoolItem(null); setSchoolFormOpen(true); }} style={styles.addButton}><AppText style={styles.addButtonText}>+ Ny skolehusk</AppText></Pressable> : null}
    {view === "reminders" ? <><View style={styles.filter} accessibilityRole="tablist" accessibilityLabel="Filter påminnelser"><FilterButton selected={filter === "active"} title="Aktive" onPress={() => setFilter("active")} /><FilterButton selected={filter === "history"} title="Historikk" onPress={() => setFilter("history")} /></View>
      {husk.loading ? <ReminderSkeleton /> : husk.missingContext ? <ErrorState title="Mangler familietilgang" description="Vi finner ikke en aktiv familie for Husk akkurat nå." onRetry={() => void husk.refresh()} /> : husk.error ? <ErrorState description="Kunne ikke hente Husk akkurat nå." onRetry={() => void husk.refresh()} /> : <HuskSection title={filter === "active" ? "Aktive" : "Historikk"}>{husk.reminders.length ? <ReminderList reminders={husk.reminders} action={action} actionBusy={completion.saving ? "pending" : null} onAction={(id) => void (action === "complete" ? completion.complete(id) : completion.undo(id))} /> : <EmptyState {...empty} />}{completion.error ? <AppText style={styles.error}>{completion.error}</AppText> : null}</HuskSection>}</> :
      view === "lists" ? husk.loading ? <ReminderSkeleton /> : husk.missingContext ? <ErrorState title="Mangler familietilgang" description="Vi finner ikke en aktiv familie for Husk akkurat nå." onRetry={() => void husk.refresh()} /> : husk.error ? <ErrorState description="Kunne ikke hente listene akkurat nå." onRetry={() => void husk.refresh()} /> : <HuskSection title="Aktive lister">{husk.lists.length ? husk.lists.map((list) => <HuskListCard key={list.id} list={list} onPress={() => router.push(`/(app)/husk/lists/${list.id}`)} />) : <EmptyState title="Ingen lister ennå" description="Det er ingen aktive lister for familien." />}</HuskSection> :
      husk.loading ? <ReminderSkeleton /> : husk.missingContext ? <ErrorState title="Mangler familietilgang" description="Vi finner ikke en aktiv familie for Skoleuka akkurat nå." onRetry={() => void husk.refresh()} /> : husk.error ? <ErrorState description="Kunne ikke hente Skoleuka akkurat nå." onRetry={() => void husk.refresh()} /> : <HuskSection title="Skoleuka">{husk.schoolWeek.length ? husk.schoolWeek.map((item) => <Pressable key={item.id} onPress={() => { setEditingSchoolItem(item); setSchoolFormOpen(true); }} style={styles.schoolCard} accessible accessibilityRole="summary" accessibilityLabel={`${item.dayLabel}: ${item.title} for ${item.childLabel}`}><AppText style={styles.schoolDay}>{item.dayLabel} • {item.childLabel}</AppText><AppText style={styles.schoolTitle}>{item.title}</AppText>{item.note ? <AppText style={styles.schoolNote}>{item.note}</AppText> : null}</Pressable>) : <EmptyState title="Ingen skolehusk denne uka" description="Skoleuka er tom for valgt familie." />}</HuskSection>}
    <SchoolWeekForm visible={schoolFormOpen} item={editingSchoolItem} children={husk.familyMembers.filter((member) => member.includeInSchoolWeek)} weekStart={husk.weekStart} saving={schoolMutations.saving} error={schoolMutations.error} onClose={() => { setSchoolFormOpen(false); schoolMutations.resetError(); }} onSave={async (payload) => { if (editingSchoolItem) await schoolMutations.update({ id: editingSchoolItem.id, payload: { ...payload, scope: editingSchoolItem.isRecurring ? "series" : undefined, occurrenceDate: editingSchoolItem.occurrenceDate ?? undefined } }); else await schoolMutations.create(payload); setSchoolFormOpen(false); }} onDelete={editingSchoolItem ? async () => { await schoolMutations.remove({ id: editingSchoolItem.id, scope: editingSchoolItem.isRecurring ? "series" : undefined, occurrenceDate: editingSchoolItem.occurrenceDate ?? undefined }); setSchoolFormOpen(false); } : undefined} />
  </Screen>;
}

function SchoolWeekForm({ visible, item, children, weekStart, saving, error, onClose, onSave, onDelete }: { visible: boolean; item: SchoolWeekReminderViewModel | null; children: { id: string; displayName: string }[]; weekStart: string; saving: boolean; error: string | null; onClose: () => void; onSave: (payload: { childFamilyMemberId: string; title: string; icon: string; weekday: "monday" | "tuesday" | "wednesday" | "thursday" | "friday"; date: string; isRecurring: boolean; recurrenceFrequency: "weekly"; recurrenceEndDate: string | null; note: string | null }) => Promise<void>; onDelete?: () => Promise<void> }) {
  const weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday"] as const;
  const labels = { monday: "Mandag", tuesday: "Tirsdag", wednesday: "Onsdag", thursday: "Torsdag", friday: "Fredag" };
  const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [childId, setChildId] = useState(""); const [weekday, setWeekday] = useState<typeof weekdays[number]>("monday"); const [recurring, setRecurring] = useState(false);
  useEffect(() => {
    if (!visible) return;
    setTitle(item?.title ?? "");
    setNote(item?.note ?? "");
    setChildId(item?.childFamilyMemberId ?? children[0]?.id ?? "");
    setWeekday((item?.weekday ?? "monday") as typeof weekdays[number]);
    setRecurring(item?.isRecurring ?? false);
  }, [children, item, visible]);
  const date = addDays(weekStart, weekdays.indexOf(weekday));
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalBackdrop}><View style={styles.formCard}><AppText variant="title">{item ? "Rediger skolehusk" : "Ny skolehusk"}</AppText><TextInput value={title} onChangeText={setTitle} placeholder="Tittel" placeholderTextColor={theme.colors.placeholder} style={styles.input} />
  <TextInput value={note} onChangeText={setNote} placeholder="Notat" placeholderTextColor={theme.colors.placeholder} style={styles.input} />
  <View style={styles.options}>{children.map((child) => <Pressable key={child.id} onPress={() => setChildId(child.id)} style={[styles.choice, childId === child.id && styles.choiceSelected]}><AppText>{child.displayName}</AppText></Pressable>)}</View><View style={styles.options}>{weekdays.map((day) => <Pressable key={day} onPress={() => setWeekday(day)} style={[styles.choice, weekday === day && styles.choiceSelected]}><AppText>{labels[day]}</AppText></Pressable>)}</View><View style={styles.rowSwitch}><AppText>Gjenta ukentlig</AppText><Switch value={recurring} onValueChange={setRecurring} /></View>{error ? <AppText style={styles.error}>{error}</AppText> : null}<Pressable disabled={saving || !title.trim() || !childId} onPress={() => void onSave({ childFamilyMemberId: childId, title: title.trim(), icon: "backpack", weekday, date, isRecurring: recurring, recurrenceFrequency: "weekly", recurrenceEndDate: null, note: note.trim() || null })} style={styles.addButton}><AppText style={styles.addButtonText}>{saving ? "Lagrer …" : "Lagre"}</AppText></Pressable>{onDelete ? <Pressable disabled={saving} onPress={() => void onDelete()} style={styles.deleteButton}><AppText style={styles.deleteText}>Slett</AppText></Pressable> : null}<Pressable onPress={onClose} style={styles.choice}><AppText>Avbryt</AppText></Pressable></View></View></Modal>;
}
function addDays(date: string, days: number) { const value = new Date(`${date}T00:00:00.000Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); }

function FilterButton({ title, selected, onPress }: { title: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} accessibilityRole="tab" accessibilityState={{ selected }} accessibilityLabel={`Vis ${title.toLowerCase()} påminnelser`} accessibilityHint="Bytter hvilken type påminnelser som vises." style={[styles.filterButton, selected && styles.filterButtonSelected]}><AppText style={[styles.filterText, selected && styles.filterTextSelected]}>{title}</AppText></Pressable>; }
const styles = StyleSheet.create({ header: { gap: theme.spacing.xs }, description: { color: theme.colors.textMuted }, filter: { flexDirection: "row", gap: theme.spacing.sm }, filterButton: { minHeight: 44, justifyContent: "center", paddingHorizontal: theme.spacing.md, borderRadius: theme.radius.pill, backgroundColor: theme.colors.primarySoft }, filterButtonSelected: { backgroundColor: theme.colors.primaryStrong }, filterText: { color: theme.colors.primaryStrong, fontWeight: "800" }, filterTextSelected: { color: theme.colors.surface }, error: { color: theme.colors.error }, addButton: { minHeight: 44, alignItems: "center", justifyContent: "center", borderRadius: theme.radius.pill, backgroundColor: theme.colors.primaryStrong, paddingHorizontal: theme.spacing.md }, addButtonText: { color: theme.colors.surface, fontWeight: "800" }, modalBackdrop: { flex: 1, justifyContent: "center", padding: theme.spacing.lg, backgroundColor: "rgba(15, 23, 42, 0.45)" }, formCard: { gap: theme.spacing.md, padding: theme.spacing.lg, borderRadius: theme.radius.lg, backgroundColor: theme.colors.surface }, input: { minHeight: 48, borderWidth: 1, borderColor: theme.colors.border, borderRadius: theme.radius.md, paddingHorizontal: theme.spacing.md, color: theme.colors.text }, options: { flexDirection: "row", flexWrap: "wrap", gap: theme.spacing.sm }, choice: { minHeight: 40, justifyContent: "center", paddingHorizontal: theme.spacing.md, borderRadius: theme.radius.pill, backgroundColor: theme.colors.background }, choiceSelected: { backgroundColor: theme.colors.primarySoft, borderWidth: 1, borderColor: theme.colors.primary }, rowSwitch: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, deleteButton: { minHeight: 44, alignItems: "center", justifyContent: "center", borderRadius: theme.radius.pill, borderWidth: 1, borderColor: theme.colors.error, paddingHorizontal: theme.spacing.md }, deleteText: { color: theme.colors.error, fontWeight: "800" }, schoolCard: { gap: theme.spacing.xs, padding: theme.spacing.md, borderRadius: theme.radius.lg, backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.border }, schoolDay: { color: theme.colors.textMuted, fontWeight: "700" }, schoolTitle: { fontWeight: "800", color: theme.colors.text }, schoolNote: { color: theme.colors.textMuted } });
