import { useEffect, useState } from "react";
import { router } from "expo-router";
import { Modal, Pressable, RefreshControl, StyleSheet, Switch, TextInput, View } from "react-native";
import { Screen } from "../../../components/Screen";
import { AppText } from "../../../components/AppText";
import { EmptyState, ErrorState } from "../../../components/States";
import { theme } from "../../../theme/tokens";
import { useHusk, type HuskView } from "../hooks/useHusk";
import { useReminderCompletion } from "../hooks/useReminderMutations";
import { emptyReminderState, type ReminderFilter } from "../reminderHistory";
import { HuskSection } from "./HuskSection";
import { ReminderList } from "./ReminderList";
import { ReminderSkeleton } from "./ReminderSkeleton";
import { HuskListCard } from "./HuskListCard";
import { HuskViewSwitcher } from "./HuskViewSwitcher";
import { selectHuskView } from "../viewState";
import { useSchoolWeekMutations } from "../hooks/useSchoolWeekMutations";
import { useTaskMutations } from "../hooks/useTaskMutations";
import { filterSchoolWeekByQuery, filterTasksByQuery } from "../search";
import type { SchoolWeekReminderViewModel } from "../models";
import type { TaskViewModel } from "../taskModel";

export function HuskShell() {
  const [filter, setFilter] = useState<ReminderFilter>("active");
  const [query, setQuery] = useState("");
  const [view, setView] = useState<HuskView>("reminders");
  const husk = useHusk(filter, view);
  const completion = useReminderCompletion();
  const schoolMutations = useSchoolWeekMutations(husk.weekStart);
  const [taskFormOpen, setTaskFormOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<TaskViewModel | null>(null);
  const taskMutations = useTaskMutations();
  const [schoolFormOpen, setSchoolFormOpen] = useState(false);
  const [editingSchoolItem, setEditingSchoolItem] = useState<SchoolWeekReminderViewModel | null>(null);
  const visibleReminders = husk.reminders.filter((reminder) => {
    const normalized = query.trim().toLocaleLowerCase("nb-NO");
    if (!normalized) return true;
    return [reminder.title, reminder.assigneeLabel, reminder.dateLabel, reminder.timeLabel].filter(Boolean).some((value) => value!.toLocaleLowerCase("nb-NO").includes(normalized));
  });
  const visibleTasks = filterTasksByQuery(husk.tasks, query);
  const visibleSchoolWeek = filterSchoolWeekByQuery(husk.schoolWeek, query);
  const empty = query.trim() ? { title: "Ingen treff", description: "Prøv et annet søk eller fjern filteret." } : emptyReminderState(filter);
  const action = filter === "active" ? "complete" : "undo";
  return <Screen bottomInset="tab" refreshControl={<RefreshControl refreshing={husk.refreshing} onRefresh={() => void husk.refresh()} tintColor={theme.colors.primary} />}>
    <View style={styles.header}><AppText variant="title">Husk</AppText><AppText style={styles.description}>Påminnelser og lister for familien.</AppText></View>
    <HuskViewSwitcher view={view} onChange={(nextView) => setView(selectHuskView({ view, reminderFilter: filter }, nextView).view)} />
    {view === "tasks" ? <Pressable accessibilityRole="button" accessibilityLabel="Legg til oppgave" onPress={() => { setEditingTask(null); setTaskFormOpen(true); }} style={styles.addButton}><AppText style={styles.addButtonText}>+ Ny oppgave</AppText></Pressable> : null}
    {view === "school-week" ? <Pressable accessibilityRole="button" accessibilityLabel="Legg til skolehusk" onPress={() => { setEditingSchoolItem(null); setSchoolFormOpen(true); }} style={styles.addButton}><AppText style={styles.addButtonText}>+ Ny skolehusk</AppText></Pressable> : null}
    {view !== "lists" ? <TextInput value={query} onChangeText={setQuery} placeholder={view === "tasks" ? "Søk i oppgaver" : view === "school-week" ? "Søk i skoleuka" : "Søk i påminnelser"} placeholderTextColor={theme.colors.placeholder} style={styles.input} accessibilityLabel={view === "tasks" ? "Søk i oppgaver" : view === "school-week" ? "Søk i skoleuka" : "Søk i påminnelser"} /> : null}
    {view === "reminders" ? <><View style={styles.filter} accessibilityRole="tablist" accessibilityLabel="Filter påminnelser"><FilterButton selected={filter === "active"} title="Aktive" onPress={() => setFilter("active")} /><FilterButton selected={filter === "history"} title="Historikk" onPress={() => setFilter("history")} /></View>
      {husk.loading ? <ReminderSkeleton /> : husk.missingContext ? <ErrorState title="Mangler familietilgang" description="Vi finner ikke en aktiv familie for Husk akkurat nå." onRetry={() => void husk.refresh()} /> : husk.error ? <ErrorState description="Kunne ikke hente Husk akkurat nå." onRetry={() => void husk.refresh()} /> : <HuskSection title={filter === "active" ? "Aktive" : "Historikk"}>{visibleReminders.length ? <ReminderList reminders={visibleReminders} action={action} actionBusy={completion.saving ? "pending" : null} onAction={(id) => void (action === "complete" ? completion.complete(id) : completion.undo(id))} /> : <EmptyState {...empty} />}{completion.error ? <AppText style={styles.error}>{completion.error}</AppText> : null}</HuskSection>}</> :
      view === "lists" ? husk.loading ? <ReminderSkeleton /> : husk.missingContext ? <ErrorState title="Mangler familietilgang" description="Vi finner ikke en aktiv familie for Husk akkurat nå." onRetry={() => void husk.refresh()} /> : husk.error ? <ErrorState description="Kunne ikke hente listene akkurat nå." onRetry={() => void husk.refresh()} /> : <HuskSection title="Aktive lister">{husk.lists.length ? husk.lists.map((list) => <HuskListCard key={list.id} list={list} onPress={() => router.push(`/(app)/husk/lists/${list.id}`)} />) : <EmptyState title="Ingen lister ennå" description="Det er ingen aktive lister for familien." />}</HuskSection> :
      view === "tasks" ? husk.loading ? <ReminderSkeleton /> : husk.missingContext ? <ErrorState title="Mangler familietilgang" description="Vi finner ikke en aktiv familie for oppgaver akkurat nå." onRetry={() => void husk.refresh()} /> : husk.error ? <ErrorState description="Kunne ikke hente oppgavene akkurat nå." onRetry={() => void husk.refresh()} /> : <HuskSection title="Oppgaver"><TaskList tasks={visibleTasks} hasQuery={Boolean(query.trim())} saving={taskMutations.saving} onToggle={(id) => void taskMutations.toggle(id)} onEdit={(task) => { setEditingTask(task); setTaskFormOpen(true); }} onDelete={(id) => void taskMutations.remove(id)} />{taskMutations.error ? <AppText style={styles.error}>{taskMutations.error}</AppText> : null}</HuskSection> :
      husk.loading ? <ReminderSkeleton /> : husk.missingContext ? <ErrorState title="Mangler familietilgang" description="Vi finner ikke en aktiv familie for Skoleuka akkurat nå." onRetry={() => void husk.refresh()} /> : husk.error ? <ErrorState description="Kunne ikke hente Skoleuka akkurat nå." onRetry={() => void husk.refresh()} /> : <HuskSection title="Skoleuka">{visibleSchoolWeek.length ? visibleSchoolWeek.map((item) => <Pressable key={item.id} onPress={() => { setEditingSchoolItem(item); setSchoolFormOpen(true); }} style={styles.schoolCard} accessible accessibilityRole="summary" accessibilityLabel={`${item.dayLabel}: ${item.title} for ${item.childLabel}`}><AppText style={styles.schoolDay}>{item.dayLabel} • {item.childLabel}</AppText><AppText style={styles.schoolTitle}>{item.title}</AppText>{item.note ? <AppText style={styles.schoolNote}>{item.note}</AppText> : null}</Pressable>) : <EmptyState title={query.trim() ? "Ingen treff" : "Ingen skolehusk denne uka"} description={query.trim() ? "Prøv et annet søk eller fjern filteret." : "Skoleuka er tom for valgt familie."} />}</HuskSection>}
    <TaskForm visible={taskFormOpen} task={editingTask} saving={taskMutations.saving} error={taskMutations.error} onClose={() => { setTaskFormOpen(false); taskMutations.resetError(); }} onSave={async (payload) => { if (editingTask) await taskMutations.update({ id: editingTask.id, input: payload }); else await taskMutations.create(payload); setTaskFormOpen(false); }} />
    <SchoolWeekForm visible={schoolFormOpen} item={editingSchoolItem} childMembers={husk.familyMembers.filter((member) => member.includeInSchoolWeek)} weekStart={husk.weekStart} saving={schoolMutations.saving} error={schoolMutations.error} onClose={() => { setSchoolFormOpen(false); schoolMutations.resetError(); }} onSave={async (payload) => { if (editingSchoolItem) await schoolMutations.update({ id: editingSchoolItem.id, payload: { ...payload, scope: editingSchoolItem.isRecurring ? "series" : undefined, occurrenceDate: editingSchoolItem.occurrenceDate ?? undefined } }); else await schoolMutations.create(payload); setSchoolFormOpen(false); }} onDelete={editingSchoolItem ? async () => { await schoolMutations.remove({ id: editingSchoolItem.id, scope: editingSchoolItem.isRecurring ? "series" : undefined, occurrenceDate: editingSchoolItem.occurrenceDate ?? undefined }); setSchoolFormOpen(false); } : undefined} />
  </Screen>;
}

function SchoolWeekForm({ visible, item, childMembers, weekStart, saving, error, onClose, onSave, onDelete }: { visible: boolean; item: SchoolWeekReminderViewModel | null; childMembers: { id: string; displayName: string }[]; weekStart: string; saving: boolean; error: string | null; onClose: () => void; onSave: (payload: { childFamilyMemberId: string; title: string; icon: string; weekday: "monday" | "tuesday" | "wednesday" | "thursday" | "friday"; date: string; isRecurring: boolean; recurrenceFrequency: "weekly"; recurrenceEndDate: string | null; note: string | null }) => Promise<void>; onDelete?: () => Promise<void> }) {
  const weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday"] as const;
  const labels = { monday: "Mandag", tuesday: "Tirsdag", wednesday: "Onsdag", thursday: "Torsdag", friday: "Fredag" };
  const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [childId, setChildId] = useState(""); const [weekday, setWeekday] = useState<typeof weekdays[number]>("monday"); const [recurring, setRecurring] = useState(false);
  useEffect(() => {
    if (!visible) return;
    setTitle(item?.title ?? "");
    setNote(item?.note ?? "");
    setChildId(item?.childFamilyMemberId ?? childMembers[0]?.id ?? "");
    setWeekday((item?.weekday ?? "monday") as typeof weekdays[number]);
    setRecurring(item?.isRecurring ?? false);
  }, [childMembers, item, visible]);
  const date = addDays(weekStart, weekdays.indexOf(weekday));
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalBackdrop}><View style={styles.formCard}><AppText variant="title">{item ? "Rediger skolehusk" : "Ny skolehusk"}</AppText><TextInput value={title} onChangeText={setTitle} placeholder="Tittel" placeholderTextColor={theme.colors.placeholder} style={styles.input} />
  <TextInput value={note} onChangeText={setNote} placeholder="Notat" placeholderTextColor={theme.colors.placeholder} style={styles.input} />
  <View style={styles.options}>{childMembers.map((child) => <Pressable key={child.id} onPress={() => setChildId(child.id)} style={[styles.choice, childId === child.id && styles.choiceSelected]}><AppText>{child.displayName}</AppText></Pressable>)}</View><View style={styles.options}>{weekdays.map((day) => <Pressable key={day} onPress={() => setWeekday(day)} style={[styles.choice, weekday === day && styles.choiceSelected]}><AppText>{labels[day]}</AppText></Pressable>)}</View><View style={styles.rowSwitch}><AppText>Gjenta ukentlig</AppText><Switch value={recurring} onValueChange={setRecurring} /></View>{error ? <AppText style={styles.error}>{error}</AppText> : null}<Pressable disabled={saving || !title.trim() || !childId} onPress={() => void onSave({ childFamilyMemberId: childId, title: title.trim(), icon: "backpack", weekday, date, isRecurring: recurring, recurrenceFrequency: "weekly", recurrenceEndDate: null, note: note.trim() || null })} style={styles.addButton}><AppText style={styles.addButtonText}>{saving ? "Lagrer …" : "Lagre"}</AppText></Pressable>{onDelete ? <Pressable disabled={saving} onPress={() => void onDelete()} style={styles.deleteButton}><AppText style={styles.deleteText}>Slett</AppText></Pressable> : null}<Pressable onPress={onClose} style={styles.choice}><AppText>Avbryt</AppText></Pressable></View></View></Modal>;
}
function addDays(date: string, days: number) { const value = new Date(`${date}T00:00:00.000Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); }

function FilterButton({ title, selected, onPress }: { title: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} accessibilityRole="tab" accessibilityState={{ selected }} accessibilityLabel={`Vis ${title.toLowerCase()} påminnelser`} accessibilityHint="Bytter hvilken type påminnelser som vises." style={[styles.filterButton, selected && styles.filterButtonSelected]}><AppText style={[styles.filterText, selected && styles.filterTextSelected]}>{title}</AppText></Pressable>; }
const styles = StyleSheet.create({ header: { gap: theme.spacing.xs }, description: { color: theme.colors.textMuted }, filter: { flexDirection: "row", gap: theme.spacing.sm }, filterButton: { minHeight: 44, justifyContent: "center", paddingHorizontal: theme.spacing.md, borderRadius: theme.radius.pill, backgroundColor: theme.colors.primarySoft }, filterButtonSelected: { backgroundColor: theme.colors.primaryStrong }, filterText: { color: theme.colors.primaryStrong, fontWeight: "800" }, filterTextSelected: { color: theme.colors.surface }, error: { color: theme.colors.error }, addButton: { minHeight: 44, alignItems: "center", justifyContent: "center", borderRadius: theme.radius.pill, backgroundColor: theme.colors.primaryStrong, paddingHorizontal: theme.spacing.md }, addButtonText: { color: theme.colors.surface, fontWeight: "800" }, modalBackdrop: { flex: 1, justifyContent: "center", padding: theme.spacing.lg, backgroundColor: "rgba(15, 23, 42, 0.45)" }, formCard: { gap: theme.spacing.md, padding: theme.spacing.lg, borderRadius: theme.radius.lg, backgroundColor: theme.colors.surface }, input: { minHeight: 48, borderWidth: 1, borderColor: theme.colors.border, borderRadius: theme.radius.md, paddingHorizontal: theme.spacing.md, color: theme.colors.text, backgroundColor: theme.colors.surface }, options: { flexDirection: "row", flexWrap: "wrap", gap: theme.spacing.sm }, choice: { minHeight: 40, justifyContent: "center", paddingHorizontal: theme.spacing.md, borderRadius: theme.radius.pill, backgroundColor: theme.colors.background }, choiceSelected: { backgroundColor: theme.colors.primarySoft, borderWidth: 1, borderColor: theme.colors.primary }, rowSwitch: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, deleteButton: { minHeight: 44, alignItems: "center", justifyContent: "center", borderRadius: theme.radius.pill, borderWidth: 1, borderColor: theme.colors.error, paddingHorizontal: theme.spacing.md }, deleteText: { color: theme.colors.error, fontWeight: "800" }, schoolCard: { gap: theme.spacing.xs, padding: theme.spacing.md, borderRadius: theme.radius.lg, backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.border }, schoolDay: { color: theme.colors.textMuted, fontWeight: "700" }, schoolTitle: { fontWeight: "800", color: theme.colors.text }, schoolNote: { color: theme.colors.textMuted }, taskGroups: { gap: theme.spacing.md }, taskCard: { flexDirection: "row", alignItems: "center", gap: theme.spacing.sm, padding: theme.spacing.md, borderRadius: theme.radius.lg, backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.border }, taskCompleted: { opacity: 0.72 }, taskToggle: { minHeight: 44, minWidth: 44, alignItems: "center", justifyContent: "center" }, taskBody: { flex: 1, gap: theme.spacing.xs }, taskTitle: { fontWeight: "800", color: theme.colors.text }, deleteSmall: { minHeight: 40, justifyContent: "center", paddingHorizontal: theme.spacing.sm } });

function TaskList({ tasks, hasQuery, saving, onToggle, onEdit, onDelete }: { tasks: TaskViewModel[]; hasQuery: boolean; saving: boolean; onToggle: (id: string) => void; onEdit: (task: TaskViewModel) => void; onDelete: (id: string) => void }) {
  if (!tasks.length) return <EmptyState title={hasQuery ? "Ingen oppgaver matcher søket" : "Ingen oppgaver i dag"} description={hasQuery ? "Prøv et annet søk eller fjern filteret." : "Legg til en oppgave når noe må gjøres."} />;
  const openTasks = tasks.filter((task) => !task.completed);
  const completedTasks = tasks.filter((task) => task.completed);
  return <View style={styles.taskGroups}><TaskGroup title="Gjenstående oppgaver" tasks={openTasks} saving={saving} onToggle={onToggle} onEdit={onEdit} onDelete={onDelete} /><TaskGroup title="Fullførte oppgaver" tasks={completedTasks} saving={saving} onToggle={onToggle} onEdit={onEdit} onDelete={onDelete} /></View>;
}
function TaskGroup({ title, tasks, saving, onToggle, onEdit, onDelete }: { title: string; tasks: TaskViewModel[]; saving: boolean; onToggle: (id: string) => void; onEdit: (task: TaskViewModel) => void; onDelete: (id: string) => void }) {
  if (!tasks.length) return null;
  return <View style={styles.taskGroups}><AppText variant="heading">{title} ({tasks.length})</AppText>{tasks.map((task) => <View key={task.id} style={[styles.taskCard, task.completed && styles.taskCompleted]}><Pressable disabled={saving} onPress={() => onToggle(task.id)} accessibilityRole="checkbox" accessibilityState={{ checked: task.completed, disabled: saving }} accessibilityLabel={`${task.completed ? "Marker som ikke ferdig" : "Fullfør"} ${task.title}`} style={styles.taskToggle}><AppText>{task.completed ? "☑" : "☐"}</AppText></Pressable><Pressable onPress={() => onEdit(task)} style={styles.taskBody} accessibilityRole="button" accessibilityLabel={`Vis oppgave ${task.title}`}><AppText style={styles.taskTitle}>{task.title}</AppText><AppText style={styles.schoolNote}>{task.assigneeLabel}{task.dueLabel ? ` · ${task.dueLabel}` : ""}</AppText>{task.description ? <AppText style={styles.schoolNote}>{task.description}</AppText> : null}</Pressable><Pressable disabled={saving} onPress={() => onDelete(task.id)} accessibilityRole="button" accessibilityLabel={`Slett ${task.title}`} style={styles.deleteSmall}><AppText style={styles.deleteText}>Slett</AppText></Pressable></View>)}</View>;
}
function TaskForm({ visible, task, saving, error, onClose, onSave }: { visible: boolean; task: TaskViewModel | null; saving: boolean; error: string | null; onClose: () => void; onSave: (payload: { title: string; description?: string | null; assignedMemberIds?: string[]; assignedFamilyMemberId?: string | null; dueDate?: string | null }) => Promise<void> }) {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [dueDate, setDueDate] = useState("");
  useEffect(() => { if (!visible) return; setTitle(task?.title ?? ""); setDescription(task?.description ?? ""); setDueDate(task?.dueDate?.slice(0, 10) ?? ""); }, [task, visible]);
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalBackdrop}><View style={styles.formCard}><AppText variant="title">{task ? "Rediger oppgave" : "Ny oppgave"}</AppText><TextInput value={title} onChangeText={setTitle} placeholder="Oppgave" placeholderTextColor={theme.colors.placeholder} style={styles.input} maxLength={120} /><TextInput value={description} onChangeText={setDescription} placeholder="Notat" placeholderTextColor={theme.colors.placeholder} style={styles.input} maxLength={500} multiline /><TextInput value={dueDate} onChangeText={setDueDate} placeholder="Frist (YYYY-MM-DD)" placeholderTextColor={theme.colors.placeholder} style={styles.input} />{error ? <AppText style={styles.error}>{error}</AppText> : null}<Pressable disabled={saving || !title.trim()} onPress={() => void onSave({ title: title.trim(), description: description.trim() || null, dueDate: dueDate.trim() || null })} style={styles.addButton}><AppText style={styles.addButtonText}>{saving ? "Lagrer …" : "Lagre"}</AppText></Pressable><Pressable onPress={onClose} style={styles.choice}><AppText>Avbryt</AppText></Pressable></View></View></Modal>;
}
