import { Ionicons } from "@expo/vector-icons";
import type React from "react";
import { Pressable, StyleSheet, View } from "react-native";
import { router } from "expo-router";
import { AppText } from "../../../components/AppText";
import { theme } from "../../../theme/tokens";
import type { ReminderViewModel } from "../models";
const icons: Record<string, React.ComponentProps<typeof Ionicons>["name"]> = { backpack: "bag-handle-outline", book: "book-outline", cake: "gift-outline", car: "car-outline", gift: "gift-outline", grill: "restaurant-outline", passport: "briefcase-outline", shirt: "shirt-outline", summer: "sunny-outline", tooth: "medical-outline" };
export function ReminderCard({ reminder, action, onAction, actionBusy = false }: { reminder: ReminderViewModel; action?: "complete" | "undo"; onAction?: () => void; actionBusy?: boolean }) { const meta = [reminder.dateLabel, reminder.timeLabel, reminder.assigneeLabel].filter(Boolean).join(" • "); const actionTitle = action === "complete" ? "Fullfør" : "Angre"; return <Pressable onPress={() => router.push(`/(app)/husk/${reminder.id}`)} accessible accessibilityRole="button" accessibilityLabel={`${reminder.title}. ${meta}. Status: ${reminder.statusLabel}.`} accessibilityHint="Åpner detaljene for påminnelsen." style={styles.card}><View style={styles.icon}><Ionicons name={icons[reminder.icon] ?? "notifications-outline"} size={23} color={theme.colors.primaryStrong} /></View><View style={styles.copy}><AppText variant="lead" style={styles.title}>{reminder.title}</AppText><AppText style={styles.meta}>{meta}</AppText></View>{onAction && action ? <Pressable onPress={(event) => { event.stopPropagation(); onAction(); }} disabled={actionBusy} accessibilityRole="button" accessibilityLabel={`${actionTitle} ${reminder.title}`} accessibilityHint={action === "complete" ? "Flytter påminnelsen til historikk." : "Flytter påminnelsen tilbake til aktive påminnelser."} style={styles.action}><AppText variant="small" style={styles.actionText}>{actionBusy ? "Lagrer…" : actionTitle}</AppText></Pressable> : null}</Pressable>; }
const styles = StyleSheet.create({ card: { minHeight: 88, flexDirection: "row", alignItems: "center", gap: theme.spacing.sm, padding: theme.spacing.md, borderWidth: 1, borderColor: theme.colors.border, borderRadius: theme.radius.lg, backgroundColor: theme.colors.surface, ...theme.shadow.card }, icon: { width: 44, height: 44, borderRadius: 22, justifyContent: "center", alignItems: "center", backgroundColor: theme.colors.primarySoft }, copy: { flex: 1, gap: 2 }, title: { fontWeight: "800" }, meta: { color: theme.colors.textMuted }, action: { minHeight: 44, justifyContent: "center", paddingHorizontal: theme.spacing.sm, borderRadius: theme.radius.md, backgroundColor: theme.colors.primarySoft }, actionText: { color: theme.colors.primaryStrong, fontWeight: "800" } });
