import { Ionicons } from "@expo/vector-icons";
import type React from "react";
import { Pressable, StyleSheet, View } from "react-native";
import { AppText } from "../../../components/AppText";
import { theme } from "../../../theme/tokens";
import type { ReminderViewModel } from "../models";
const icons: Record<string, React.ComponentProps<typeof Ionicons>["name"]> = { backpack: "bag-handle-outline", book: "book-outline", cake: "gift-outline", car: "car-outline", gift: "gift-outline", grill: "restaurant-outline", passport: "briefcase-outline", shirt: "shirt-outline", summer: "sunny-outline", tooth: "medical-outline" };
export function ReminderCard({ reminder }: { reminder: ReminderViewModel }) { const meta = [reminder.dateLabel, reminder.timeLabel, reminder.assigneeLabel].filter(Boolean).join(" • "); return <Pressable accessibilityRole="button" accessibilityLabel={`${reminder.title}. ${meta}. Status: ${reminder.statusLabel}.`} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.icon}><Ionicons name={icons[reminder.icon] ?? "notifications-outline"} size={23} color={theme.colors.primaryStrong} /></View><View style={styles.copy}><AppText variant="lead" style={styles.title}>{reminder.title}</AppText><AppText style={styles.meta}>{meta}</AppText></View><View style={[styles.status, reminder.status === "overdue" && styles.overdue]}><AppText variant="small" style={styles.statusText}>{reminder.statusLabel}</AppText></View></Pressable>; }
const styles = StyleSheet.create({ card: { minHeight: 88, flexDirection: "row", alignItems: "center", gap: theme.spacing.sm, padding: theme.spacing.md, borderWidth: 1, borderColor: theme.colors.border, borderRadius: theme.radius.lg, backgroundColor: theme.colors.surface, ...theme.shadow.card }, icon: { width: 44, height: 44, borderRadius: 22, justifyContent: "center", alignItems: "center", backgroundColor: theme.colors.primarySoft }, copy: { flex: 1, gap: 2 }, title: { fontWeight: "800" }, meta: { color: theme.colors.textMuted }, status: { borderRadius: theme.radius.pill, paddingHorizontal: theme.spacing.sm, paddingVertical: 4, backgroundColor: theme.colors.successSoft }, overdue: { backgroundColor: theme.colors.errorSoft }, statusText: { fontWeight: "800", color: theme.colors.primaryStrong }, pressed: { opacity: .86 } });
