import { formatReminderDate, getReminderStatus, mapHuskListToViewModel, mapReminderToViewModel, sortReminders } from "./models";
const assert = { equal(actual: unknown, expected: unknown) { if (actual !== expected) throw new Error(`Expected ${String(expected)}, received ${String(actual)}`); }, deepEqual(actual: unknown, expected: unknown) { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error("Values are not equal"); } };
const base = { id: "r", familyId: "f", title: "Påminnelse", icon: "book", dueDate: "2026-07-17T14:30:00.000Z", date: "2026-07-17", reminderMinutesBefore: null, reminder: null, note: null, scope: "family" as const, memberIds: [], sourceType: null, sourceId: null, isPrivate: false, createdByUserId: null, createdAt: "", updatedAt: "", archivedAt: null, audienceMembers: [] };
assert.equal(getReminderStatus("2026-07-16", "2026-07-17"), "overdue");
assert.equal(getReminderStatus("2026-07-17", "2026-07-17"), "today");
assert.equal(formatReminderDate("2026-07-18", "2026-07-17"), "I morgen");
assert.equal(mapReminderToViewModel(base, "2026-07-17").statusLabel, "I dag");
assert.deepEqual(sortReminders([{ id: "later", title: "Z", status: "upcoming", date: "2026-07-19" }, { id: "today", title: "A", status: "today", date: "2026-07-17" }] as any).map((item) => item.id), ["today", "later"]);
assert.deepEqual(mapHuskListToViewModel({ id: "l", title: "Pakking", icon: "home", completedCount: 2, totalCount: 4, items: [] } as any), { id: "l", title: "Pakking", icon: "home", completedCount: 2, totalCount: 4, progressPercent: 50, progressLabel: "2 av 4 fullført" });
console.log("Husk view model tests passed");
