import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
const component = readFileSync("components/AdvertisementCard.tsx", "utf8");
const css = readFileSync("app/globals.css", "utf8");
const dashboard = readFileSync("app/dashboard/page.tsx", "utf8");
const menu = readFileSync("app/menu/page.tsx", "utf8");
const calendar = readFileSync("app/calendar/page.tsx", "utf8");
const wishlist = readFileSync("app/wishlist/page.tsx", "utf8");
const shopping = readFileSync("app/shopping/ShoppingPageClient.tsx", "utf8");
const api = readFileSync("lib/api.ts", "utf8");
assert(component.includes('IntersectionObserver'));
assert(component.includes('threshold: [0.5]'));
assert(component.includes('impressed.current = true'));
assert(component.includes('recordAdvertisementClick'));
assert(component.includes('void recordAdvertisementClick(advertisement.id, advertisement.placement).catch(() => undefined)'));
assert(!component.includes('window.open("about:blank"'));
assert(!component.includes('opened.location.href'));
assert(!component.includes('event.preventDefault()'));
assert(component.includes('loading="lazy"') || component.includes('loading=\"lazy\"'));
assert(component.includes('aria-label={`Annonse: ${advertisement.altText}`}'));
assert(component.includes('Annonse</span>'));
assert(component.includes('images.desktop ?? images.tablet ?? images.mobile'));
assert(component.includes('images.tablet ?? images.mobile'));
assert(component.includes('onError={() => setHidden(true)}'));
assert(component.includes('target="_blank"'));
assert(component.includes('rel="noopener noreferrer sponsored"'));
assert(css.includes('.advertisement-card__image') && css.includes('max-width: 100%'));
assert(dashboard.includes('<AdvertisementPlacementCard placement="HOME" />'));
assert(menu.includes('<AdvertisementPlacementCard placement="MENU" />'));
assert(calendar.includes('<AdvertisementPlacementCard placement="CALENDAR" />'));
assert(wishlist.includes('<AdvertisementPlacementCard placement="WISHLIST" />'));
assert(shopping.includes('<AdvertisementPlacementCard placement="SHOPPING" />'));
assert(api.includes('getAdvertisements') && api.includes('recordAdvertisementImpression'));
console.log("advertisement card source tests passed");
