import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
const component = readFileSync("components/AdvertisementCard.tsx", "utf8");
const dashboard = readFileSync("app/dashboard/page.tsx", "utf8");
const menu = readFileSync("app/menu/page.tsx", "utf8");
const calendar = readFileSync("app/calendar/page.tsx", "utf8");
const wishlist = readFileSync("app/wishlist/page.tsx", "utf8");
const shopping = readFileSync("app/shopping/ShoppingPageClient.tsx", "utf8");
const api = readFileSync("lib/api.ts", "utf8");
assert(component.includes('IntersectionObserver'));
assert(component.includes('threshold: [0.5]'));
assert(component.includes('impressed.current = true'));
assert(component.includes('recordAdvertisementClick'));
assert(component.includes('loading="lazy"') || component.includes('loading=\"lazy\"'));
assert(component.includes('aria-label={`Annonse: ${advertisement.altText}`}'));
assert(component.includes('Annonse</span>'));
assert(component.includes('images.desktop ?? images.tablet ?? images.mobile'));
assert(component.includes('images.tablet ?? images.mobile'));
assert(component.includes('onError={() => setHidden(true)}'));
assert(component.includes('target="_blank"'));
assert(dashboard.includes('<AdvertisementPlacementCard placement="HOME" />'));
assert(menu.includes('<AdvertisementPlacementCard placement="MENU" />'));
assert(calendar.includes('<AdvertisementPlacementCard placement="CALENDAR" />'));
assert(wishlist.includes('<AdvertisementPlacementCard placement="WISHLIST" />'));
assert(shopping.includes('<AdvertisementPlacementCard placement="SHOPPING" />'));
assert(api.includes('getAdvertisements') && api.includes('recordAdvertisementImpression'));
console.log("advertisement card source tests passed");
