export enum AdminAuditAction {
  ADMIN_LOGIN = "ADMIN_LOGIN",
  ADMIN_LOGOUT = "ADMIN_LOGOUT",
  USER_VIEWED = "USER_VIEWED",
  USER_DISABLED = "USER_DISABLED",
  USER_ENABLED = "USER_ENABLED",
  ADVERTISEMENT_CREATED = "ADVERTISEMENT_CREATED",
  ADVERTISEMENT_UPDATED = "ADVERTISEMENT_UPDATED",
  ADVERTISEMENT_PUBLISHED = "ADVERTISEMENT_PUBLISHED",
  ADVERTISEMENT_PAUSED = "ADVERTISEMENT_PAUSED",
  ADMIN_CREATED = "ADMIN_CREATED",
  ADMIN_UPDATED = "ADMIN_UPDATED",
  ADMIN_DISABLED = "ADMIN_DISABLED",
  FAMILY_INVITE_CODE_VIEWED = "FAMILY_INVITE_CODE_VIEWED",
  USER_MOVED_TO_FAMILY = "USER_MOVED_TO_FAMILY",
  FAMILY_CREATED_BY_ADMIN = "FAMILY_CREATED_BY_ADMIN"
}
