import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { AuthService } from "../auth";
import { PrismaService } from "../prisma";
import { AdminAuditAction } from "./admin-audit-actions";
import { AdminRequestUser } from "./admin-auth.service";
import { AdminRoleDto } from "./dto/admin-auth.dto";
import { AdvertisementMutationDto, AdvertisementStatusDto, AuditLogQueryDto, CreateAdminUserDto, PageQueryDto, UpdateAdminUserDto, UpdateUserStatusDto, MoveUserFamilyDto, CreateUserFamilyDto } from "./dto/admin-api.dto";

type Meta = { ipAddress?: string | null; userAgent?: string | null };
const AD_STATUSES = ["DRAFT", "SCHEDULED", "ACTIVE", "PAUSED", "ENDED"];
const AD_PLACEMENTS = ["HOME", "CALENDAR", "MENU"];
const ADMIN_ROLES = ["SUPER_ADMIN", "SUPPORT", "ANALYST", "AD_MANAGER"];

@Injectable()
export class AdminApiService {
  constructor(private readonly prisma: PrismaService, private readonly auth: AuthService) {}
  private get db(): any { return this.prisma.client as any; }

  async dashboard() { const now = new Date(); const d7 = new Date(now.getTime() - 7*864e5); const d30 = new Date(now.getTime() - 30*864e5); const [totalUsers,totalFamilies,new7,new30,activeImports,activeAds] = await Promise.all([this.db.user.count(),this.db.family.count(),this.db.user.count({where:{createdAt:{gte:d7}}}),this.db.user.count({where:{createdAt:{gte:d30}}}),this.db.calendarIcsSource.count({where:{active:true}}),this.db.advertisement.count({where:{status:"ACTIVE"}})]); return { totalUsers,totalFamilies,newUsersLast7Days:new7,newUsersLast30Days:new30,activeCalendarImports:activeImports,activeAdvertisements:activeAds }; }

  async users(q: PageQueryDto) { const {page,pageSize,skip,take}=this.page(q,25,100); const where:any={}; const s=this.str(q.search); if(s) where.OR=[{name:{contains:s,mode:"insensitive"}},{email:{contains:s,mode:"insensitive"}}]; if(q.status!==undefined){ const st=this.enumVal(q.status,["active","inactive"],"status"); where.deactivatedAt=st==="active"?null:{not:null}; } const orderBy={createdAt:this.enumVal(q.sort,["asc","desc"],"sort",true)??"desc"}; const [total,items]=await Promise.all([this.db.user.count({where}),this.db.user.findMany({where,orderBy,skip,take,select:{id:true,name:true,email:true,createdAt:true,updatedAt:true,deactivatedAt:true,memberships:{select:{family:{select:{id:true,name:true,_count:{select:{members:true}}}},updatedAt:true},take:1,orderBy:{updatedAt:"desc"}}}})]); return {page,pageSize,total,items:items.map((u:any)=>({id:u.id,name:u.name,email:u.email,createdAt:u.createdAt.toISOString(),active:!u.deactivatedAt,familyName:u.memberships[0]?.family?.name??null,familyMemberCount:u.memberships[0]?.family?._count?.members??0,lastRelevantActivity:u.updatedAt?.toISOString?.()??null}))}; }

  async user(id:string){ const u=await this.db.user.findUnique({where:{id},select:{id:true,name:true,email:true,createdAt:true,updatedAt:true,deactivatedAt:true,memberships:{select:{family:{select:{id:true,name:true,_count:{select:{members:true}}}},role:true,displayName:true}}}}); if(!u) throw new NotFoundException("User not found"); return {id:u.id,name:u.name,email:u.email,createdAt:u.createdAt.toISOString(),updatedAt:u.updatedAt.toISOString(),active:!u.deactivatedAt,memberships:u.memberships.map((m:any)=>({familyId:m.family.id,familyName:m.family.name,role:m.role,displayName:m.displayName,familyMemberCount:m.family._count.members}))}; }


  async families(q: PageQueryDto){ const {page,pageSize,skip,take}=this.page(q,10,50); const where:any={}; const search=this.str(q.search); if(search) where.name={contains:search,mode:"insensitive"}; const code=this.str(q.inviteCode); if(code) where.code=this.normalizeFamilyCode(code); const [total,items]=await Promise.all([this.db.family.count({where}),this.db.family.findMany({where,skip,take,orderBy:{createdAt:"desc"},select:{id:true,name:true,code:true,createdAt:true,_count:{select:{members:true}},members:{where:{role:"OWNER"},select:{displayName:true,user:{select:{email:true,name:true}}},take:1}}})]); return {page,pageSize,total,items:items.map((f:any)=>({id:f.id,name:f.name,memberCount:f._count.members,createdAt:f.createdAt.toISOString(),ownerSummary:f.members[0]?.displayName||f.members[0]?.user?.name||f.members[0]?.user?.email||null}))}; }

  async familyInviteCode(userId:string,familyId:string,admin:AdminRequestUser,meta:Meta){ const [user,family]=await Promise.all([this.db.user.findUnique({where:{id:userId},select:{id:true}}),this.db.family.findUnique({where:{id:familyId},select:{id:true,name:true,code:true}})]); if(!user) throw new NotFoundException("User not found"); if(!family) throw new NotFoundException("Family not found"); if(!family.code) throw new NotFoundException("Family invite code was not found"); await this.audit(admin.id,AdminAuditAction.FAMILY_INVITE_CODE_VIEWED,"Family",familyId,meta,{userId}); return {familyId:family.id,familyName:family.name,inviteCode:family.code}; }

  async moveUserFamily(userId:string,b:MoveUserFamilyDto,admin:AdminRequestUser,meta:Meta){ const fromFamilyId=this.reqStr(b.fromFamilyId,"current family"); const targetFamilyId=this.reqStr(b.targetFamilyId,"target family"); const role=this.enumVal(b.role,["PARENT","CHILD","GUEST"],"role") as string; const reason=this.reason(b.reason); if(fromFamilyId===targetFamilyId) throw new BadRequestException("The target family must be different from the current family"); return this.db.$transaction(async(tx:any)=>{ const user=await tx.user.findUnique({where:{id:userId},select:{id:true,name:true,email:true,deactivatedAt:true}}); if(!user) throw new NotFoundException("User not found"); if(user.deactivatedAt) throw new BadRequestException("Inactive users cannot be moved"); const current=await tx.familyMember.findFirst({where:{userId,familyId:fromFamilyId},include:{family:true}}); if(!current) throw new NotFoundException("Current family membership was not found"); const target=await tx.family.findUnique({where:{id:targetFamilyId},select:{id:true,name:true,_count:{select:{members:true}}}}); if(!target) throw new NotFoundException("Target family not found"); const conflict=await tx.familyMember.findFirst({where:{userId,familyId:targetFamilyId},select:{id:true}}); if(conflict) throw new BadRequestException("User already belongs to the target family"); if(current.role==="OWNER"){ const owners=await tx.familyMember.count({where:{familyId:fromFamilyId,role:"OWNER",userId:{not:null}}}); if(owners<=1) throw new BadRequestException("This user is the only owner of the current family and cannot be moved until ownership is resolved."); }
      await tx.familyMember.delete({where:{id:current.id}}); await tx.familyMember.create({data:{userId,familyId:targetFamilyId,displayName:current.displayName||user.name||user.email||"Family member",role}}); await tx.adminAuditLog.create({data:{adminUserId:admin.id,action:AdminAuditAction.USER_FAMILY_MOVED,targetType:"User",targetId:userId,metadata:{fromFamilyId,targetFamilyId,role,reason},ipAddress:meta.ipAddress??null}}); return this.user(userId); }); }

  async createUserFamily(userId:string,b:CreateUserFamilyDto,admin:AdminRequestUser,meta:Meta){ const name=this.familyName(b.name); const reason=this.reason(b.reason); return this.db.$transaction(async(tx:any)=>{ const user=await tx.user.findUnique({where:{id:userId},select:{id:true,name:true,email:true,deactivatedAt:true,memberships:{select:{id:true},take:1}}}); if(!user) throw new NotFoundException("User not found"); if(user.deactivatedAt) throw new BadRequestException("Inactive users cannot create a family"); if(user.memberships.length) throw new BadRequestException("This user already belongs to a family. Move the user to another family instead."); const family=await this.createAdminFamilyWithCode(tx,{name},{members:{select:{id:true}}}); await tx.familyMember.create({data:{userId,familyId:family.id,displayName:user.name||user.email||"Family owner",role:"OWNER"}}); await tx.adminAuditLog.create({data:{adminUserId:admin.id,action:AdminAuditAction.USER_FAMILY_CREATED,targetType:"User",targetId:userId,metadata:{familyId:family.id,reason},ipAddress:meta.ipAddress??null}}); return this.user(userId); }); }

  async setUserStatus(id:string, body:UpdateUserStatusDto, admin:AdminRequestUser, meta:Meta){ const active=this.bool(body.active,"active"); return this.db.$transaction(async(tx:any)=>{ const before=await tx.user.findUnique({where:{id},select:{id:true,deactivatedAt:true}}); if(!before) throw new NotFoundException("User not found"); const user=await tx.user.update({where:{id},data:{deactivatedAt:active?null:new Date()},select:{id:true,name:true,email:true,deactivatedAt:true,updatedAt:true}}); await tx.adminAuditLog.create({data:{adminUserId:admin.id,action:active?AdminAuditAction.USER_ENABLED:AdminAuditAction.USER_DISABLED,targetType:"User",targetId:id,metadata:{previousActive:!before.deactivatedAt,newActive:active},ipAddress:meta.ipAddress??null}}); return {id:user.id,name:user.name,email:user.email,active:!user.deactivatedAt,updatedAt:user.updatedAt.toISOString()}; }); }

  async statistics(){ const d30=new Date(Date.now()-30*864e5); const [totalUsers,totalFamilies,regs,events,tasks,reminders,activeImports,ads]=await Promise.all([this.db.user.count(),this.db.family.count(),this.db.user.findMany({where:{createdAt:{gte:d30}},select:{createdAt:true},orderBy:{createdAt:"asc"}}),this.db.calendarEvent.count({where:{createdAt:{gte:d30}}}),this.db.task.count({where:{createdAt:{gte:d30}}}),this.db.reminder.count({where:{createdAt:{gte:d30}}}),this.db.calendarIcsSource.count({where:{active:true}}),this.db.advertisement.groupBy({by:["status"],_count:{_all:true}})]); const byDay:any={}; for(let i=29;i>=0;i--){const d=new Date(Date.now()-i*864e5).toISOString().slice(0,10);byDay[d]=0;} regs.forEach((r:any)=>{const d=r.createdAt.toISOString().slice(0,10); if(d in byDay) byDay[d]++;}); return {totalUsers,totalFamilies,registrationsPerDay:Object.entries(byDay).map(([date,count])=>({date,count})),calendarEventsCreatedLast30Days:events,tasksCreatedLast30Days:tasks,remindersCreatedLast30Days:reminders,activeCalendarImports:activeImports,advertisementsByStatus:ads.map((a:any)=>({status:a.status,count:a._count._all}))}; }

  async advertisements(q:PageQueryDto){ const {page,pageSize,skip,take}=this.page(q,25,100); const where:any={}; if(q.status!==undefined) where.status=this.enumVal(q.status,AD_STATUSES,"status"); const [total,items]=await Promise.all([this.db.advertisement.count({where}),this.db.advertisement.findMany({where,skip,take,orderBy:{createdAt:"desc"},include:{createdBy:{select:{id:true,name:true,email:true}}}})]); return {page,pageSize,total,items:items.map(this.ad)}; }
  async advertisement(id:string){ const a=await this.db.advertisement.findUnique({where:{id},include:{createdBy:{select:{id:true,name:true,email:true}}}}); if(!a) throw new NotFoundException("Advertisement not found"); return this.ad(a); }
  async createAdvertisement(b:AdvertisementMutationDto, admin:AdminRequestUser, meta:Meta){ const data=this.adInput(b,true); const a=await this.db.advertisement.create({data:{...data,createdById:admin.id},include:{createdBy:{select:{id:true,name:true,email:true}}}}); await this.audit(admin.id,AdminAuditAction.ADVERTISEMENT_CREATED,"Advertisement",a.id,meta,{status:a.status}); return this.ad(a); }
  async updateAdvertisement(id:string,b:AdvertisementMutationDto,admin:AdminRequestUser,meta:Meta){ const data=this.adInput(b,false); const a=await this.db.advertisement.update({where:{id},data,include:{createdBy:{select:{id:true,name:true,email:true}}}}).catch(()=>{throw new NotFoundException("Advertisement not found")}); await this.audit(admin.id,data.status==="PAUSED"?AdminAuditAction.ADVERTISEMENT_PAUSED:(data.status==="ACTIVE"?AdminAuditAction.ADVERTISEMENT_PUBLISHED:AdminAuditAction.ADVERTISEMENT_UPDATED),"Advertisement",id,meta,{changes:Object.keys(data)}); return this.ad(a); }
  async deleteAdvertisement(id:string,admin:AdminRequestUser,meta:Meta){ const existing=await this.db.advertisement.findUnique({where:{id},select:{id:true,status:true,events:{select:{id:true},take:1}}}); if(!existing) throw new NotFoundException("Advertisement not found"); if(existing.status==="ACTIVE"||existing.status==="ENDED"||existing.events.length) await this.db.advertisement.update({where:{id},data:{status:"ENDED"}}); else await this.db.advertisement.delete({where:{id}}); await this.audit(admin.id,AdminAuditAction.ADVERTISEMENT_UPDATED,"Advertisement",id,meta,{deleted:true,softDeleted:existing.status==="ACTIVE"||existing.status==="ENDED"||existing.events.length}); return {id,deleted:true}; }

  async adminUsers(){ return (await this.db.adminUser.findMany({orderBy:{createdAt:"desc"},select:{id:true,email:true,name:true,role:true,active:true,lastLoginAt:true,createdAt:true,updatedAt:true}})).map(this.admin); }
  async createAdmin(b:CreateAdminUserDto,admin:AdminRequestUser,meta:Meta){ const email=this.email(b.email); const password=this.password(b.password); const role=this.enumVal(b.role,ADMIN_ROLES,"role") as AdminRoleDto; const u=await this.db.adminUser.create({data:{email,passwordHash:await this.auth.hashPassword(password),name:this.reqStr(b.name,"name"),role,active:b.active===undefined?true:this.bool(b.active,"active")},select:{id:true,email:true,name:true,role:true,active:true,lastLoginAt:true,createdAt:true,updatedAt:true}}); await this.audit(admin.id,AdminAuditAction.ADMIN_CREATED,"AdminUser",u.id,meta,{role}); return this.admin(u); }
  async updateAdmin(id:string,b:UpdateAdminUserDto,admin:AdminRequestUser,meta:Meta){ return this.db.$transaction(async(tx:any)=>{ const current=await tx.adminUser.findUnique({where:{id}}); if(!current) throw new NotFoundException("Admin user not found"); const data:any={}; if(b.name!==undefined)data.name=this.reqStr(b.name,"name"); if(b.role!==undefined)data.role=this.enumVal(b.role,ADMIN_ROLES,"role"); if(b.active!==undefined)data.active=this.bool(b.active,"active"); if(current.role==="SUPER_ADMIN"&&current.active&&((data.role&&data.role!=="SUPER_ADMIN")||data.active===false)) await this.ensureAnotherSuper(tx,id); const u=await tx.adminUser.update({where:{id},data,select:{id:true,email:true,name:true,role:true,active:true,lastLoginAt:true,createdAt:true,updatedAt:true}}); await tx.adminAuditLog.create({data:{adminUserId:admin.id,action:data.active===false?AdminAuditAction.ADMIN_DISABLED:AdminAuditAction.ADMIN_UPDATED,targetType:"AdminUser",targetId:id,metadata:{changes:Object.keys(data)},ipAddress:meta.ipAddress??null}}); return this.admin(u); }); }
  async auditLog(q:AuditLogQueryDto, admin:AdminRequestUser){ if(admin.role!=="SUPER_ADMIN") throw new ForbiddenException("Only SUPER_ADMIN can access audit logs"); const {page,pageSize,skip,take}=this.page(q,50,100); const where:any={}; if(q.adminId) where.adminUserId=this.reqStr(q.adminId,"adminId"); if(q.action) where.action=this.reqStr(q.action,"action"); if(q.from||q.to) where.createdAt={...(q.from?{gte:this.date(q.from,"from")}:{}),...(q.to?{lte:this.date(q.to,"to")}: {})}; const [total,items]=await Promise.all([this.db.adminAuditLog.count({where}),this.db.adminAuditLog.findMany({where,skip,take,orderBy:{createdAt:"desc"},include:{adminUser:{select:{id:true,email:true,name:true,role:true}}}})]); return {page,pageSize,total,items:items.map((l:any)=>({id:l.id,adminUser:l.adminUser,action:l.action,targetType:l.targetType,targetId:l.targetId,metadata:this.safeMetadata(l.metadata),ipAddress:l.ipAddress,createdAt:l.createdAt.toISOString()}))}; }


  private reason(v:unknown){ const s=this.reqStr(v,"reason"); if(s.length>500) throw new BadRequestException("reason must be 500 characters or fewer"); return s; }
  private familyName(v:unknown){ const s=this.reqStr(v,"family name"); if(s.length<2) throw new BadRequestException("family name must be at least 2 characters"); if(s.length>80) throw new BadRequestException("family name must be 80 characters or fewer"); return s; }
  private normalizeFamilyCode(value: unknown): string { const raw=this.reqStr(value,"inviteCode"); const compact=raw.toUpperCase().replace(/[\s-]+/g,""); const normalized=compact.startsWith("FA")?compact:`FA${compact}`; if(!/^FA[A-Z0-9]{6}$/.test(normalized)) throw new NotFoundException("Family code was not found"); return `FA-${normalized.slice(2)}`; }
  private async createAdminFamilyWithCode(tx:any,data:any,include:any){ for(let i=0;i<10;i++){ const code=`FA-${Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join("")}`; if(await tx.family.findUnique({where:{code}})) continue; try{return await tx.family.create({data:{...data,code},include});}catch{continue;} } throw new BadRequestException("Could not generate a unique family code"); }

  private safeMetadata(value:any): any { if (Array.isArray(value)) return value.map((v)=>this.safeMetadata(v)); if (value && typeof value === "object") { const out:any = {}; for (const [key, nested] of Object.entries(value)) { if (/password|passwordHash|token|session|secret|privateUrl|invitationToken/i.test(key)) out[key] = "[redacted]"; else out[key] = this.safeMetadata(nested); } return out; } return value; }

  private async ensureAnotherSuper(tx:any,id:string){ const c=await tx.adminUser.count({where:{id:{not:id},role:"SUPER_ADMIN",active:true}}); if(c<1) throw new BadRequestException("Cannot remove the last active SUPER_ADMIN"); }
  private async audit(adminUserId:string,action:string,targetType:string,targetId:string,meta:Meta,metadata:any){ await this.db.adminAuditLog.create({data:{adminUserId,action,targetType,targetId,metadata,ipAddress:meta.ipAddress??null}}); }
  private page(q:PageQueryDto,def:number,max:number){ const page=Math.max(1, Number(q.page??1)||1); const pageSize=Math.min(max,Math.max(1,Number(q.pageSize??def)||def)); return {page,pageSize,skip:(page-1)*pageSize,take:pageSize}; }
  private str(v:unknown){ return typeof v==="string"&&v.trim()?v.trim():null; } private reqStr(v:unknown,n:string){ const s=this.str(v); if(!s) throw new BadRequestException(`${n} is required`); return s; } private bool(v:unknown,n:string){ if(typeof v!=="boolean") throw new BadRequestException(`${n} must be boolean`); return v; } private enumVal(v:unknown,vals:string[],n:string,optional=false){ if(optional&&v===undefined)return undefined; if(typeof v!=="string"||!vals.includes(v)) throw new BadRequestException(`${n} is invalid`); return v; } private email(v:unknown){ const e=this.reqStr(v,"email").toLowerCase(); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)) throw new BadRequestException("email is invalid"); return e; } private password(v:unknown){ if(typeof v!=="string"||v.length<8) throw new BadRequestException("password must be at least 8 characters"); return v; } private date(v:unknown,n:string){ const d=new Date(this.reqStr(v,n)); if(Number.isNaN(d.getTime())) throw new BadRequestException(`${n} is invalid`); return d; }
  private adInput(b:AdvertisementMutationDto,create:boolean){ const data:any={}; if(create||b.title!==undefined)data.title=this.reqStr(b.title,"title"); if(create||b.body!==undefined)data.body=this.reqStr(b.body,"body"); if(create||b.placement!==undefined)data.placement=this.enumVal(b.placement,AD_PLACEMENTS,"placement"); if(b.status!==undefined)data.status=this.enumVal(b.status,AD_STATUSES,"status"); if(b.imageUrl!==undefined)data.imageUrl=b.imageUrl===null?null:this.url(b.imageUrl,"imageUrl"); if(b.targetUrl!==undefined)data.targetUrl=b.targetUrl===null?null:this.url(b.targetUrl,"targetUrl"); if(b.startsAt!==undefined)data.startsAt=b.startsAt===null?null:this.date(b.startsAt,"startsAt"); if(b.endsAt!==undefined)data.endsAt=b.endsAt===null?null:this.date(b.endsAt,"endsAt"); const start=data.startsAt, end=data.endsAt; if(start&&end&&end<start) throw new BadRequestException("endsAt cannot be before startsAt"); return data; }
  private url(v:unknown,n:string){ const s=this.reqStr(v,n); try{ const u=new URL(s); if(!["http:","https:"].includes(u.protocol)) throw new Error(); return s; }catch{ throw new BadRequestException(`${n} must be a valid URL`); } }
  private ad=(a:any)=>({id:a.id,title:a.title,body:a.body,imageUrl:a.imageUrl,targetUrl:a.targetUrl,placement:a.placement,status:a.status,startsAt:a.startsAt?.toISOString?.()??null,endsAt:a.endsAt?.toISOString?.()??null,createdBy:a.createdBy,createdAt:a.createdAt.toISOString(),updatedAt:a.updatedAt.toISOString()});
  private admin=(a:any)=>({id:a.id,email:a.email,name:a.name,role:a.role,active:a.active,lastLoginAt:a.lastLoginAt?.toISOString?.()??null,createdAt:a.createdAt.toISOString(),updatedAt:a.updatedAt.toISOString()});
}
