import "reflect-metadata";
import { strict as assert } from "node:assert";
import { BadRequestException, ForbiddenException } from "@nestjs/common";
import { Reflector } from "@nestjs/core";
import { AuthService } from "../src/auth";
import { AdminApiService } from "../src/admin/admin-api.service";
import { AdminRolesGuard } from "../src/admin/guards/admin-roles.guard";

type Role = "SUPER_ADMIN"|"SUPPORT"|"ANALYST"|"AD_MANAGER";
const now=()=>new Date(); const admin=(role:Role="SUPER_ADMIN")=>({id:`admin-${role}`,email:`${role}@x.test`,name:role,role,active:true,lastLoginAt:null,createdAt:now().toISOString(),updatedAt:now().toISOString(),sessionId:"s"});
class DB { users:any[]=[]; families:any[]=[]; ics:any[]=[]; ads:any[]=[]; admins:any[]=[]; audits:any[]=[]; tasks:any[]=[]; reminders:any[]=[]; events:any[]=[];
  client:any={ $transaction: async (fn:any)=>fn(this.client),
    user:{ count:async(a:any={})=>this.filter(this.users,a.where).length, findMany:async(a:any={})=>this.sort(this.filter(this.users,a.where),a.orderBy).slice(a.skip??0,(a.skip??0)+(a.take??99)).map(u=>this.selUser(u,a.select)), findUnique:async({where,select}:any)=>{const u=this.users.find(x=>x.id===where.id); return u?this.selUser(u,select):null}, update:async({where,data,select}:any)=>{const u=this.users.find(x=>x.id===where.id); Object.assign(u,data,{updatedAt:now()}); return this.selUser(u,select)}},
    family:{ count:async()=>this.families.length }, calendarIcsSource:{ count:async(a:any={})=>this.filter(this.ics,a.where).length }, calendarEvent:{ count:async(a:any={})=>this.filter(this.events,a.where).length }, task:{ count:async(a:any={})=>this.filter(this.tasks,a.where).length }, reminder:{ count:async(a:any={})=>this.filter(this.reminders,a.where).length },
    advertisement:{ count:async(a:any={})=>this.filter(this.ads,a.where).length, groupBy:async()=>Object.entries(this.ads.reduce((m:any,a)=>{m[a.status]=(m[a.status]??0)+1; return m},{})).map(([status,count])=>({status,_count:{_all:count}})), findMany:async(a:any={})=>this.filter(this.ads,a.where).slice(a.skip??0,(a.skip??0)+(a.take??99)).map(x=>({...x,createdBy:this.admins.find(a=>a.id===x.createdById)})), findUnique:async({where,select,include}:any)=>{const a=this.ads.find(x=>x.id===where.id); if(!a)return null; if(select)return {id:a.id,status:a.status,events:a.events??[]}; return {...a,createdBy:this.admins.find(x=>x.id===a.createdById)}}, create:async({data}:any)=>{const a={id:`ad-${this.ads.length+1}`,...data,events:[],createdAt:now(),updatedAt:now()}; this.ads.push(a); return {...a,createdBy:this.admins.find(x=>x.id===a.createdById)}}, update:async({where,data}:any)=>{const a=this.ads.find(x=>x.id===where.id); Object.assign(a,data,{updatedAt:now()}); return {...a,createdBy:this.admins.find(x=>x.id===a.createdById)}}, delete:async({where}:any)=>{this.ads=this.ads.filter(x=>x.id!==where.id); return {}}},
    adminUser:{ findMany:async()=>this.admins, create:async({data}:any)=>{const a={id:`admin-${this.admins.length+1}`,...data,lastLoginAt:null,createdAt:now(),updatedAt:now()}; this.admins.push(a); return a}, findUnique:async({where}:any)=>this.admins.find(a=>a.id===where.id)??null, count:async({where}:any)=>this.admins.filter(a=>a.id!==where.id.not&&a.role===where.role&&a.active===where.active).length, update:async({where,data}:any)=>{const a=this.admins.find(x=>x.id===where.id); Object.assign(a,data,{updatedAt:now()}); return a}},
    adminAuditLog:{ create:async({data}:any)=>{const l={id:`audit-${this.audits.length+1}`,...data,createdAt:now(),adminUser:this.admins.find(a=>a.id===data.adminUserId)}; this.audits.push(l); return l}, count:async(a:any={})=>this.filter(this.audits,a.where).length, findMany:async(a:any={})=>this.filter(this.audits,a.where).sort((a,b)=>+b.createdAt-+a.createdAt).slice(a.skip??0,(a.skip??0)+(a.take??99)) }};
  filter(arr:any[],w:any={}){return arr.filter(x=>!w||Object.entries(w).every(([k,v]:any)=>k==='OR'?v.some((o:any)=>this.filter([x],o).length):v?.contains!==undefined?String(x[k]).toLowerCase().includes(String(v.contains).toLowerCase()):v?.gte?x[k]>=v.gte:v?.not!==undefined?x[k]!==v.not:x[k]===v))} sort(a:any[],o:any){if(o?.createdAt)return [...a].sort((x,y)=>o.createdAt==='asc'?+x.createdAt-+y.createdAt:+y.createdAt-+x.createdAt); return a} selUser(u:any,_s:any){return {...u,memberships:u.memberships??[]}}
}
function svc(){const db=new DB(); const auth={hashPassword:async(p:string)=>`hash:${p}`} as AuthService; return {db,service:new AdminApiService(db as any, auth)} }
function roleAllowed(required:Role[], actual:Role){ class R extends Reflector{getAllAndOverride(){return required}} const g=new AdminRolesGuard(new R()); try{return g.canActivate({switchToHttp:()=>({getRequest:()=>({admin:{role:actual}})}),getHandler:()=>({}),getClass:()=>({})} as any)}catch{return false}}
async function run(){ const {db,service}=svc(); const d=new Date(); db.users.push({id:'u1',name:'Alice',email:'alice@test.no',createdAt:d,updatedAt:d,passwordHash:'secret',memberships:[{family:{id:'f1',name:'Fam',_count:{members:2}},updatedAt:d}]},{id:'u2',name:'Bob',email:'bob@test.no',createdAt:d,updatedAt:d,deactivatedAt:d}); db.families.push({id:'f1'}); db.ics.push({active:true}); db.admins.push({id:'sa',email:'sa@test.no',name:'SA',role:'SUPER_ADMIN',active:true,createdAt:d,updatedAt:d,lastLoginAt:null},{id:'admgr',email:'ad@test.no',name:'AD',role:'AD_MANAGER',active:true,createdAt:d,updatedAt:d,lastLoginAt:null}); db.ads.push({id:'a1',title:'A',body:'B',placement:'HOME',status:'ACTIVE',createdById:'admgr',createdAt:d,updatedAt:d,events:[]});
  assert.equal((await service.dashboard()).totalUsers,2); assert.equal((await service.dashboard()).activeAdvertisements,1);
  const users=await service.users({search:'ali',pageSize:10}); assert.equal(users.total,1); assert.equal('passwordHash' in users.items[0],false);
  await service.setUserStatus('u1',{active:false},admin('SUPPORT') as any,{}); assert.equal(db.users[0].deactivatedAt instanceof Date,true); assert.equal(db.audits.at(-1).action,'USER_DISABLED');
  assert.equal(roleAllowed(['SUPER_ADMIN','SUPPORT'] as Role[],'ANALYST'),false);
  assert.equal(roleAllowed(['SUPER_ADMIN','AD_MANAGER'] as Role[],'AD_MANAGER'),true); assert.equal(roleAllowed(['SUPER_ADMIN','SUPPORT'] as Role[],'AD_MANAGER'),false); assert.equal(roleAllowed(['SUPER_ADMIN'] as Role[],'SUPPORT'),false);
  await service.createAdvertisement({title:'T',body:'B',placement:'HOME',targetUrl:'https://example.com',status:'DRAFT'},admin('AD_MANAGER') as any,{}); assert.equal(db.audits.at(-1).action,'ADVERTISEMENT_CREATED');
  await assert.rejects(()=>service.createAdvertisement({title:'T',body:'B',placement:'HOME',targetUrl:'notaurl'},admin() as any,{}),BadRequestException); await assert.rejects(()=>service.createAdvertisement({title:'T',body:'B',placement:'HOME',startsAt:'2026-01-02',endsAt:'2026-01-01'},admin() as any,{}),BadRequestException);
  await service.createAdmin({email:'new@test.no',password:'password123',name:'New',role:'SUPPORT'},admin() as any,{}); assert.equal('passwordHash' in (await service.adminUsers())[0],false);
  await assert.rejects(()=>service.updateAdmin('sa',{active:false},admin() as any,{}),BadRequestException);
  await assert.rejects(()=>service.auditLog({},admin('SUPPORT') as any),ForbiddenException);
  console.log('admin api tests passed'); }
void run();
