import "reflect-metadata";
import { strict as assert } from "node:assert";
import { BadRequestException, ConflictException, ForbiddenException } from "@nestjs/common";
import { Reflector } from "@nestjs/core";
import { AuthService } from "../src/auth";
import { AdminApiService } from "../src/admin/admin-api.service";
import { AdminRolesGuard } from "../src/admin/guards/admin-roles.guard";

type Role = "SUPER_ADMIN"|"SUPPORT"|"ANALYST"|"AD_MANAGER";
const now=()=>new Date(); const admin=(role:Role="SUPER_ADMIN")=>({id:`admin-${role}`,email:`${role}@x.test`,name:role,role,active:true,lastLoginAt:null,createdAt:now().toISOString(),updatedAt:now().toISOString(),sessionId:"s"});
class DB { users:any[]=[]; families:any[]=[]; ics:any[]=[]; ads:any[]=[]; admins:any[]=[]; audits:any[]=[]; tasks:any[]=[]; reminders:any[]=[]; events:any[]=[]; feedback:any[]=[];
  client:any={ $transaction: async (fn:any)=>fn(this.client),
    user:{ count:async(a:any={})=>this.filter(this.users,a.where).length, findMany:async(a:any={})=>this.sort(this.filter(this.users,a.where),a.orderBy).slice(a.skip??0,(a.skip??0)+(a.take??99)).map(u=>this.selUser(u,a.select)), findUnique:async({where,select}:any)=>{const u=this.users.find(x=>x.id===where.id); return u?this.selUser(u,select):null}, update:async({where,data,select}:any)=>{const u=this.users.find(x=>x.id===where.id); Object.assign(u,data,{updatedAt:now()}); return this.selUser(u,select)}},
    family:{ count:async(a:any={})=>this.filter(this.families,a.where).length, findMany:async(a:any={})=>this.filter(this.families,a.where).slice(a.skip??0,(a.skip??0)+(a.take??99)).map(f=>({...f,_count:{members:f.members?.length??0}})), findUnique:async({where}:any)=>this.families.find(f=>(where.id&&f.id===where.id)||(where.code&&f.code===where.code))??null, create:async({data}:any)=>{const f={id:`f${this.families.length+1}`,name:data.name,code:data.code,createdAt:now(),updatedAt:now(),members:[] as any[]}; if(data.members?.create) f.members.push({id:`m${Date.now()}`,familyId:f.id,...data.members.create,createdAt:now(),updatedAt:now()}); this.families.push(f); return f} }, calendarIcsSource:{ count:async(a:any={})=>this.filter(this.ics,a.where).length }, calendarEvent:{ count:async(a:any={})=>this.filter(this.events,a.where).length }, task:{ count:async(a:any={})=>this.filter(this.tasks,a.where).length }, reminder:{ count:async(a:any={})=>this.filter(this.reminders,a.where).length },
    advertisement:{ count:async(a:any={})=>this.filter(this.ads,a.where).length, groupBy:async()=>Object.entries(this.ads.reduce((m:any,a)=>{m[a.status]=(m[a.status]??0)+1; return m},{})).map(([status,count])=>({status,_count:{_all:count}})), findMany:async(a:any={})=>this.filter(this.ads,a.where).slice(a.skip??0,(a.skip??0)+(a.take??99)).map(x=>({...x,createdBy:this.admins.find(a=>a.id===x.createdById)})), findUnique:async({where,select,include}:any)=>{const a=this.ads.find(x=>x.id===where.id); if(!a)return null; if(select)return {id:a.id,status:a.status,events:a.events??[]}; return {...a,createdBy:this.admins.find(x=>x.id===a.createdById)}}, create:async({data}:any)=>{const a={id:`ad-${this.ads.length+1}`,...data,events:[],createdAt:now(),updatedAt:now()}; this.ads.push(a); return {...a,createdBy:this.admins.find(x=>x.id===a.createdById)}}, update:async({where,data}:any)=>{const a=this.ads.find(x=>x.id===where.id); Object.assign(a,data,{updatedAt:now()}); return {...a,createdBy:this.admins.find(x=>x.id===a.createdById)}}, delete:async({where}:any)=>{this.ads=this.ads.filter(x=>x.id!==where.id); return {}}},
    adminUser:{ findMany:async()=>this.admins, create:async({data}:any)=>{const a={id:`admin-${this.admins.length+1}`,...data,lastLoginAt:null,createdAt:now(),updatedAt:now()}; this.admins.push(a); return a}, findUnique:async({where}:any)=>this.admins.find(a=>a.id===where.id)??null, count:async({where}:any)=>this.admins.filter(a=>a.id!==where.id.not&&a.role===where.role&&a.active===where.active).length, update:async({where,data}:any)=>{const a=this.admins.find(x=>x.id===where.id); Object.assign(a,data,{updatedAt:now()}); return a}},
    adminAuditLog:{ create:async({data}:any)=>{const l={id:`audit-${this.audits.length+1}`,...data,createdAt:now(),adminUser:this.admins.find(a=>a.id===data.adminUserId)}; this.audits.push(l); return l}, count:async(a:any={})=>this.filter(this.audits,a.where).length, findMany:async(a:any={})=>this.filter(this.audits,a.where).sort((a,b)=>+b.createdAt-+a.createdAt).slice(a.skip??0,(a.skip??0)+(a.take??99)) },
    familyMember:{ findFirst:async({where,include}:any)=>{const all=this.families.flatMap(f=>(f.members??[]).map((m:any)=>({...m,family:f}))); const m=all.find((m:any)=>(!where.userId||m.userId===where.userId)&&(!where.familyId||m.familyId===where.familyId)); return m&&include?.family?{...m,family:m.family}:m??null}, count:async({where}:any)=>this.families.flatMap(f=>f.members??[]).filter((m:any)=>m.familyId===where.familyId&&m.role===where.role&&m.userId!==where.userId?.not).length, create:async({data}:any)=>{const f=this.families.find(x=>x.id===data.familyId); const m={id:`m-${Math.random()}`,...data,createdAt:now(),updatedAt:now()}; f.members.push(m); return m}, deleteMany:async({where}:any)=>{let count=0; for(const f of this.families){const before=f.members.length; f.members=f.members.filter((m:any)=>!(m.userId===where.userId&&where.familyId.in.includes(m.familyId))); count+=before-f.members.length} return {count}}},
    familyInvitation:{ updateMany:async()=>({count:0}) },
    feedbackSubmission:{ count:async(a:any={})=>this.filter(this.feedback,a.where).length, findMany:async(a:any={})=>this.sort(this.filter(this.feedback,a.where),a.orderBy).slice(a.skip??0,(a.skip??0)+(a.take??99)).map(f=>this.withFeedbackRelations(f)), findUnique:async({where}:any)=>{const f=this.feedback.find(x=>x.id===where.id); return f?this.withFeedbackRelations(f):null} } };
  withFeedbackRelations(f:any){ return {...f,user:this.users.find(u=>u.id===f.userId)??null,family:this.families.find(x=>x.id===f.familyId)??null}; }
  filter(arr:any[],w:any={}){return arr.filter(x=>!w||Object.entries(w).every(([k,v]:any)=>k==='OR'?v.some((o:any)=>this.filter([x],o).length):v?.contains!==undefined?String(x[k]).toLowerCase().includes(String(v.contains).toLowerCase()):v?.gte?x[k]>=v.gte:v?.not!==undefined?x[k]!==v.not:x[k]===v))} sort(a:any[],o:any){if(o?.createdAt)return [...a].sort((x,y)=>o.createdAt==='asc'?+x.createdAt-+y.createdAt:+y.createdAt-+x.createdAt); return a} selUser(u:any,_s:any){return {...u,memberships:u.memberships??[]}}
}
function svc(){const db=new DB(); const auth={hashPassword:async(p:string)=>`hash:${p}`} as AuthService; return {db,service:new AdminApiService(db as any, auth)} }
function roleAllowed(required:Role[], actual:Role){ class R extends Reflector{getAllAndOverride(){return required}} const g=new AdminRolesGuard(new R()); try{return g.canActivate({switchToHttp:()=>({getRequest:()=>({admin:{role:actual}})}),getHandler:()=>({}),getClass:()=>({})} as any)}catch{return false}}
async function run(){ const {db,service}=svc(); const d=new Date(); db.users.push({id:'u1',name:'Alice',email:'alice@test.no',createdAt:d,updatedAt:d,passwordHash:'secret',memberships:[{id:'m1',familyId:'f1',role:'OWNER',family:{id:'f1',name:'Fam',_count:{members:2}},updatedAt:d}]},{id:'u2',name:'Bob',email:'bob@test.no',createdAt:d,updatedAt:d,deactivatedAt:d}); db.families.push({id:'f1',name:'Fam',code:'FA-ABC123',createdAt:d,updatedAt:d,members:[{id:'m1',userId:'u1',familyId:'f1',displayName:'Alice',role:'OWNER'}]},{id:'f2',name:'Target',code:'FA-XYZ789',createdAt:d,updatedAt:d,members:[{id:'m2',userId:'owner2',familyId:'f2',displayName:'Owner',role:'OWNER'}]}); db.ics.push({active:true}); db.admins.push({id:'sa',email:'sa@test.no',name:'SA',role:'SUPER_ADMIN',active:true,createdAt:d,updatedAt:d,lastLoginAt:null},{id:'admgr',email:'ad@test.no',name:'AD',role:'AD_MANAGER',active:true,createdAt:d,updatedAt:d,lastLoginAt:null}); db.ads.push({id:'a1',title:'A',body:'B',placement:'HOME',status:'ACTIVE',createdById:'admgr',createdAt:d,updatedAt:d,events:[]});
  const older=new Date(d.getTime()-1000); db.feedback.push({id:'fb-old',type:'feedback',message:'older general feedback message',userId:'u1',familyId:'f1',userAgent:'Safari on iOS',appVersion:'1.0.0',createdAt:older},{id:'bug-new',type:'bug',message:'newest bug report message with enough detail',userId:'u2',familyId:null,userAgent:null,appVersion:null,createdAt:d},{id:'fb-new',type:'feedback',message:'newest general feedback message',userId:'u2',familyId:'f1',userAgent:'Chrome on macOS',appVersion:'1.1.0',createdAt:d});
  assert.equal((await service.dashboard()).totalUsers,2); assert.equal((await service.dashboard()).activeAdvertisements,1);
  const feedback=await service.feedbackSubmissions(); assert.equal(feedback.bugReports.length,1); assert.equal(feedback.generalFeedback.length,2); assert.equal(feedback.bugReports[0].id,'bug-new'); assert.equal(feedback.generalFeedback[0].id,'fb-new'); assert.equal(feedback.generalFeedback[1].id,'fb-old'); assert.equal(feedback.generalFeedback[0].status,'New'); assert.equal(feedback.generalFeedback[0].familyName,'Fam'); assert.equal(feedback.generalFeedback[0].email,'bob@test.no');
  const feedbackDetail=await service.feedbackSubmission('fb-new'); assert.equal(feedbackDetail.message,'newest general feedback message'); assert.equal(feedbackDetail.userAgent,'Chrome on macOS');
  
  const invite=await service.familyInviteCode('u1','f1',admin('SUPPORT') as any,{}); assert.equal(invite.inviteCode,'FA-ABC123'); assert.equal(JSON.stringify(db.audits.at(-1).metadata).includes('FA-ABC123'),false);
  const fams=await service.families({search:'tar',userId:'u1'}); assert.equal(fams.items[0].familyName,'Target'); assert.equal('inviteCode' in fams.items[0],false);
  await assert.rejects(()=>service.moveUserFamily('u1',{targetFamilyId:'f2',role:'PARENT',reason:'needs support move'},admin('SUPPORT') as any,{}),ConflictException);
  db.families[0].members.push({id:'m-other',userId:'other',familyId:'f1',displayName:'Other',role:'OWNER'});
  const moved=await service.moveUserFamily('u1',{targetFamilyId:'f2',role:'PARENT',reason:'needs support move'},admin('SUPPORT') as any,{}); assert.equal(moved.targetFamilyId,'f2'); assert.equal(db.families[1].members.some((m:any)=>m.userId==='u1'),true); assert.equal(db.audits.at(-1).action,'USER_MOVED_TO_FAMILY');
  db.users.push({id:'u3',name:'Cara',email:'cara@test.no',createdAt:d,updatedAt:d,passwordHash:'secret',memberships:[]}); const created=await service.createFamilyForUser('u3',{name:'Cara Family',reason:'needs first family'},admin('SUPPORT') as any,{}); assert.equal(created.role,'OWNER'); assert.equal(db.audits.at(-1).action,'FAMILY_CREATED_BY_ADMIN'); assert.equal(JSON.stringify(db.audits.at(-1).metadata).includes('FA-'),false);

  const users=await service.users({search:'ali',pageSize:10}); assert.equal(users.total,1); assert.equal('passwordHash' in users.items[0],false);
  await service.setUserStatus('u1',{active:false},admin('SUPPORT') as any,{}); assert.equal(db.users[0].deactivatedAt instanceof Date,true); assert.equal(db.audits.at(-1).action,'USER_DISABLED');
  assert.equal(roleAllowed(['SUPER_ADMIN','SUPPORT'] as Role[],'ANALYST'),false); assert.equal(roleAllowed(['SUPER_ADMIN','SUPPORT'] as Role[],'SUPPORT'),true);
  assert.equal(roleAllowed(['SUPER_ADMIN','AD_MANAGER'] as Role[],'AD_MANAGER'),true); assert.equal(roleAllowed(['SUPER_ADMIN','SUPPORT'] as Role[],'AD_MANAGER'),false); assert.equal(roleAllowed(['SUPER_ADMIN'] as Role[],'SUPPORT'),false);
  await service.createAdvertisement({title:'T',body:'B',placement:'HOME',targetUrl:'https://example.com',status:'DRAFT'},admin('AD_MANAGER') as any,{}); assert.equal(db.audits.at(-1).action,'ADVERTISEMENT_CREATED');
  await assert.rejects(()=>service.createAdvertisement({title:'T',body:'B',placement:'HOME',targetUrl:'notaurl'},admin() as any,{}),BadRequestException); await assert.rejects(()=>service.createAdvertisement({title:'T',body:'B',placement:'HOME',startsAt:'2026-01-02',endsAt:'2026-01-01'},admin() as any,{}),BadRequestException);
  await service.createAdmin({email:'new@test.no',password:'password123',name:'New',role:'SUPPORT'},admin() as any,{}); assert.equal('passwordHash' in (await service.adminUsers())[0],false);
  await assert.rejects(()=>service.updateAdmin('sa',{active:false},admin() as any,{}),BadRequestException);
  await assert.rejects(()=>service.auditLog({},admin('SUPPORT') as any),ForbiddenException);
  {
    const ddb:any={audits:[],users:[{id:"du1",memberships:[{id:"dm1",familyId:"df1",role:"PARENT"}]},{id:"du2",memberships:[{id:"dm2",familyId:"df1",role:"OWNER"}]},{id:"du3",memberships:[{id:"dm3",familyId:"df1",role:"CHILD"},{id:"dm4",familyId:"df2",role:"PARENT"}]}],families:[{id:"df1",members:[{id:"dm1",userId:"du1",familyId:"df1",role:"PARENT"},{id:"dm2",userId:"du2",familyId:"df1",role:"OWNER"},{id:"dm3",userId:"du3",familyId:"df1",role:"CHILD"}]},{id:"df2",members:[{id:"dm4",userId:"du3",familyId:"df2",role:"PARENT"}]}]};
    const rows:any={userSession:[{userId:"du1"}],passwordResetToken:[],pushDevice:[{userId:"du1"}],notification:[{recipientUserId:"du1",familyId:"df1"}],familyInvitation:[{createdByUserId:"du1",familyId:"df1"}],shoppingListInvitation:[],wishlistShareInvitation:[],wishlistItem:[{ownerUserId:"du1",familyId:"df1"}],wishlistItemReservation:[],shoppingListAccess:[],shoppingList:[{familyId:"df1",ownerUserId:"du1"}],shoppingListItem:[{createdByUserId:"du1",shoppingList:{familyId:"df1"}}],calendarEvent:[{createdByUserId:"du1",familyId:"df1"}],reminder:[{createdByUserId:"du1",familyId:"df1"}],task:[],feedbackSubmission:[],calendarEventParticipant:[],calendarEventException:[],calendarIcsSource:[],calendarExportFeed:[],familyCustomShoppingItem:[],mealPlan:[],mealPlanDay:[],reminderAudienceMember:[],list:[],listItem:[],schoolWeekReminder:[]};
    const match=(x:any,w:any):boolean=>!w||Object.entries(w).every(([k,v]:any)=>k==="OR"?v.some((o:any)=>match(x,o)):v?.in? v.in.includes(x[k]):v?.not!==undefined?x[k]!==v.not:typeof v==="object"&&v!==null&&!Array.isArray(v)?match(x[k],v):x[k]===v);
    const delegate=(name:string)=>({count:async({where}:any={})=>(rows[name]??[]).filter((x:any)=>match(x,where)).length});
    ddb.client={$transaction:async(fn:any)=>fn(ddb.client),adminAuditLog:{create:async({data}:any)=>{ddb.audits.push(data); return data}},user:{findUnique:async({where}:any)=>ddb.users.find((u:any)=>u.id===where.id)??null,delete:async({where}:any)=>{ddb.users=ddb.users.filter((u:any)=>u.id!==where.id); ddb.families.forEach((f:any)=>f.members=f.members.filter((m:any)=>m.userId!==where.id)); return {}},deleteMany:async({where}:any)=>{const ids=where.id.in; const c=ddb.users.filter((u:any)=>ids.includes(u.id)).length; ddb.users=ddb.users.filter((u:any)=>!ids.includes(u.id)); ddb.families.forEach((f:any)=>f.members=f.members.filter((m:any)=>!ids.includes(m.userId))); return {count:c}}},family:{findUnique:async({where}:any)=>ddb.families.find((f:any)=>f.id===where.id)??null,delete:async({where}:any)=>{ddb.families=ddb.families.filter((f:any)=>f.id!==where.id); return {}}},familyMember:{count:async({where}:any)=>ddb.families.flatMap((f:any)=>f.members).filter((m:any)=>match(m,where)).length}};
    for(const n of Object.keys(rows)) ddb.client[n]=delegate(n);
    const deletionService=new AdminApiService(ddb as any, {hashPassword:async(p:string)=>p} as any);
    const impact=await deletionService.userDeletionImpact("du1"); assert.equal(impact.sessions,1); assert.equal(impact.membershipCount,1);
    await deletionService.deleteUser("du1",{reason:"gdpr erasure request"},admin() as any,{}); assert.equal(ddb.users.some((u:any)=>u.id==="du1"),false); assert.equal(ddb.audits.at(-1).action,"USER_DELETED_BY_ADMIN");
    await assert.rejects(()=>deletionService.deleteUser("du2",{reason:"gdpr erasure request"},admin() as any,{}),ConflictException);
    const familyImpact=await deletionService.familyDeletionImpact("df1"); assert.equal(familyImpact.usersDeleted,1); assert.equal(familyImpact.usersDetached,1);
    const deleted=await deletionService.deleteFamily("df1",{reason:"owner requested full family deletion"},admin() as any,{}); assert.equal(deleted.usersDeleted,1); assert.equal(ddb.users.some((u:any)=>u.id==="du3"),true); assert.equal(ddb.families.some((f:any)=>f.id==="df1"),false); assert.equal(ddb.audits.at(-1).action,"FAMILY_DELETED_BY_ADMIN");
    assert.equal(roleAllowed(["SUPER_ADMIN"] as Role[],"SUPER_ADMIN"),true); assert.equal(roleAllowed(["SUPER_ADMIN"] as Role[],"SUPPORT"),false); assert.equal(roleAllowed(["SUPER_ADMIN"] as Role[],"ANALYST"),false); assert.equal(roleAllowed(["SUPER_ADMIN"] as Role[],"AD_MANAGER"),false);
  }
  console.log('admin api tests passed'); }
void run();
